### ISSUE TITLE
Screen sharing from Mobile is blank after few seconds of inactivity

### ISSUE THREAD

**Issue by tj0xin** [jitsi/jitsi-meet#11084]
**Description:**
When screen sharing from Mobile phone (Android or iOS) if there is not activity on screen (scrolling or Animated objects) for few seconds (15 or More seconds) the shared screen is automatically blank on all the participant except safari on Mac. 

**Steps to reproduce:**
Step 1: Tested on 3 Devices (2 Mobile Phones (Android and iOS) and 1 Laptop (Chrome))

Step 2: Start a Meeting, get into the single Meeting room.

Step 3: Start Screen Share on Mobile phone and Open any documents (full screen preferred). (Make sure there is no clock or Animated notifications (Android) running on screen during screen sharing also make sure the “Red Colored” Pill shaped broadcast notification in top left corner is not seen (iOS Only) otherwise the issue won’t be reproduced. 
- (iOS) Open stock E-Mail app and open any document (DOCX / PPT / PDF) in Landscape mode and such that it hides the Red broadcast icon (Red Pill), and keep it idle that way the Red Pill wont be shown on screen.

Step 4: Keep the Document idle for 10-15 seconds maybe a bit longer (Don’t touch the screen / change screen Orientation)

Now, the Shared Screen on other two non sharing devices (Participants) will be blank and on Windows / Chrome it will show as “Inactive” in connection status.

Again, tap the screen or move the document, then again the shared screen is seen.

**Expected behavior:**
The screen sharing should not be blanked in any case, it should continue to be shown till it is interrupted by user.

**Actual behavior:**
When screen sharing from Mobile phone (Android or iOS) if there is not activity on screen (scrolling or Animated objects) for few seconds (15 or More seconds) the shared screen is automatically blank on all the participant except safari on Mac. 

 **Server information:**
**- Jitsi Meet version:** 2.0.6826-1
**- Operating System:** Ubuntu 20.04.3 LTS 

**Client information:**
**- Browser / app version:** Browser Version (Chrome): 99.0.4844.51 / App Version: 22.0.1 Build 169
**- Operating System:** Microsoft Windows 10 64Bit

**Additional information:**
This bug has affected both Jitsi Meet deployments (meet.jit.si) and (beta.meet.jit.si) as well as other external deployments.

I hope this is resolved as soon as possible. 

There is an open discussion on Community forum: https://community.jitsi.org/t/screen-sharing-on-mobile-blank/112005

@saghul has already tested and can reproduce the bug.

Thanks

**Comment by saghul** [comment]
Conjecture: the platform APIs (ReplayKit and MediaProjection) might not be giving us frames if the content is static. We may need to run our own "clock" and just store frames and poll them at the given framerate, if this was the problem, that is.

**Comment by perburn** [comment]
Having the same problem when screen sharing from a Linux desktop that is using Wayland. Some seconds after there is no change in the shared stream (e.g. sharing a slide) the video stream is blanked out for all participants and the avatar of the sharing user is shown.

**Comment by saghul** [comment]
Oh that's bad. I could not reproduce it on macOS, but I'll try again none the less.

**Comment by tj0xin** [comment]
> Oh that's bad. I could not reproduce it on macOS, but I'll try again none the less.

Even i couldn't reproduce the bug on MacOS.

**Comment by saghul** [comment]
Thanks!

**Comment by prathm29** [comment]
> Oh that's bad. I could not reproduce it on macOS, but I'll try again none the less.

I cant reproduce on MACOS as well

**Comment by prathm29** [comment]
this should be solved asap, i wonder why other peoples aren't complaining?

**Comment by saghul** [comment]
Sorry pal, you don't get to decide what should or shouldn't be worked on and with what urgency.

If that's all you are willing to crontribute I'd suggest you stay silent.

The reason why not many people are complaining is simple: it seems to happen on corner cases. Usually people share content that "moves" one way or another, which triggers an update.

**Comment by prathm29** [comment]
> Sorry pal, you don't get to decide what should or shouldn't be worked on and with what urgency.

Of course man, why so rude?



> If that's all you are willing to crontribute I'd suggest you stay silent.

Really appreciate your kind suggestion. 



> The reason why not many people are complaining is simple: it seems to happen on corner cases. Usually people share content that "moves" one way or another, which triggers an update.

Usually? Looks like you don't attend conferences regularly or you are unaware of how conferences happen. Majority of them screen share PPT or Word doc etc and the slide / page is expected to be kept and stay on screen till it is explained / conveyed to the meeting attendees which can usually stay on screen anywhere between 30 Seconds to 30 minutes. and as @tj0xin pointed out it doesn't stay even 10-15 seconds on screen. Isn't it that SIMPLE to understand?

**Comment by saghul** [comment]
> Of course man, why so rude?

Work on your delivery. If after being pointed out you don't understand the tone is not appreciated this will be my last reply.

> Usually? Looks like you don't attend conferences regularly or you are unaware of how conferences happen. Majority of them screen share PPT or Word doc etc and the slide / page is expected to be kept and stay on screen till it is explained / conveyed to the meeting attendees which can usually stay on screen anywhere between 30 Seconds to 30 minutes. and as @tj0xin pointed out it doesn't stay even 10-15 seconds on screen.

Any pixel movement will trigger an update, for instance, on iOS, there is a red indicator that subtly pulsates, this causes updates so the problem doesn't manifest on portrait orientation, but it does on landscape, because there is no such indicator. Note that this is on the sender side.

> Isn't it that SIMPLE to understand?

I understand it perfectly fine.

**Comment by prathm29** [comment]
> Work on your delivery. If after being pointed out you don't understand the tone is not appreciated this will be my last reply.

I apologies, i didn't mean being rude / aggressive on my initial messages but was coming out of frustration. It didn't mean anything to You (Personally or Jitsi Team). We are receiving lots of complaints everyday from people using it on our deployment. 

> Any pixel movement will trigger an update, for instance, on iOS, there is a red indicator that subtly pulsates, this causes updates so the problem doesn't manifest on portrait orientation, but it does on landscape, because there is no such indicator. Note that this is on the sender side.

Agree, but while on Portrait mode the red indicator disappears.

**Comment by tj0xin** [comment]
> Of course man, why so rude?

Your comments should be respectable. Also, please note this is a Community driven project other people including Saghul are working extremely hard to create and maintain the project 
 the way it is right now, have some courtesy!

If you are willing to contribute the doors are wide open. 

Hope you get the point.

**Comment by denzs** [comment]
We are facing the same issue within our customers instance but also on meet.jit.si.

We are able to reproduce the issue with Windows 10 with Edge and Chrome.
If the screensharing is running within Firefox is seems to stay stable.
With Edge/Chrome the screensharing gets black after 10 seconds.

For reproducing it is important to have nothing moving on the screen,
so i just share the screen and after that i minimize every application to share just the desktop, then the clock is the only moving part every minute..

With my linux (running Xorg) client i am not able to reproduce the problem using chrome.

**Comment by denzs** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1099280 looks quite interesting to me but i am not deep enough into the details :-/

**Comment by saghul** [comment]
Yep, that the issue. We have fixed it in meet.jit.si already by ignoring mute events for SS tracks. The fix will be part of the next stable release.

Coincidentally this also fixes the case case when mobile shares and there are no frames when the content is static.

**Comment by denzs** [comment]
@saghul i just wanted to let you know we are still facing the issue on meet.jit.si too
beta.meet.jit.si seems to have issues at this very moment..

**Comment by saghul** [comment]
Hum, you shouldn't be seeing issues. How are you testing it?

**Comment by denzs** [comment]
Hmm after playing around with meet.jit.si a bit more we are not able to reproduce the interruption of the screensharing (when it is the selected stream) but there are still effects when switching from main view to tile view again..

When the shared screen is selected it seems to work, but when we switch back to tile view the corresponding tile stays grey for very long (until activity on the senders site?!).

At the moment we are testing in https://meet.jit.si/tester123 if you want to take a look.
But you should propably be able to reproduce it by yourself easily of course :)

**Comment by saghul** [comment]
> Hmm after playing around with meet.jit.si a bit more we are not able to reproduce the interruption of the screensharing (when it is the selected stream) but there are still effects when switching from main view to tile view again..
> 
> When the shared screen is selected it seems to work, but when we switch back to tile view the corresponding tile stays grey for very long (until activity on the senders site?!).

Hum. I suppose the problem is there is no data to render when we attach the stream to the tile. @jallamsetty1 do you reckon we should do something to ask the bridge to request a keyframe?

**Comment by denzs** [comment]
That sounds exactly how it feels to me ;)

**Comment by denzs** [comment]
When switching from tile view to dedicated screen sharing view, the same effect can be observed.
While the tile shows the correct time (from windows desktop), after clicking the tile to make it full screen, i see the time from 2minutes ago... it takes some time (> 10 secs) until it gets refresehd (keyframe?!) .

If the mouse is moved on the sharing client it is refreshed instantly.

**Comment by danielchristianschroeter** [comment]
I am experiencing the same issue with a self-hosted docker-jitsi-meet installation using stable-8719. When initiating a Jitsi session with Google Chrome on a Windows client and performing an entire screen share, the shared screen turns black after approximately 15-20 seconds of inactivity (no mouse movement). However, the screen share remains active if for example a video is playing on the shared screen.
Interestingly, I don't encounter any interruptions when sharing my screen on a Ubuntu 20.04.6 LTS client.

**Comment by jallamsetty1** [comment]
We implemented a workaround in the client which should fixe some of the cases mentioned here, i.e., if the user doesn't switch between tile view and stage view, the client will continue to show the shared screen even if the content of the shared screen doesn't change. This fix hasn't made it to the stable release yet.
This bug has also been fixed in Chromium M116 - https://bugs.chromium.org/p/chromium/issues/detail?id=1099280#c31

**Comment by jallamsetty1** [comment]
> Hum. I suppose the problem is there is no data to render when we attach the stream to the tile. @jallamsetty1 do you reckon we should do something to ask the bridge to request a keyframe?

@saghul The application cannot generate a new key frame request, it is handled by libwebrtc. Maybe the bridge can generate a new keyframe request when it detects that there are no frames coming in for a screensharing source? I have yet to verify the M116 fix. I don't know if it fixes the constraints not being applied part or the firing of the mute/unmute events part or both. Even if the latter is fixed, we would still need new key frames to render the screenshare when the user changes between stage view and tile view.

**Comment by saghul** [comment]
Oh that's nice! THen yeah we can wait for a fix!

**Comment by Reavus3** [comment]
I can only reproduce this on Windows in an edge Browser (Version 115.0.1901.200 (Offizielles Build) (64-Bit)) 
This is with the latest version of Jitsi (jitsi-meet 2.0.8719-1) on an Ubuntu 22.04 Server. Also whilst sharing the entire screen but no visible moving curser or anthing, then it also takes around 10-15 seconds to cut out. I don't see anything in the console or jvb logs when it happens though.

I can confirm that on Mac it is not reproducible in Brave/Edge even without seconds on the clock showing.

 A quick fix, for now, is to have seconds showing on the clock in Windows, then it is constantly moving.

**Comment by enoch85** [comment]
> With Edge/Chrome the screensharing gets black after 10 seconds.

Exactly this issue as well on Edge/Chrome. Not on Firefox. I'm on Ubuntu 22.04 Desktop and the presenter is on Windows 11.

**Comment by saghul** [comment]
It wasn't a config fix, but a code fix. It has now also been released on the latest app versions.
