### ISSUE TITLE
iOS no audio is working for the first time call connected

### ISSUE THREAD

**Issue by mohammadebrahim** [jitsi/jitsi-meet#11423]
There is no audio-only video for the first time call connected

### Steps to reproduce:

1. Kill the app
2. Lock the iPhone
3. Make a call from another device to an ios device.

### Expected behavior:

Should make a call with proper Audio and video every time make a call

### Actual behavior:

First-time audio is not working from the second time and onward audio started working

### Server information:

- Jitsi Meet version: 2.0.6865-2

### Client information:

- Jitsi SDK version: 5.0.0
- Operating System: ios 15

**Comment by saghul** [comment]
How did you implement the calling part? Jitsi Meet does not currently implement that.

**Comment by mohammadebrahim** [comment]
Using JMCallKitProxy calling part implemented

**Comment by mohammadebrahim** [comment]
@saghul  below is the jitsi code -

```
 let defaultOptions = JitsiMeetConferenceOptions.fromBuilder { (builder) in
            builder.serverURL = URL(string: EndPoints.JITSI_SERVER_URL)
            builder.setFeatureFlag("welcomepage.enabled", withBoolean: false)
        }
        JitsiMeet.sharedInstance().defaultConferenceOptions = defaultOptions
        let room: String  = self.callUUID.uuidString
        let token: String  = self.tokenUUID 
        let jitsiMeetView = JitsiMeetView()
        jitsiMeetView.delegate = self
        self.jitsiMeetView = jitsiMeetView
        let options = JitsiMeetConferenceOptions.fromBuilder { (builder) in
            builder.room = room
            builder.token = token
            builder.setFeatureFlag("pip.enabled", withBoolean: false)
            builder.setFeatureFlag("add-people.enabled", withBoolean: false)
            builder.setFeatureFlag("invite.enabled", withBoolean: false)
            builder.setFeatureFlag("raise-hand.enabled", withBoolean: false)
    
        }
        self.view = jitsiMeetView
        jitsiMeetView.join(options)
```

**Comment by saghul** [comment]
So, audio works if the app was running but in the background, but not otherwise?

**Comment by mohammadebrahim** [comment]
> So, audio works if the app was running but in the background, but not otherwise?

Yes, mostly for the first time audio is not working

**Comment by saghul** [comment]
@alexbumbu is this the problem you were looking into?

**Comment by mohammadebrahim** [comment]
@saghul any solution?

**Comment by saghul** [comment]
Unfortunately I don't have one, sorry.

**Comment by chrismcclune** [comment]
I am also seeing this issue. When app is just backgrounded all works fine. When the app has been killed and opened from say CallKit answer then audio does not work. Neither does selecting any other audio route, the selection is made, then nothing changes, when inspecting the audio route menu again, the previous selection remains.

**Comment by chrismcclune** [comment]
No way right now apart from manual, with the same steps as OP.

**Comment by mohammadebrahim** [comment]
@saghul @chrismcclune below is the new step where consistently issue reproduce.

- Accept video audio calls from the ios end.
- End call from ios end.
- Press the home button 
- wait for 30sec
- Again make a call to ios.
- Accept video audio calls from the ios end.


Result - Only video but no audio
Expected - Video and Audio Both.

**Comment by saghul** [comment]
How does one reproduce that with Jitsi Meet? We don't do incoming calls.

**Comment by mohammadebrahim** [comment]
@saghul can we meet one to one so that I will share my screen to show you how to reproduce it?

**Comment by saghul** [comment]
Can't you record a video? I'm a tad busy at the moment.

**Comment by AbhinavCognome** [comment]
We are facing the same issue sometimes when we join a room from IOS devices. For the first time if we start with Video muted. The audio is also not sent/received from both the IOS parties.
We are using a self-hosted JITSI in an Ubuntu environment.

**Comment by saghul** [comment]
What app / SDK version are you using?

**Comment by ambucognome** [comment]
@saghul we are using sdk version 7.0.1

**Comment by saghul** [comment]
I recall we have fixed that somewhere after 8.0.0, you should update.

**Comment by ambucognome** [comment]
@saghul  we have updated sdk version to 8.0.1 but the issue still same.

Use Case -
First call no audio but video works and then from second call everything works fine 

both the devices are on ios 17 

Use Case 2 -

one device on ios 17 and other device is on ios 16 

call from ios 17 to ios 16 works fine without any issue  but vice Verda does not work

**Comment by saghul** [comment]
Please update to the latest as of now.

**Comment by ambucognome** [comment]
@saghul yes we are on latest 8.0.1 but the issue still same ☹️

**Comment by ambucognome** [comment]
@saghul  Actually the issue is with the feature flag **'call-integration.enabled'** when ever I am enabling this feature flag it is giving issue. But when I remove that feature flag it works fine.

@saghul  I have another question. how can we enable this **'close-captions.enabled'** feature flag by default so that english subtitles can be seen as soon as call starts without user interaction for selecting english language.

**Comment by saghul** [comment]
Do you have any CallKit integration in your app?

We currently don't have a way to turn on subtitles from the moment the call starts.
