### ISSUE TITLE
[Android] Tile view cut off in landscape mode

### ISSUE THREAD

**Issue by steepnought** [jitsi/jitsi-meet#11636]
### Description:

With Jitsi Meet 22.2.0 on Android when four participants are in a meeting, tile view is active and the device is held in landscape mode, the lower two tiles are cut off, i.e. the videos extend beyond the bottom edge of the screen.

### Server information:

- Jitsi Meet version: 2.0.7287-1
- Operating System: Debian Bullseye

### Client information:

- Browser / app version: 22.2.0
- Operating System:  Android

**Comment by saghul** [comment]
What android device do you have? Can you share a screenshot?

**Comment by steepnought** [comment]
Tested with Huawei MediaPad and Samsung Galaxy Tab A7 Lite. Find screenshot attached.

![Screenshot](https://user-images.githubusercontent.com/98918408/172684719-378f5572-9634-4917-95e9-51e3e2ad1e8a.png)

**Comment by saghul** [comment]
Thank you.

**Comment by steepnought** [comment]
The changelog of jitsi-meet 2.0.7439-1 says `fix(tile-view, rn) Fix landscape mode tile view` but installing this version on the server does not fix this bug for me.

**Comment by saghul** [comment]
That commit affects the mobile version, you can install the beta.

It's listed there because the codebase is shared.

**Comment by steepnought** [comment]
I use the app from F-Droid. Do they provide betas?

**Comment by saghul** [comment]
No they don't. You'll need to wait for 22.3.0 then. We are hoping to release it next week or so.

**Comment by steepnought** [comment]
Looks like 22.4.0 has been released. Did you forget to put it on F-Droid?

**Comment by saghul** [comment]
The F-Droid teams does the builds.

**Comment by saghul** [comment]
Closing since this was fixed in master.

**Comment by steepnought** [comment]
With 22.4.0 the situation is better but the problem is not completely solved. In landscape mode the bottom tiles are still cut off at the bottom edge but only so much that you can't see the rounded corners of the squares.

Furthermore, when trying to join a call I am now always asked if I want to join normally or in low-bandwidth mode which is pretty annoying.

@saghul I didn't find a button to reopen this issue.

**Comment by saghul** [comment]
> With 22.4.0 the situation is better but the problem is not completely solved. In landscape mode the bottom tiles are still cut off at the bottom edge but only so much that you can't see the rounded corners of the squares.

Can you share a screenshot of your device now?



> Furthermore, when trying to join a call I am now always asked if I want to join normally or in low-bandwidth mode which is pretty annoying.

That has nothing to do with this.

**Comment by steepnought** [comment]
Find screenshot attached.

![Screenshot_20220726](https://user-images.githubusercontent.com/98918408/181087125-2ef126aa-fad8-4e37-9382-076f90e60365.png)

**Comment by saghul** [comment]
@robertpin isn't this what you fixed recently?

**Comment by robertpin** [comment]
@saghul No, I fixed the number of tiles displayed in landscape. I don't remember seeing this issue before.

**Comment by saghul** [comment]
Oh! Can you please look into it?
