### ISSUE TITLE
Unable to reconnect quickly

### ISSUE THREAD

**Issue by shabanov-krl** [jitsi/jitsi-meet#12972]
### Description:

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.02.28-14_13_10.webm](https://user-images.githubusercontent.com/46450095/221838980-8013dbfa-b05d-4bc6-bd82-8476e69e0efa.webm)

### Steps to reproduce:

1. Join meeting
2. Leave meeting
3. Join meeting immediately

### Expected behavior:

Join meeting again

### Actual behavior:

Fast open and close conference modal

### Server information:

- Jitsi Meet version: 7.0.1
- Operating System: default jitsi meet server

### Client information:

- Browser / app version: official android sdk example with 7.0.1 sdk version 
- Operating System: Android 13

### Additional information:

If you wait a bit between steps 2 and 3, then everything is ok

**Comment by hanif-simform** [comment]
Same behaviour I can see in Android,
I can see that, the meeting window closes on `READY_TO_CLOSE` but user actually leaves after Lobby room left especially while end meeting for all.

`2023-02-28 18:31:41.546 25265-25265 JitsiMeetSDK  I  Received Final Close event: READY_TO_CLOSE
  2023-02-28 18:31:46.073 25265-26111 JitsiMeetSDK  I  [modules/xmpp/Lobby.js] Lobby room left!`

The gap is almost 5 Seconds, if during this time, if we try to join, it fails.

So I thing one more event is required to capture the event of Lobby Room Left.

**Comment by zsj8580** [comment]
This issue has been solved in the latest build version

**Comment by erengms** [comment]
Which commit number is the solution?

**Comment by mdhanif-simformsolutions** [comment]
@zsj8580 
I can still reproduce this issue in Version `8.1.2` can you share any more details or specific commit which fixes this issues ?

**Comment by alper9191** [comment]
Hi, what is your commit number ? It still produce the problem. This is urgent issue for us. waiting your support!
Thanks.

**Comment by saghul** [comment]
Are you waiting for the READY_TO_CLOSE event before starting a new activity?

**Comment by alper9191** [comment]
This event (READY_TO_CLOSE) comes up 2 times, about 3 seconds apart, each time. We are waiting first READY_TO_CLOSE but when we Join meeting immediately, the second event drop like the video attached above. 
How could fix this problem ? 
Could you please share us the commit number ? @saghul

**Comment by saghul** [comment]
I don't know the commit that fixed it for the OP, might be a different bug that manifests the same way.

Can you share a full log?

**Comment by alper9191** [comment]
Hi @saghul ,

[log.txt](https://github.com/jitsi/jitsi-meet/files/11555612/log.txt)

log is attached.

**Comment by patelnishantk** [comment]
Facing same issue. Waiting for some resolution

**Comment by shabanov-krl** [comment]
dont resolve in version 0.2.0+1
