### ISSUE TITLE
Inconsistent Video Reception in Jitsi Meet on Firefox 117.0 despite Adequate Bandwidth

### ISSUE THREAD

**Issue by bradkrane** [jitsi/jitsi-meet#13804]
### Description:

I am experiencing an issue where I cannot consistently receive video from other participants. While others can view everything without any problems, I rarely receive any video. My bitrate usage indicates that the download bitrate is approximately 84 kilobits per second, whereas the upload bitrate can be and often is much higher. This is puzzling, especially considering the minimal bitrate required for video & And that my bandwidth limits and speed tests during the sessions indicate I can send or receive far more bandwidth.

### Steps to reproduce:

1. Join a Jitsi Meet session with multiple participants.
2. Observe the video feed from other participants.
3. Note the inconsistency in receiving video, even after rejoining the session.

### Expected behavior:

I should be able to consistently view video from all participants without any interruptions.

### Actual behavior:

While others can view everything without any problems, I rarely receive any video. When I rejoin the session, I can briefly see everyone's video, but it cuts out after about three seconds.

### Server information:

- Jitsi Meet version: UNKN, when I'm connected as a client to the server how can I look this up? I looked everywhere in 
- Operating System: UNKN

### Client information:

- Browser / app version: Firefox 117.0 (64-bit)
- Operating System: OS Name:                   Microsoft Windows 10 Education
OS Version:                10.0.19045 N/A Build 19045

### Additional information:

I've conducted a network speed test with my ISP, and my connectivity is significantly higher than the bitrate being used for the video download. It's worth noting that other participants do not face this issue, I do.

There are no errors in the dev console When experiencing the issue.

### How can I help to resolve this?

I would appreciate any information on how I can help to come to a conclusion or resolve this issue.

**Comment by damencho** [comment]
Is this on meet.jit.si? 
Do you reproduce the issue with previous versions of Firefox? Do you reproduce the issue with chrome?

**Comment by janonym1** [comment]
I've encountered the same problems with a flaky video connection on an older jitsi version as well as the latest one. 
I think the bug is related to changes in the latest Firefox version (117, 64bit, Linux) as chromium seems to work fine for me. When I downgraded to FF 116.0, the video-connections returned to the expected normal behavior

**Comment by bradkrane** [comment]
I have seen this issue on previous versions of Firefox maybe the last six months of them. If that's the issue it's the worst it's ever been. I can't see that though as Firefox conforms to standards obviously and it should work regardless.

I've been connected to another server I'm not sure the version I will figure that out & post back!

**Comment by HappyFr1day** [comment]
I can reproduce this over my LAN with Jitsi 2.3-25-g1da507fa-1 and Firefox 117, both client and server running on Ubuntu Linux 22.04. Chromium works well. I will try and grab bridge logs later today.

**Comment by WilhelmRoscher** [comment]
I had the same issue on:

- Chrome Version 116.0.5845.140 (Offizieller Build) (arm64)
- Mac OS Ventura (13.5.1)
- Apple Silicon M1

With Chrome Version 117.0.5938.62 (Offizieller Build) (arm64) its seems to work normally again.

**Comment by spluess** [comment]
Has been happening for a while. Also see https://github.com/jitsi/jitsi-meet/issues/12578
Experiencing this with 117.0.1 on MacOS, Windows and Linux, regardless if connecting a local jitsi server or hosted ones or meet.jit.si . Other browsers work fine for us.

**Comment by jallamsetty1** [comment]
We are hoping that [this](https://github.com/jitsi/lib-jitsi-meet/commit/eab806a2f89d2e58c7c488528568d7ba488bb940) will fix the issue.

**Comment by jallamsetty1** [comment]
@bradkrane The above fix has been applied to meet.jit.si. Can you please give it a try and let us know if the issue is fixed for you on Firefox 117?

**Comment by javierckr** [comment]
Now we can see the green color of good bandwidth, but it seems that FF is not decoding vp9 as expected #10657, maybe we should open a new issue.
In these tests, there is a Chrome sending video, other chrome's see it in 720p but the firefox is blurry.
Firefox:
 
![image](https://github.com/jitsi/jitsi-meet/assets/42911254/a89bcb80-fb66-4599-b41e-73bf162524f2)

![image](https://github.com/jitsi/jitsi-meet/assets/42911254/b52f2d2f-f1ce-4391-8506-3572bc4e0f29)

Chrome:
![Captura desde 2023-09-21 16-50-09](https://github.com/jitsi/jitsi-meet/assets/42911254/3344f691-ad32-4eda-a467-80fdd754dbb0)

**Comment by saghul** [comment]
I believe it will be part of the next stable release. Or you could use the nightly / unstable releases.

**Comment by JOpsDev** [comment]
To get this fix I updated my test installation to the unstable nightly from yesterday and I am still seeing the problem of Firefox 118.0.2 dropping the video streams and JVB generating messages like "Sources suspended due to 
insufficient bandwidth (bwe=-1 bps)". Would the Jingle messages to/from the client be helpful here?

**Comment by mrossi88** [comment]
@jallamsetty1 I had the same problem with Firefox >= 117 and Jitsi Docker ver. stable-8319. I tried on meet.jit.si and it seems work. I guess the fix will be release in the next stable release. When do you plan to release? Thx

**Comment by jallamsetty1** [comment]
This fix hasn't been released to the stable yet. We hope to make a stable release by the end of this week or early next week and that should include the fix.

**Comment by jallamsetty1** [comment]
> To get this fix I updated my test installation to the unstable nightly from yesterday and I am still seeing the problem of Firefox 118.0.2 dropping the video streams and JVB generating messages like "Sources suspended due to insufficient bandwidth (bwe=-1 bps)". Would the Jingle messages to/from the client be helpful here?

Are only Firefox clients experiencing this issue? When you run into this issue, can you please execute the following on the browser console and check if that makes any difference?
`APP.conference._room.setReceiverConstraints({ 'assumedBandwidthBps': 2000000 });`

**Comment by bugfishtm** [comment]
No difference after executing this command, got same issue with own jitsi instance

**Comment by jallamsetty1** [comment]
> No difference after executing this command, got same issue with own jitsi instance

If this doesn't make any difference then probably there is a network issue in your instance. This command tells the bridge to ignore its BWE and assume the client has 2 Mbps downlink and send sources accordingly.

**Comment by otbutz** [comment]
> > To get this fix I updated my test installation to the unstable nightly from yesterday and I am still seeing the problem of Firefox 118.0.2 dropping the video streams and JVB generating messages like "Sources suspended due to insufficient bandwidth (bwe=-1 bps)". Would the Jingle messages to/from the client be helpful here?
> 
> Are only Firefox clients experiencing this issue? When you run into this issue, can you please execute the following on the browser console and check if that makes any difference? `APP.conference._room.setReceiverConstraints({ 'assumedBandwidthBps': 2000000 });`

That workaround seems to fix my issues :+1: 

Any ETA for the next Jitsi release?

**Comment by rmsouza** [comment]
Facing the same issue here with stable version 2.0.9111-1. No luck by executing `PP.conference._room.setReceiverConstraints({ 'assumedBandwidthBps': 2000000 });`.
Got the instance upgraded with much more network resources as well.
Connection status turns Poor on Firefox as soon as I turn video on.
I little bit random but usually after open 3 or 4 tabs the video is suspended.
BTW, I could not reproduce the same scenario on meet.jit.si.

**Comment by otbutz** [comment]
Which Firefox version? There is a known issue with SVC handling that has been fixed in Firefox 120.

see https://github.com/jitsi/jitsi-meet/issues/13933#issuecomment-1769251765

**Comment by rmsouza** [comment]
> Which Firefox version? There is a known issue with SVC handling that has been fixed in Firefox 120.
> 
> see [#13933 (comment)](https://github.com/jitsi/jitsi-meet/issues/13933#issuecomment-1769251765)

Firefox 120 (Ubuntu 22/04)

Still experiencing it in 2 different environments. Everything works well on meet.jit.si

Video from Firefox has been suspended for other participants, usually when the fourth participant gets in,  but its random.
Something like this also happens when switching from tile view to full screen or even when participants resize the page.
Looks like all the time resolution changes for some reason the application reacts and suspends the video, but only when the video comes from Firefox.

**Comment by damencho** [comment]
Are those environments updated to latest stable? That is the version meet.jit.si is running.

**Comment by JosefWN** [comment]
I just had this in a meeting running the latest release (9364) toward my own server, but not involving Firefox. Latest Chrome, Safari & Jitsi iOS app.

**Comment by jallamsetty1** [comment]
> I just had this in a meeting running the latest release (9364) toward my own server, but not involving Firefox. Latest Chrome, Safari & Jitsi iOS app.

Hi, did the videos recover at some point? Can you please share browser console logs from the user who did not see the any remote videos?

**Comment by JosefWN** [comment]
It recovered when one participant left. Don't have the logs but I will keep an eye out and get back with more information if it keeps occurring.

**Comment by TimSC** [comment]
I'm having problems on Firefox 137.0 with my self hosted server on AWS EC2 which is a t3-medium

Using the trust-bwe = false work around fixes it for me https://decafbad.net/2023/09/03/jitsi-and-firefox-fixing-a-recent-bug-with-the-bwe-bwe-1/

**Comment by jallamsetty1** [comment]
There was a bug in Firefox 137 https://bugzilla.mozilla.org/show_bug.cgi?id=1962792 because of which JVB was not able to learn the layer information correctly. It is fixed in FF 139 (beta)

**Comment by jallamsetty1** [comment]
@photoninger Are you able to confirm if this issue is resolved with latest stable using Ffirefox 139? thanks!

**Comment by photoninger** [comment]
@jallamsetty1 I did a little test with Firefox-139b08 and `cc.trust-bwe = true`: No more flapping videos and no `Sources suspended due to insufficient bandwidth` in jvb.log anymore. Looks like it is fixed with FF 139.

**Comment by jallamsetty1** [comment]
Thanks for confirming that the Firefox fix resolves this issue.
