### ISSUE TITLE
Too many open files, jvb becomes unavailable after some time

### ISSUE THREAD

**Issue by pedro-nonfree** [jitsi/jitsi-meet#1390]
My problem is that I can enter a room, but when arrives the new participant, we get the timeout of ~24 seconds error.

So I first started thinking it was prosody #1386 

that's why I tried

```
service prosody restart
service jitsi-videobridge restart
service jicofo restart
```
after that, we could meet

next attempt, reduce one restart

```
service jitsi-videobridge restart
service jicofo restart
```

it works too after this operation

```
service jicofo restart
```
same...

conclusion: there is a problem with jicofo: after some time, it looses something

this is the final of a meeting according to `/var/log/jitsi/jicofo.log`, and after that you can see `Health check failed`

Note: I masked private information as:

- *user1*: wherever appeared a nick (1 time)
- *meet.example.com*: custom domain for the service (several times)
- *myroom*: custom room inside jitsi (several times)

```
Jicofo 2017-03-09 17:42:00.567 INFO: [36] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Owner has left the room !
Jicofo 2017-03-09 17:42:00.567 INFO: [36] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member myroom@conference.meet.example.com/64891030 is leaving
Jicofo 2017-03-09 17:42:00.568 WARNING: [36] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Participant not found for myroom@conference.meet.example.com/64891030 terminated already or never started ?
Jicofo 2017-03-09 17:42:00.568 INFO: [36] org.jitsi.jicofo.FocusManager.log() Disposed conference for room: myroom@conference.meet.example.com conference count: 0
Jicofo 2017-03-09 21:38:10.053 WARNING: [15] org.jitsi.jicofo.JvbDoctor.log() Health check failed on: jitsi-videobridge.meet.example.com error: <error code="500" type="WAIT"><internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Failed to acquire DatagramSocket specific to STUN communication</text></error>
Jicofo 2017-03-09 21:38:10.053 INFO: [39] org.jitsi.jicofo.BridgeSelector.removeJvbAddress().192 Removing JVB: jitsi-videobridge.meet.example.com
Jicofo 2017-03-09 21:38:10.054 INFO: [39] org.jitsi.jicofo.JvbDoctor.log() Stopping health-check task for: jitsi-videobridge.meet.example.com
```

Here I put what happens next day when we try to join. It fails, until I restart `jicofo`

https://gist.github.com/pedro-nonfree/b4f46a1980e25ca45bc65599b32b001b

If you need other logs, tell me

Thanks

**Comment by damencho** [comment]
For more info:
http://lists.jitsi.org/pipermail/dev/2017-March/032083.html
and http://lists.jitsi.org/pipermail/dev/2017-March/032083.html

Can you try latest nightly, do you see the problem with it?

**Comment by pedro-nonfree** [comment]
Thanks @damencho 
I'm glad that you are aware of the issue!

You put the same link two times, would like to know what is the other one.

No, I don't have a development environment to try it (and to me is not feasible in short time), I just the stable application. I can try when it merges to stable and is available as update in debian repository.

**Comment by damencho** [comment]
To test the nightlies you just need to change the repo from stable to unstable and update or from stable to testing, this will also work. We took the packages from there when we push to stable.

**Comment by damencho** [comment]
The link is for another thread: http://lists.jitsi.org/pipermail/dev/2017-March/032083.html

**Comment by pedro-nonfree** [comment]
I tested with nightly of 2 days ago, and same error:

```
Jicofo 2017-03-14 15:28:27.088 WARNING: [50] org.jitsi.jicofo.JvbDoctor.log() Health check failed on: jitsi-videobridge.meet.guifi.net error: <error code="500" type="WAIT"><internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">java.net.SocketException: Too many open files (Error creating socket)</text></error>
Jicofo 2017-03-14 15:28:27.089 INFO: [39] org.jitsi.jicofo.BridgeSelector.removeJvbAddress().201 Removing JVB: jitsi-videobridge.meet.guifi.net
Jicofo 2017-03-14 15:28:27.089 INFO: [39] org.jitsi.jicofo.JvbDoctor.log() Stopping health-check task for: jitsi-videobridge.meet.guifi.net
```

Now I upgraded with nightly with the timestamp of this message

Let me know if you need more details like "version", but I don't know how to show it

**Comment by damencho** [comment]
You upgraded videobridge to nightly and saw this error?

**Comment by pedro-nonfree** [comment]
I upgraded again to nightly at 2017-03-15 13:00, let's see next time we use meet jitsi if it works without doing nothing or I have to restart jicofo again.

I upgraded videobridge to nightly this way

```
cat /etc/apt/sources.list.d/jitsi-stable.list 
#deb https://download.jitsi.org stable/
deb https://download.jitsi.org unstable/
```

**Comment by pedro-nonfree** [comment]
I could not try yet, but seems that if I do another meeting I should restart jicofo. Logs:

```
Jicofo 2017-03-15 19:06:59.383 INFO: [36] org.jitsi.jicofo.FocusManager.log() Disposed conference for room: myroom@conference.meet.example.com conference count: 0 
Jicofo 2017-03-15 23:15:39.186 WARNING: [52] org.jitsi.jicofo.JvbDoctor.log() Health check failed on: jitsi-videobridge.meet.guifi.net error: <error code="500" type="WAIT"><internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Too many open files (Socket creation failed)</text></error> 
Jicofo 2017-03-15 23:15:39.186 INFO: [39] org.jitsi.jicofo.BridgeSelector.removeJvbAddress().201 Removing JVB: jitsi-videobridge.meet.guifi.net 
Jicofo 2017-03-15 23:15:39.187 INFO: [39] org.jitsi.jicofo.JvbDoctor.log() Stopping health-check task for: jitsi-videobridge.meet.guifi.net 
```

**Comment by damencho** [comment]
This is a problem with jvb and is fixed in nightlies, we hope soon to update and stable.

**Comment by pepemedigu** [comment]
The same problem to me, I hope it will be solved soon. Thanks!

**Comment by damencho** [comment]
I believe it is already fixed.

**Comment by pedro-nonfree** [comment]
No, it's not fixed, here you have how I upgraded from unstable:

```
# apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  jitsi-meet jitsi-meet-prosody jitsi-meet-web jitsi-meet-web-config jitsi-videobridge
5 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 35.7 MB of archives.
After this operation, 244 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 https://download.jitsi.org/ unstable/ jitsi-meet 1.0.1902-1 [2,718 B]
Get:2 https://download.jitsi.org/ unstable/ jitsi-meet-web 1.0.1813-1 [5,302 kB]
Get:3 https://download.jitsi.org/ unstable/ jitsi-meet-web-config 1.0.1813-1 [9,436 B]
Get:4 https://download.jitsi.org/ unstable/ jitsi-meet-prosody 1.0.1813-1 [5,580 B]
Get:5 https://download.jitsi.org/ unstable/ jitsi-videobridge 921-1 [30.4 MB]
Fetched 35.7 MB in 8s (4,177 kB/s)
Reading changelogs... Done
Preconfiguring packages ...
(Reading database ... 42310 files and directories currently installed.)
Preparing to unpack .../jitsi-meet_1.0.1902-1_all.deb ...
Unpacking jitsi-meet (1.0.1902-1) over (1.0.1896-1) ...
Preparing to unpack .../jitsi-meet-web_1.0.1813-1_all.deb ...
Unpacking jitsi-meet-web (1.0.1813-1) over (1.0.1806-1) ...
Preparing to unpack .../jitsi-meet-web-config_1.0.1813-1_all.deb ...
Unpacking jitsi-meet-web-config (1.0.1813-1) over (1.0.1806-1) ...
Preparing to unpack .../jitsi-meet-prosody_1.0.1813-1_all.deb ...
Unpacking jitsi-meet-prosody (1.0.1813-1) over (1.0.1806-1) ...
Preparing to unpack .../jitsi-videobridge_921-1_amd64.deb ...
Unpacking jitsi-videobridge (921-1) over (920-1) ...
Processing triggers for systemd (215-17+deb8u6) ...
Setting up jitsi-videobridge (921-1) ...
Setting up jitsi-meet-web (1.0.1813-1) ...
Setting up jitsi-meet-web-config (1.0.1813-1) ...
----------------

You can now switch to a Let’s Encrypt certificate. To do so, execute:
/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh

----------------
Setting up jitsi-meet-prosody (1.0.1813-1) ...
Setting up jitsi-meet (1.0.1902-1) ...
```

A conference of yesterday, after 3 hours, that message that disconnect jitsi videobridge

```
Jicofo 2017-03-29 20:04:17.379 INFO: [36] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Owner has left the room !
Jicofo 2017-03-29 20:04:17.379 INFO: [36] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member dev@conference.meet.example.com/4c4c6713 is leaving
Jicofo 2017-03-29 20:04:17.379 WARNING: [36] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Participant not found for dev@conference.meet.example.com/4c4c6713 terminated already or never started ?
Jicofo 2017-03-29 20:04:17.381 INFO: [36] org.jitsi.jicofo.FocusManager.log() Disposed conference for room: dev@conference.meet.example.com conference count: 0
Jicofo 2017-03-30 00:12:19.530 WARNING: [41] org.jitsi.jicofo.JvbDoctor.log() Health check failed on: jitsi-videobridge.meet.example.com error: <error code="500" type="WAIT"><internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">java.net.SocketException: Too many open files (Error creating socket)</text></error>
Jicofo 2017-03-30 00:12:19.530 INFO: [39] org.jitsi.jicofo.BridgeSelector.removeJvbAddress().201 Removing JVB: jitsi-videobridge.meet.example.com
Jicofo 2017-03-30 00:12:19.530 INFO: [39] org.jitsi.jicofo.JvbDoctor.log() Stopping health-check task for: jitsi-videobridge.meet.example.com
```

**Comment by damencho** [comment]
Thanks for the report, we will take a look.

**Comment by damencho** [comment]
Hey @pedro-nonfree if it is possible to collect some logs next time you see "Too many open files".
In order to do that just run /usr/share/jitsi-videobridge/collect-dump-logs.sh as root and send me the result file privately.

**Comment by pedro-nonfree** [comment]
I think it's always the same error since I upgraded to unstable

FYI in the same debian I have a docker with rocketchat

I tried to run `/usr/share/jitsi-videobridge/collect-dump-logs.sh`:

```
# apt-get install openjdk-8-jdk openjdk-8-jre
 openjdk-8-jdk : Depends: openjdk-8-jdk-headless (= 8u121-b13-1~bpo8+1) but it is not going to be installed
 openjdk-8-jre : Depends: openjdk-8-jre-headless (= 8u121-b13-1~bpo8+1) but it is not going to be installed

# apt-get install openjdk-7-jdk openjdk-7-jre

# /usr/share/jitsi-videobridge/collect-dump-logs.sh
find: `/var/crash': No such file or directory
Jvb at pid 14608
lsof: status error on /tmp/java_pid14608.hprof: No such file or directory
lsof 4.86
 latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/
 latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ
 latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man
 usage: [-?abhKlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-f[gG]] [+|-e s]
 [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+m [m]] [+|-M] [-o [o]] [-p s]
[+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]
Use the ``-h'' option to get more help information.
Dumping heap to /tmp/heap-2017-03-31-0136-14608.bin ...
Heap dump file created
tar: Removing leading `/' from member names
/tmp/stack-2017-03-31-0136-14608.threads
/tmp/heap-2017-03-31-0136-14608.bin
tar: /tmp/java_pid14608.hprof: Cannot stat: No such file or directory
/var/log/jitsi/jvb.log
tar: /tmp/hs_err_*: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
# mkdir /var/crash
# /usr/share/jitsi-videobridge/collect-dump-logs.sh
Jvb at pid 14608
lsof: status error on /tmp/java_pid14608.hprof: No such file or directory
lsof 4.86
 latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/
 latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ
 latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man
 usage: [-?abhKlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-f[gG]] [+|-e s]
 [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+m [m]] [+|-M] [-o [o]] [-p s]
[+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]
Use the ``-h'' option to get more help information.
Dumping heap to /tmp/heap-2017-03-31-0137-14608.bin ...
Heap dump file created
tar: Removing leading `/' from member names
/tmp/stack-2017-03-31-0137-14608.threads
/tmp/heap-2017-03-31-0137-14608.bin
tar: /tmp/java_pid14608.hprof: Cannot stat: No such file or directory
/var/log/jitsi/jvb.log
tar: /tmp/hs_err_*: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```

**Comment by damencho** [comment]
What I need from the collect log is the archive that it produced.
There is nothing interesting in those logs other than the content of these two files:
/tmp/stack-2017-03-31-0136-14608.threads
/tmp/heap-2017-03-31-0136-14608.bin
Can you send it to me?

**Comment by pedro-nonfree** [comment]
Sorry! That's true. Despite the errors in the script generates a dump file with the content you want. I already sent it to your email.

**Comment by damencho** [comment]
Thanks, received. We will take a look. I see several thread dumps and heap dumps that will be useful, I hope something to popup from there. These are very useful logs.

**Comment by damencho** [comment]
@pedro-nonfree I have few questions, you are running jvb without modifications right? And also is the system loaded, I mean between you use it successfully and you spot the problem, are there any conferences made in between those two attempts?

**Comment by pedro-nonfree** [comment]
Very few modifications,

- `/etc/jitsi/meet/meet.guifi.net-config.js`: with `disableThirdPartyRequests: true,`
- parameters to allow chrome extension share screen

yes, I'm using it right now for a meeting, it works after doing `service jicofo restart`. Between these dumps, there are conferences made (that can last 1 hour or 2). Perhaps 3 on a week (as you see very low usage, compared to meet.jit.si). The problem is that after hours of these conferences, the doctor checker stops jvb (previous logs)

**Comment by damencho** [comment]
Yep, I see, I was checking about code modifications. 
In the heapdumps you sent me I see a lot of FileDescriptors prepared for finalization, not sure whether this is the root of the problem, cause they should already been closed.
But I've been debugging yesterday and I see all the sockets are being closed as they should. And If I see a lot of objects prepared for finalization and if I force the garbage collector they are cleaned. So I had a suspicion that your jvb is not heavily used so the jvm is not stressed and so garbage collector is not started for some time, which causes a lot of objects prepared for finalization for the next time the garbage collector to clean them. I'm not certain of that scenario at all, it is just a guess.
What java version are you using is it 8? 

Another thing you can try, is enabling pubsub for jvb. Normally it is used when you have more than one jvb for balancing, but with one it also helps when restarting jicofo to find the new instance, we will soon switch the default configuration to have this by default:
Add this to jvb's sip-communicator.properties file:
org.jitsi.videobridge.PUBSUB_SERVICE=your.service.com
org.jitsi.videobridge.PUBSUB_NODE=jvb
Add this to jicofo's sip-communicator.properties file:
org.jitsi.focus.pubsub.ADDRESS=your.service.com
org.jitsi.jicofo.STATS_PUBSUB_NODE=jvb
And then restart both.

The pubsub will do some jvm work :) If that doesn't help its worth trying to force the garbage collector once a day or something like that:
PID=$(cat /var/run/jitsi-videobridge.pid)
sudo -u jvb jcmd $PID GC.run

**Comment by damencho** [comment]
I see you are running java8. I still some suspicious stuff in the heapdump that I want to discuss with a colleague, but he is currently on vacation. Will come back later when there is more info on the subject.

**Comment by damencho** [comment]
Hey @pedro-nonfree could you please test build 928 of jvb and report how it is behaving. We believe the problem is fixed ther. Thanks to @bgrozev :)

**Comment by pedro-nonfree** [comment]
Sorry the late response, but is still failing. Tell me if I can help:

on 2017-04-11 I did the upgrade
```
[10:54:46] root@hostname:~# apt-get upgrade
Setting up jitsi-meet-prosody (1.0.1882-1) ...
Setting up jitsi-meet (1.0.1981-1) ...
Setting up docker-engine (17.04.0~ce-0~debian-jessie) ...
Installing new version of config file /etc/bash_completion.d/docker ...
Installing new version of config file /etc/init.d/docker ...
Setting up eject (2.1.5+deb1+cvs20081104-13.1+deb8u1) ...
Processing triggers for libc-bin (2.19-18+deb8u7) ...
Processing triggers for systemd (215-17+deb8u6) ...
```

```
Jicofo 2017-04-11 20:38:50.572 INFO: [36] org.jitsi.jicofo.FocusManager.log() Disposed conference for room: exoeticom@conference.meet.guifi.net conference count: 0
Jicofo 2017-04-11 23:24:12.476 WARNING: [15] org.jitsi.jicofo.JvbDoctor.log() Health check failed on: jitsi-videobridge.meet.guifi.net error: <error code="500" type="WAIT"><internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">java.net.SocketException: Too many open files (Error creating socket)</text></error>
Jicofo 2017-04-11 23:24:12.476 INFO: [39] org.jitsi.jicofo.BridgeSelector.removeJvbAddress().201 Removing JVB: jitsi-videobridge.meet.guifi.net
Jicofo 2017-04-11 23:24:12.477 INFO: [39] org.jitsi.jicofo.JvbDoctor.log() Stopping health-check task for: jitsi-videobridge.meet.guifi.net
```

**Comment by damencho** [comment]
@pedro-nonfree Could you again send me heapdump and logs when it happens, so we can hunt it further, thank you for your cooperation.

**Comment by bgrozev** [comment]
@pedro-nonfree We're really scratching our heads with this one. Our tests show that we don't leave any sockets not closed, and we can't reproduce the problem unless we leave sockets not closed. We suspect that something in your environment contributes to the problem. Would you be able to compile and run the following java program on the same machine that you see the problem with the bridge?

```
import java.util.*;
import java.net.*;


public class Test
{
  public static void main(String[] argv)
  throws Exception
  {
    for (int j =0; j<10; j++)
    for ( int i = 20000 ; i < 60000; i++)
    {
        try{
        //System.err.println("i="+i);
        DatagramSocket s = new DatagramSocket(i);
        s.close();
        } catch (BindException be){
            System.err.println("bind error (port="+i+"), a few of these are normal");
        }
    }

    System.err.println("all good, did not run out of FDs");
  }
}
```

You can do this with "javac Test.java && java Test". It should run for a few seconds and print "all good".

**Comment by pedro-nonfree** [comment]
Results of the test:
```
# javac Test.java && java Test
bind error (port=23951), a few of these are normal
bind error (port=28222), a few of these are normal
bind error (port=36046), a few of these are normal
bind error (port=36213), a few of these are normal
bind error (port=37512), a few of these are normal
bind error (port=42817), a few of these are normal
bind error (port=43650), a few of these are normal
bind error (port=45292), a few of these are normal
bind error (port=46390), a few of these are normal
bind error (port=48123), a few of these are normal
bind error (port=50956), a few of these are normal
bind error (port=54437), a few of these are normal
bind error (port=56726), a few of these are normal
bind error (port=58202), a few of these are normal
bind error (port=58884), a few of these are normal
bind error (port=23951), a few of these are normal
bind error (port=28222), a few of these are normal
bind error (port=36046), a few of these are normal
bind error (port=36213), a few of these are normal
bind error (port=37512), a few of these are normal
bind error (port=42817), a few of these are normal
bind error (port=43650), a few of these are normal
bind error (port=45292), a few of these are normal
bind error (port=46390), a few of these are normal
bind error (port=48123), a few of these are normal
bind error (port=50956), a few of these are normal
bind error (port=54437), a few of these are normal
bind error (port=56726), a few of these are normal
bind error (port=58202), a few of these are normal
bind error (port=58884), a few of these are normal
bind error (port=23951), a few of these are normal
bind error (port=28222), a few of these are normal
bind error (port=36046), a few of these are normal
bind error (port=36213), a few of these are normal
bind error (port=37512), a few of these are normal
bind error (port=42817), a few of these are normal
bind error (port=43650), a few of these are normal
bind error (port=45292), a few of these are normal
bind error (port=46390), a few of these are normal
bind error (port=48123), a few of these are normal
bind error (port=50956), a few of these are normal
bind error (port=54437), a few of these are normal
bind error (port=56726), a few of these are normal
bind error (port=58202), a few of these are normal
bind error (port=58884), a few of these are normal
bind error (port=23951), a few of these are normal
bind error (port=28222), a few of these are normal
bind error (port=36046), a few of these are normal
bind error (port=36213), a few of these are normal
bind error (port=37512), a few of these are normal
bind error (port=42817), a few of these are normal
bind error (port=43650), a few of these are normal
bind error (port=45292), a few of these are normal
bind error (port=46390), a few of these are normal
bind error (port=48123), a few of these are normal
bind error (port=50956), a few of these are normal
bind error (port=54437), a few of these are normal
bind error (port=56726), a few of these are normal
bind error (port=58202), a few of these are normal
bind error (port=58884), a few of these are normal
bind error (port=23951), a few of these are normal
bind error (port=28222), a few of these are normal
bind error (port=36046), a few of these are normal
bind error (port=36213), a few of these are normal
bind error (port=37512), a few of these are normal
bind error (port=42817), a few of these are normal
bind error (port=43650), a few of these are normal
bind error (port=45292), a few of these are normal
bind error (port=46390), a few of these are normal
bind error (port=48123), a few of these are normal
bind error (port=50956), a few of these are normal
bind error (port=54437), a few of these are normal
bind error (port=56726), a few of these are normal
bind error (port=58202), a few of these are normal
bind error (port=58884), a few of these are normal
bind error (port=23951), a few of these are normal
bind error (port=28222), a few of these are normal
bind error (port=36046), a few of these are normal
bind error (port=36213), a few of these are normal
bind error (port=37512), a few of these are normal
bind error (port=42817), a few of these are normal
bind error (port=43650), a few of these are normal
bind error (port=45292), a few of these are normal
bind error (port=46390), a few of these are normal
bind error (port=48123), a few of these are normal
bind error (port=50956), a few of these are normal
bind error (port=54437), a few of these are normal
bind error (port=56726), a few of these are normal
bind error (port=58202), a few of these are normal
bind error (port=58884), a few of these are normal
bind error (port=23951), a few of these are normal
bind error (port=28222), a few of these are normal
bind error (port=36046), a few of these are normal
bind error (port=36213), a few of these are normal
bind error (port=37512), a few of these are normal
bind error (port=42817), a few of these are normal
bind error (port=43650), a few of these are normal
bind error (port=45292), a few of these are normal
bind error (port=46390), a few of these are normal
bind error (port=48123), a few of these are normal
bind error (port=50956), a few of these are normal
bind error (port=54437), a few of these are normal
bind error (port=56726), a few of these are normal
bind error (port=58202), a few of these are normal
bind error (port=58884), a few of these are normal
bind error (port=23951), a few of these are normal
bind error (port=28222), a few of these are normal
bind error (port=36046), a few of these are normal
bind error (port=36213), a few of these are normal
bind error (port=37512), a few of these are normal
bind error (port=42817), a few of these are normal
bind error (port=43650), a few of these are normal
bind error (port=45292), a few of these are normal
bind error (port=46390), a few of these are normal
bind error (port=48123), a few of these are normal
bind error (port=50956), a few of these are normal
bind error (port=54437), a few of these are normal
bind error (port=56726), a few of these are normal
bind error (port=58202), a few of these are normal
bind error (port=58884), a few of these are normal
bind error (port=23951), a few of these are normal
bind error (port=28222), a few of these are normal
bind error (port=36046), a few of these are normal
bind error (port=36213), a few of these are normal
bind error (port=37512), a few of these are normal
bind error (port=42817), a few of these are normal
bind error (port=43650), a few of these are normal
bind error (port=45292), a few of these are normal
bind error (port=46390), a few of these are normal
bind error (port=48123), a few of these are normal
bind error (port=50956), a few of these are normal
bind error (port=54437), a few of these are normal
bind error (port=56726), a few of these are normal
bind error (port=58202), a few of these are normal
bind error (port=58884), a few of these are normal
bind error (port=23951), a few of these are normal
bind error (port=28222), a few of these are normal
bind error (port=36046), a few of these are normal
bind error (port=36213), a few of these are normal
bind error (port=37512), a few of these are normal
bind error (port=42817), a few of these are normal
bind error (port=43650), a few of these are normal
bind error (port=45292), a few of these are normal
bind error (port=46390), a few of these are normal
bind error (port=48123), a few of these are normal
bind error (port=50956), a few of these are normal
bind error (port=54437), a few of these are normal
bind error (port=56726), a few of these are normal
bind error (port=58202), a few of these are normal
bind error (port=58884), a few of these are normal
all good, did not run out of FDs
```

This machine runs:

- nginx reverse proxy for rocketchat and jitsi meet
- rocket chat uses mongodb

```
docker run --name db -d mongo --smallfiles

docker run --restart=always --name rocketchat -p 3000:3000 --env ROOT_URL=https://xat.guifi.net --link db -d rocket.chat
```

It's strange, because is somehow isolated, but your conclusions for me it's like rocketchat with jitsi meet are not fine together. I don't know, perhaps this happens with more software...?

**Comment by jpsutton** [comment]
I'm experiencing the same issue.  Stable Jitsi Meet installation on Ubuntu 16.04 using the quick install method.  I can provide logs if it would help.

**Comment by pedro-nonfree** [comment]
Now we have another server to test (total: 2). The new one is a debian with jitsi everything with default configuration. Debian has the following firewall [1]. In jitsi stable the same problem (probably, you did not applied yet), but after that I applied unstable [2] and we have the same problem, but now I think the logs find something more interesting (java.lang.NullPointerException) [3]

I will give you result of privately

[1] /etc/firewall
```
*nat
COMMIT
*filter
:INPUT ACCEPT
:FORWARD ACCEPT
:OUTPUT ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT ! -i eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT -m comment --comment "apply to different than eth0"
-A INPUT -i lo -j ACCEPT
-A INPUT -i eth0 -j ACCEPT
-A INPUT -i eth1 -p tcp -m multiport --dports 80,443 -j ACCEPT -m comment --comment "HTTP/HTTPS intranet"
-A INPUT -i eth2 -p tcp -m multiport --dports 80,443 -j ACCEPT -m comment --comment "HTTP/HTTPS internet"
-A INPUT -i eth1 -p udp -m multiport --dports 10000 -j ACCEPT -m comment --comment "Jitsi UDP intranet"
-A INPUT -i eth2 -p udp -m multiport --dports 10000 -j ACCEPT -m comment --comment "Jitsi UDP internet"
-A INPUT -j DROP
COMMIT
*mangle
COMMIT
```

[2]
```
root@rt:~# apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  jicofo jitsi-meet jitsi-meet-prosody jitsi-meet-web jitsi-meet-web-config jitsi-videobridge
6 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 62.7 MB of archives.
After this operation, 973 kB disk space will be freed.
Do you want to continue? [Y/n] 
Get:1 https://download.jitsi.org/ unstable/ jitsi-meet 1.0.2037-1 [2,724 B]
Get:2 https://download.jitsi.org/ unstable/ jicofo 1.0-348-1 [26.2 MB]
Get:3 https://download.jitsi.org/ unstable/ jitsi-meet-web 1.0.1924-1 [5,863 kB]
Get:4 https://download.jitsi.org/ unstable/ jitsi-meet-web-config 1.0.1924-1 [9,406 B]
Get:5 https://download.jitsi.org/ unstable/ jitsi-meet-prosody 1.0.1924-1 [5,600 B]
Get:6 https://download.jitsi.org/ unstable/ jitsi-videobridge 938-1 [30.7 MB]
Fetched 62.7 MB in 3s (17.5 MB/s)             
Reading changelogs... Done
Preconfiguring packages ...
(Reading database ... 34290 files and directories currently installed.)
Preparing to unpack .../jitsi-meet_1.0.2037-1_all.deb ...
Unpacking jitsi-meet (1.0.2037-1) over (1.0.1622-1) ...
Preparing to unpack .../jicofo_1.0-348-1_amd64.deb ...
Unpacking jicofo (1.0-348-1) over (1.0-320-1) ...
Preparing to unpack .../jitsi-meet-web_1.0.1924-1_all.deb ...
Unpacking jitsi-meet-web (1.0.1924-1) over (1.0.1592-1) ...
Preparing to unpack .../jitsi-meet-web-config_1.0.1924-1_all.deb ...
Unpacking jitsi-meet-web-config (1.0.1924-1) over (1.0.1592-1) ...
Preparing to unpack .../jitsi-meet-prosody_1.0.1924-1_all.deb ...
Unpacking jitsi-meet-prosody (1.0.1924-1) over (1.0.1592-1) ...
Preparing to unpack .../jitsi-videobridge_938-1_amd64.deb ...
Unpacking jitsi-videobridge (938-1) over (879-1) ...
Processing triggers for systemd (215-17+deb8u6) ...
Setting up jitsi-videobridge (938-1) ...
Installing new version of config file /etc/jitsi/videobridge/logging.properties ...
 * Applying /etc/sysctl.d/20-jvb-udp-buffers.conf ...
net.core.rmem_max = 10485760
net.core.netdev_max_backlog = 100000
 * Applying /etc/sysctl.d/99-sysctl.conf ...
 * Applying /etc/sysctl.conf ...
Setting up jicofo (1.0-348-1) ...
Installing new version of config file /etc/init.d/jicofo ...
Setting up jitsi-meet-web (1.0.1924-1) ...
Setting up jitsi-meet-web-config (1.0.1924-1) ...
----------------

You can now switch to a Let’s Encrypt certificate. To do so, execute:
/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh

----------------
Setting up jitsi-meet-prosody (1.0.1924-1) ...
Setting up jitsi-meet (1.0.2037-1) ...
Processing triggers for systemd (215-17+deb8u6) ...
```

[3]

```
JVB 2017-04-28 21:47:35.977 FINE: [25] org.jitsi.videobridge.xmpp.ComponentImpl.log() RECV: <iq type="get" to="jitsi-videobridge.meet.example.com" from="focus@auth.meet.example.com/focus10
9701329789694" id="dDmX2-5740"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"/></iq>
JVB 2017-04-28 21:47:35.977 INFO: [25] org.jitsi.videobridge.Videobridge.log() CAT=stat create_conf,conf_id=3e610986969650d9 conf_name=null,logging=false,conf_count=1,ch_count=0,v_
streams=0
JVB 2017-04-28 21:47:35.985 INFO: [25] org.jitsi.impl.neomedia.VideoMediaStreamImpl.log() Creating a BandwidthEstimator for stream org.jitsi.impl.neomedia.VideoMediaStreamImpl@28a5
93c3
JVB 2017-04-28 21:47:35.986 INFO: [25] org.jitsi.videobridge.cc.BitrateController.log() bitrate_ctrl,stream=681939907 target_bps=0,bwe_bps=9223372036854775807
JVB 2017-04-28 21:47:35.986 INFO: [110339] org.jitsi.videobridge.cc.BitrateController.log() bitrate_ctrl,stream=681939907 target_bps=0,bwe_bps=9223372036854775807
JVB 2017-04-28 21:47:35.993 WARNING: [25] org.jitsi.videobridge.Channel.log() Failed to close the MediaStream/stream of channel dc06a6953259b024 of content video of conference 3e61
0986969650d9!
java.lang.NullPointerException
        at org.jitsi.videobridge.RtpChannel.closeStream(RtpChannel.java:647)
        at org.jitsi.videobridge.Channel.expire(Channel.java:383)
        at org.jitsi.videobridge.RtpChannel.expire(RtpChannel.java:1723)
        at org.jitsi.videobridge.VideoChannel.expire(VideoChannel.java:453)
        at org.jitsi.videobridge.Content.expire(Content.java:394)
        at org.jitsi.videobridge.Conference.expire(Conference.java:690)
        at org.jitsi.videobridge.health.Health.check(Health.java:168)
        at org.jitsi.videobridge.Videobridge.handleHealthCheckIQ(Videobridge.java:1129)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQRequest(ComponentImpl.java:435)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQ(ComponentImpl.java:345)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQ(ComponentImpl.java:297)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQGetImpl(ComponentImpl.java:396)
        at org.jitsi.xmpp.component.ComponentBase.handleIQGet(ComponentBase.java:315)
        at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:511)
        at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:289)
        at org.xmpp.component.AbstractComponent.processQueuedPacket(AbstractComponent.java:239)
        at org.xmpp.component.AbstractComponent.access$100(AbstractComponent.java:81)
        at org.xmpp.component.AbstractComponent$PacketProcessor.run(AbstractComponent.java:1051)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
JVB 2017-04-28 21:47:35.995 FINE: [25] org.jitsi.videobridge.xmpp.ComponentImpl.log() SENT: <iq id="dDmX2-5740" to="focus@auth.meet.example.com/focus109701329789694" from="jitsi-videobridge.meet.example.com" type="error"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"></healthcheck><error code="500" type="WAIT"><internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"></internal-server-error><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" xml:lang="en">Too many open files (Socket creation failed)</text></error></iq>
JVB 2017-04-28 21:47:35.995 FINE: [25] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Responding to IQ (packetId dDmX2-5740) with: <iq id="dDmX2-5740" to="focus@auth.meet.example.com/focus109701329789694" from="jitsi-videobridge.meet.example.com" type="error"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"></healthcheck><error code="500" type="WAIT"><internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"></internal-server-error><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" xml:lang="en">Too many open files (Socket creation failed)</text></error></iq>
JVB 2017-04-28 21:47:36.066 FINE: [23] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId dDmX2-5743): <iq type="get" to="jitsi-videobridge.meet.example.com" from="focus@auth.meet.example.com/focus109701329789694" id="dDmX2-5743"><query xmlns="http://jabber.org/protocol/disco#info"/></iq>
JVB 2017-04-28 21:47:36.066 FINE: [23] org.jitsi.videobridge.xmpp.ComponentImpl.processIQRequest() (serving component 'JitsiVideobridge') Processing IQ request (packetId dDmX2-5743).
```

**Comment by jpsutton** [comment]
Is there a reason why jvb has so many udp6 listener sockets open and changes constantly?  The number is fluctuating for me in the 300-400 range right now every few seconds.  I suspect this number is slowly creeping up and eventually runs out of file handles.  I'm writing a shell script to monitor it and record the change over time.

**Comment by damencho** [comment]
The versions after stable already got few fixes for that problem, so it
would help testing the latest nightlies and report how are they behaving.
We are unable to figure out currently why @pedro-nonfree is hitting that
problem.

**Comment by jpsutton** [comment]
I'm now running 932 from the testing repo.  I'm running my script to record the file handle usage over time and I'll report back in a few hours.

**Comment by jpsutton** [comment]
As it turns out, I didn't need to wait a few hours.  Here's an idea of how the handles are changing in a 30 minute time span...  http://imgur.com/m8uC6TM

I'll try moving to nightly builds and re-test.

**Comment by jpsutton** [comment]
Running the most recent nightly (938), I sampled the number of file handles for jvb every 6 seconds over 2 hours.  The following chart shows the file handle count over that time period. There were likely no sessions happneing on my installation in that time window...

http://imgur.com/a/zQakK

JVB did not restart during that time frame.

**Comment by damencho** [comment]
There are healthchecks running, so creating sockets is normal ... These observations are intetesting...we will take a look on Monday.

**Comment by bgrozev** [comment]
@jpsutton Thanks for the additional data. This is consistent with what we see. There is a substantial amount of sockets (and thus FDs) opened for health-checks, but they are all closed and released at some point. We never managed to reproduce the problem with hitting the limit (an getting a "too many open files" error).

**Comment by bgrozev** [comment]
> Results of the test:

This looks good. Was it run in the same environment in which the jitsi-videobridge jvm runs (inside docker)?

**Comment by bgrozev** [comment]
> JVB 2017-04-28 21:47:35.993 WARNING: [25] org.jitsi.videobridge.Channel.log() Failed to close the MediaStream/stream of channel dc06a6953259b024 of content video of conference 3e61 0986969650d9! java.lang.NullPointerException

I don't see how this could be related to the problem here.

**Comment by pedro-nonfree** [comment]
@jpsutton I recommend if you share that code to see if is reproducible in other servers.

On a comment [above](https://github.com/jitsi/jitsi-meet/issues/1390#issuecomment-298231664) I explained how I could reproduce the same problem in a different machine `server2` that is running in a different place; public IPv4, no other software running on it. I'm still dedicating this resource hopefully to solve the problem and facilitate the workaround of this issue. I'm waiting instructions if you have ideas @damencho @bgrozev

Theoretically "lot of people" (all of them that are installing vanilla jitsi meet in debian jessie 8.x with [quick instructions](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md)) is experimenting this problem. If not, these people should come here to say how to avoid it; because as I said, I have to do before each meet `service jicofo restart`.

As a possible way to fix it, I think it could be interesting to stop the "doctor" that checks if everything is running. -> Ok, I found it, I will apply that in `server1` and after some days I will say if is fine:
`You can disable health checks from jicofo by adding this to /etc/jitsi/jicofo/sip-communicator.properties
org.jitsi.jicofo.HEALTH_CHECK_INTERVAL=-1`

https://github.com/jitsi/jitsi-meet/issues/664
https://github.com/jitsi/jitsi-videobridge/issues/245
https://github.com/jitsi/jitsi-meet/issues/798
https://github.com/jitsi/jicofo/issues/167

I think this problem is wasting too much tickets (ok, seems a big issue, and already have fix part of it). I suggest, at least, to explain that this is a **known issue**, and that if you are experimenting it, disable health checks". 

Again, If you want to push solving this issue; I'm in.

**Comment by bgrozev** [comment]
@pedro-nonfree the issues that you reference have all been fixed. I'm not aware of anyone else running into this problem with the current master branch, and we haven't been able to reproduce it so far (we're still trying).

**Comment by damencho** [comment]
Hey @pedro-nonfree we managed to reproduce it. The problem comes from the ipv6 addresses you have configured. 
If you can sacrifice the ipv6 use in jvb you can disable it using:
org.ice4j.ipv6.DISABLED=true
And this will fix the problem.
We will be further investigating it.

**Comment by pedro-nonfree** [comment]
@damencho great; I will try it

Can you point me to the specific configuration file to put this option? `/etc/jitsi/wat?`, I don't find a source that explain it. I think it should be explained here too:

https://github.com/jitsi/ice4j/blob/master/doc/configuration.md#orgice4jipv6disabled

**Comment by bgrozev** [comment]
/etc/jitsi/videobridge/sip-communicator.properties

**Comment by damencho** [comment]
@pedro-nonfree build 949 of videobridge contains the fix. So if you want to give it a try, leaving jicofo health checks and return ipv6 (do not disable it) and see will you hit the problem again?
Thanks for the help and cooperation for digging this till the end. Thanks for the dumps, without them we would miss this problem.

**Comment by pedro-nonfree** [comment]
@damencho @bgrozev I have had like 10 meetings in these days, works perfectly. Thank you guys!

**Comment by damencho** [comment]
Stable was updated a few hours ago :) 
Cheers 🍺

**Comment by Ark74** [comment]
Was `org.ice4j.ipv6.DISABLED=true`  supposed to be by default on `/etc/jitsi/videobridge/sip-communicator.properties` on stable?
It wasn't, so I add it.

This issue is still present on,
jitse-meet 1011-1 - (debian based packages)
[ jitsi-videobridge (= 1011-1), jicofo (= 1.0-388-1), jitsi-meet-web (= 1.0.2441-1), jitsi-meet-web-config (= 1.0.2441-1), jitsi-meet-prosody (= 1.0.2441-1) ]

Restarting jicofo fix it, I'll report any change in a couple of days now with ipv6 disabled.
Thanks.

**Comment by Ark74** [comment]
Well first happy new year everyone!
Since I manually added `org.ice4j.ipv6.DISABLED=true` to `sip-communicator.properties` the calls seem to be consistent after weeks of the last jicofo restart.

I'll keep monitoring, but this seems to have solve my issue. 
Cheers!

**Comment by ruojianll** [comment]
@Ark74 I will try your solution. There was something wrong occurred during a public show. I just restart the jvb process and I know it will shutdown recently.

**Comment by murat-aksoy** [comment]
> Well first happy new year everyone!
> Since I manually added `org.ice4j.ipv6.DISABLED=true` to `sip-communicator.properties` the calls seem to be consistent after weeks of the last jicofo restart.
> 
> I'll keep monitoring, but this seems to have solved my issue.
> Cheers!

This one solved my problem but if there is a common issue like this, why it's not documented at somewhere?
