### ISSUE TITLE
android app menu buttons missing

### ISSUE THREAD

**Issue by petervnv** [jitsi/jitsi-meet#1557]
Hi,

As discussed in the mailing list, the android version of jitsi meet (just installed from Play store) is buggy.
On my Galaxy Tab A (2016) SM-T580 running stock 6.0.1 the menu buttons don't show up after joining a room.

Touching the screen repeatedly merely toggles the filmstrip.

**Comment by petervnv** [comment]
Just tested on an S6 edge (SM-G925F) running Samsung's stock 7.0 and menu buttons work as expected

**Comment by saghul** [comment]
We are not sure what causing this exactly. I used to get it on a Pixel device, and applied to workarounds to mitigate it, then it resurfaced and we fixed it again. On a Moto X Play device, however, I'm still able to see it, also on Android 7.0.

My hypothesis here is something related to the EGL version, maybe.

Thanks for the report!

**Comment by petervnv** [comment]
No problem. The S6 (where it seems to work fine) is running EGL 1.4

D/libEGL  (22221): loaded /vendor/lib64/egl/libGLES_mali.so
I/OpenGLRenderer(22221): Initialized EGL, version 1.4
D/OpenGLRenderer(22221): Swap behavior 1

I'm going to try and determine the EGL on the Galaxy

**Comment by petervnv** [comment]
Still not sure how to find out the EGL version running on the Galaxy Tab A (2016) SM-T580 since it's not rooted.

Anyway, I just tested the app on a brand new S8 (samsung/SM-G950F/exynos5) running Android 7 and it worked fine, just like the S6 running Android 7.

There seems to be a common denominator so far that the only working devices are running Android 7.
Has anyone running <7 gotten the menu buttons to work properly?

Cheers

**Comment by lyubomir** [comment]
My testing device is Samsung S4 running Android 4.4.4 and there're no problems with the (toolbox) buttons.

**Comment by saghul** [comment]
This was finally fixed, the next version (1.8) will contain the fix.
