### ISSUE TITLE
jitsimeetSDK crashes in iOS 26

### ISSUE THREAD

**Issue by vineethnkforios** [jitsi/jitsi-meet#16514]
### What happened?

App crashes when running on ios 26 - iPhone 17 Pro Max Simulators

Seems a bug in the JitsiMeetSDK, specifically in its handling of media device enumeration on iOS 26.

My findings:

Crash Summary
Exception
*** Terminating app due to uncaught exception 'NSInvalidArgumentException'
Reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'

 Crashing Function (From Stack Trace)
JitsiMeetSDK: -[WebRTCModule(RTCMediaStream) enumerateDevices:] + 1152

 What’s Happening?

The SDK is attempting to create an NSDictionary with device info inside the method:

-[WebRTCModule(RTCMediaStream) enumerateDevices:]

But one of the device values is nil, most likely due to iOS 26 changing how media devices are enumerated or named. This is common when:

A device has no label, deviceId, or groupId

The new iOS SDK returns nil for some AVCaptureDevice properties that used to be non-optional

This would cause:

NSDictionary *device = @{
  @"deviceId": nil, // <- BOOM 💥
  @"label": @"Back Camera",
  ...
};

crash report : Exception	NSException *	"*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]"	0x0000600000d18ff0
name	__NSCFConstantString *	"NSInvalidArgumentException"	0x00000001e5ca85e8

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [x] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

11.5.1

### Relevant log output

```shell
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001804f39e8 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000018009c084 objc_exception_throw + 72
	2   CoreFoundation                      0x000000018055de74 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 656
	3   CoreFoundation                      0x00000001804f2298 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 48
	4   JitsiMeetSDK                        0x000000010761ee10 -[WebRTCModule(RTCMediaStream) enumerateDevices:] + 1152
	5   CoreFoundation                      0x00000001804fa3b0 __invoking___ + 144
	6   CoreFoundation                      0x00000001804f755c -[NSInvocation invoke] + 276
	7   CoreFoundation                      0x00000001804f77e0 -[NSInvocation invokeWithTarget:] + 60
	8   JitsiMeetSDK                        0x000000010733c35c -[RCTModuleMethod invokeWithBridge:module:arguments:] + 380
	9   JitsiMeetSDK                        0x000000010733e510 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicEiN12_GLOBAL__N_117SchedulingContextE + 452
	10  JitsiMeetSDK                        0x000000010733e164 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 116
	11  libdispatch.dylib                   0x0000000102c1bfb8 _dispatch_call_block_and_release + 24
	12  libdispatch.dylib                   0x0000000102c359dc _dispatch_client_callout + 12
	13  libdispatch.dylib                   0x0000000102c24494 _dispatch_lane_serial_drain + 888
	14  libdispatch.dylib                   0x0000000102c250f8 _dispatch_lane_invoke + 428
	15  libdispatch.dylib                   0x0000000102c31294 _dispatch_root_queue_drain_deferred_wlh + 324
	16  libdispatch.dylib                   0x0000000102c307f0 _dispatch_workloop_worker_thread + 752
	17  libsystem_pthread.dylib             0x0000000102cbab8c _pthread_wqthread + 288
	18  libsystem_pthread.dylib             0x0000000102cb998c start_wqthread + 8
)
[modules/xmpp/moderator] Using xmpp for conference requests.
libc++abi: terminating due to uncaught exception of type NSException
[modules/xmpp/xmpp] P2P STUN servers:  [ { urls: 'stun:meet-jit-si-turnrelay.jitsi.net:443' } ]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
terminating due to uncaught exception of type NSException
CoreSimulator 1048 - Device: iPhone 17 Pro Max (2C7AF110-08A0-43D7-B5EE-812C2297D333) - Runtime: iOS 26.0 (23A343) - DeviceType: iPhone 17 Pro Max
```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

jitsimeet version: https://github.com/jitsi/jitsi-meet-ios-sdk-releases/releases/tag/11.5.1
iOS Native project

**Comment by sushibuapps** [comment]
I am also facing the same issue on iOS 26 and iPhone 17 Pro. The app crashes before entering the conference room.
Can we hopefully expect a hotfix for this?

**Comment by saghul** [comment]
Do you see this is in a physical device or just the simulator?

**Comment by saghul** [comment]
> But one of the device values is nil, most likely due to iOS 26 changing how media devices are enumerated or named. This is common when:
> 
> A device has no label, deviceId, or groupId
> 
> The new iOS SDK returns nil for some AVCaptureDevice properties that used to be non-optional

Did you find any documentation about this?Can you dump a AVCaptureDevice which has its uniqueID as nil?

**Comment by vineethnkforios** [comment]
> Do you see this is in a physical device or just the simulator?

Actually, I tested it only in a simulator.

**Comment by saghul** [comment]
It seems to be only a problem in the simulator.

**Comment by vineethnkforios** [comment]
> It seems to be only a problem in the simulator.

O...Thanks... will check and update you asap

**Comment by vineethnkforios** [comment]
> It seems to be only a problem in the simulator.

Yes, I have tested it on my real device running iOS 26, and it seems to be working fine. Thanks for your support

**Comment by saghul** [comment]
This is now fixed in the latest release.

**Comment by KolissnikBogdan** [comment]
@saghul Hello, I am still experiencing this issue.

 "@jitsi/react-native-sdk": "^11.6.3"

ios - 26.1

<img width="1206" height="2622" alt="Image" src="https://github.com/user-attachments/assets/a09e37a1-47f2-436e-966b-0bae2300c16f" />

<img width="1206" height="2622" alt="Image" src="https://github.com/user-attachments/assets/be65b665-1ed2-4d5f-81eb-a1e679e33df5" />

**Comment by saghul** [comment]
What version of react-native-webrtc do you have?

**Comment by KolissnikBogdan** [comment]
@saghul "react-native-webrtc": "124.0.4"

**Comment by saghul** [comment]
Update to 124.0.7.

**Comment by KolissnikBogdan** [comment]
@saghul got it, thx
