### ISSUE TITLE
android app crashing on startup

### ISSUE THREAD

**Issue by petervnv** [jitsi/jitsi-meet#1963]
Hi again,

I just did a fresh git clone and have been trying to compile the android app on an OS X and also an Ubuntu host.

I managed to compile the app on both platforms, but when I compile and run the app in Android Studio and the OSX android emulator I get the dreaded "Could not get BatchedBridge" error (see full logs from emulator here https://pastebin.com/aU3EATLZ )

When I compile on the ubuntu host in release mode it seems to compile fine without any errors. Unfortunately when I then try to run the app on different Samsung phones (android 6 and 7) it crashes immediately at startup.

Is anyone else having these issues with latest code? Where should I be looking?

Cheers,
Peter

**Comment by petervnv** [comment]
Just did a fresh pull and tried again on my ubuntu environment (16.04 LTS)
node v6.11.2
npm 3.10.10

I'm able to compile and install it directly from Android Studio on my S6 Edge but it immediately crashes with the usual "BatchedBridge" error....

Can anyone confirm what version of android studio they're using to compile jitsi meet?

Because of newer gradle dependency in the code, my AS "forced" me to upgrade to AS 3.0 beta 4. Has anyone gotten it to compile (and actually run) on AS 3.0 beta 4 on Ubuntu 16.04 LTS (amd64)?

Here's the crash in the logs:

09-07 17:56:32.397 20054-20111/? E/unknown:React: Exception in native call from JS
                                                  com.facebook.react.devsupport.JSException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                      at android.os.Looper.loop(Looper.java:154)
                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                      at java.lang.Thread.run(Thread.java:762)
                                                   Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                      at android.os.Handler.handleCallback(Handler.java:751) 
                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                      at android.os.Looper.loop(Looper.java:154) 
                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                      at java.lang.Thread.run(Thread.java:762) 
09-07 17:56:32.400 3725-6979/system_process D/MdnieScenarioControlService:  packageName : org.jitsi.meet    className : org.jitsi.meet.MainActivity
09-07 17:56:32.418 3725-3805/system_process I/WindowManager: Destroying surface Surface(name=Starting org.jitsi.meet) called by com.android.server.wm.WindowStateAnimator.destroySurface:-1 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:-1 com.android.server.wm.WindowState.destroyOrSaveSurface:-1 com.android.server.wm.AppWindowToken.destroySurfaces:-1 com.android.server.wm.AppWindowToken.destroySurfaces:-1 com.android.server.wm.WindowStateAnimator.finishExit:-1 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:-1 com.android.server.wm.WindowAnimator.updateWindowsLocked:-1 
09-07 17:56:32.418 3056-4996/? I/SurfaceFlinger: id=138 Removed neet (3/12)
09-07 17:56:32.419 3725-3805/system_process D/LockSettingsStorage: mSKTLockState = 2
09-07 17:56:32.421 3056-4996/? I/SurfaceFlinger: id=138 Removed neet (-2/12)
09-07 17:56:32.422 3725-3805/system_process D/LockSettingsStorage: mSKTLockState = 2
09-07 17:56:32.435 16987-18993/com.google.android.gms I/Icing: Indexing done 6747BE1A8AFCCBAEE6E7FF5E56B37C42EC6CF972
09-07 17:56:32.439 20054-20054/org.jitsi.meet W/unknown:React: Packager connection already open, nooping.
09-07 17:56:32.439 20054-20054/org.jitsi.meet W/unknown:React: Inspector connection already open, nooping.
09-07 17:56:32.444 20054-20111/org.jitsi.meet E/unknown:React: Exception in native call
                                                               java.lang.RuntimeException: Error calling function: RCTDeviceEventEmitter:emit
                                                                   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                   at java.lang.Thread.run(Thread.java:762)
                                                                Caused by: java.lang.RuntimeException: Empty Optional cannot be unwrapped
                                                                   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                   at android.os.Handler.handleCallback(Handler.java:751) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                   at android.os.Looper.loop(Looper.java:154) 
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                   at java.lang.Thread.run(Thread.java:762) 
09-07 17:56:32.446 3725-7663/system_process I/SemPersonaManager: mKnoxInfo is empty
09-07 17:56:32.452 20054-20111/org.jitsi.meet E/unknown:React: Exception in native call
                                                               java.lang.RuntimeException: Error calling function: AppRegistry:runApplication
                                                                   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                   at java.lang.Thread.run(Thread.java:762)
                                                                Caused by: java.lang.RuntimeException: Empty Optional cannot be unwrapped
                                                                   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                   at android.os.Handler.handleCallback(Handler.java:751) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                   at android.os.Looper.loop(Looper.java:154) 
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                   at java.lang.Thread.run(Thread.java:762)

**Comment by petervnv** [comment]
OK, I just tried building it from the terminal with my S6 attached like instructed in the wiki and I got an annoying "invalid dimen" error (just like in issue https://github.com/jitsi/jitsi-meet/issues/1962). But unlike with Android Studio in issue 1962, running LC_NUMERIC="en_US.UTF-8" before running the react-native command doesn't fix it.

Any clues?


android/jitsi-meet$ react-native run-android

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Error: java.lang.RuntimeException: com.android.builder.internal.aapt.AaptException: AAPT2 compile failed:
  aapt2 compile --legacy -o /home/yoda/Documents/Bubble/android/jitsi-meet/android/app/build/intermediates/res/merged/debug /home/yoda/Documents/Bubble/android/jitsi-meet/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
  Issues:
   - ERROR: /home/yoda/Documents/Bubble/android/jitsi-meet/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:257 invalid dimen
   - ERROR: /home/yoda/Documents/Bubble/android/jitsi-meet/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:258 invalid dimen
   - ERROR: /home/yoda/Documents/Bubble/android/jitsi-meet/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:293 invalid dimen
   - ERROR: /home/yoda/Documents/Bubble/android/jitsi-meet/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:294 invalid dimen
   - ERROR: /home/yoda/Documents/Bubble/android/jitsi-meet/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:295 invalid dimen
   - ERROR: /home/yoda/Documents/Bubble/android/jitsi-meet/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:296 invalid dimen
   - ERROR: /home/yoda/Documents/Bubble/android/jitsi-meet/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:297 invalid dimen
   - ERROR: /home/yoda/Documents/Bubble/android/jitsi-meet/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:298 invalid dimen
   - ERROR: /home/yoda/Documents/Bubble/android/jitsi-meet/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:299 invalid dimen
   - ERROR: /home/yoda/Documents/Bubble/android/jitsi-meet/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:300 invalid dimen
   - ERROR: /home/yoda/Documents/Bubble/android/jitsi-meet/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:301 invalid dimen

**Comment by petervnv** [comment]
Forgot to add:

react-native-cli: 2.0.1
react-native: 0.42.3

**Comment by lyubomir** [comment]
Can you do a meeting at https://meet.jit.si/LyuboAndPetervnv so that you can show me your desktop and we can talk in real time?

**Comment by saghul** [comment]
I just pushed https://github.com/jitsi/jitsi-meet/commit/ba49c7955ae9ea216a52c00fc3ca16734c40a28d which should make AS 3.0 beta 4 work. Can you try again? Make sure you first clean the projects with `./gradlew clean`.

**Comment by petervnv** [comment]
Thanks @saghul 
I had already made those changes manually yesterday or else it wouldn't even compile.

It does compile but I still get the BatchedBridge error as soon as it runs. My friend (that's on a Mac - I'm on ubuntu 160.4 LTS) just also tried to compile and he tells me he's also getting the BatchedBridge error...

**Comment by petervnv** [comment]
Quick update.
My friend on OSX was finally able to compile and get it working without the BatchedBridge error.

He deleted the node_modules folder
then ran npm install
then he ran make
finally he ran react-native run-android and this time it all worked as expected.

I've tried doing the same on my ubuntu machine but I keep getting the BatchedBridge error nevertheless.

This leads me to suspect the problem is related to building in linux instead of OSX.

Hope this info helps others that have the same issue.
