### ISSUE TITLE
Crashing with newest React-Native. (No virtual method setJSMainModuleName)

### ISSUE THREAD

**Issue by KaniZ0r** [jitsi/jitsi-meet#2314]
setJSMainModuleName from ReactInstanceManager was renamed to setJSMainModulePath on 10 Aug and JitsiMeet SDK for Android is crashing due that. 

Here's commit from React-Native github page:
 https://github.com/facebook/react-native/commit/5d4c6e5f23e3f7f64576cccff76822d4b7635ab1#diff-56c62f6d197d573adf37c27985cdadd3.

Here's error message from logcat:

12-21 11:20:36.550 25106 25106 E AndroidRuntime: FATAL EXCEPTION: main
12-21 11:20:36.550 25106 25106 E AndroidRuntime: Process: com.rntest, PID: 25106
12-21 11:20:36.550 25106 25106 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method setJSMainModuleName(Ljava/lang/String;)Lcom/facebook/react/ReactInstanceManagerBuilder; in class Lcom/facebook/react/ReactInstanceManagerBuilder; or its super classes (declaration of 'com.facebook.react.ReactInstanceManagerBuilder' appears in /data/app/com.rntest-2/base.apk)
12-21 11:20:36.550 25106 25106 E AndroidRuntime:        at org.jitsi.meet.sdk.JitsiMeetView.initReactInstanceManager(JitsiMeetView.java:95)
12-21 11:20:36.550 25106 25106 E AndroidRuntime:        at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:252)
12-21 11:20:36.550 25106 25106 E AndroidRuntime:        at com.rntest.MainActivity.onCreate(MainActivity.java:27)
12-21 11:20:36.550 25106 25106 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6309)
12-21 11:20:36.550 25106 25106 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
12-21 11:20:36.550 25106 25106 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2519)
12-21 11:20:36.550 25106 25106 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654)
12-21 11:20:36.550 25106 25106 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
12-21 11:20:36.550 25106 25106 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
12-21 11:20:36.550 25106 25106 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:111)
12-21 11:20:36.550 25106 25106 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
12-21 11:20:36.550 25106 25106 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5728)
12-21 11:20:36.550 25106 25106 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-21 11:20:36.550 25106 25106 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
12-21 11:20:36.550 25106 25106 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
12-21 11:20:36.552   951  1741 W ActivityManager:   Force finishing activity com.rntest/.MainActivity

**Comment by saghul** [comment]
This has been fixed for a while now: https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetView.java#L98 Please update your checkout.

**Comment by KaniZ0r** [comment]
Jitsi-Meet-SDK is updated 3 months ago and problem still occurs with it.

**Comment by saghul** [comment]
Are you building the SDK yourself? If so, update your local copy, that **is** fixed already.
