### ISSUE TITLE
Lots of "No jid for ssrc" messages logged

### ISSUE THREAD

**Issue by bgrozev** [jitsi/jitsi-meet#260]
Sometimes Jitsi Meet logs hundreds of "No jid for ssrc" messages to the console.

**Comment by d2chau** [comment]
This seems to be reproducible when users are in a meeting and anyone decides to toggle off/on their video stream.

**Comment by bgrozev** [comment]
On April 17, 2015 10:48:37 PM CEST, David <notifications@github.com> wrote:
>This seems to be reproducible when users are in a meeting and anyone
>decides to toggle off/on their video stream. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jitsi/jitsi-meet/issues/260#issuecomment-94072180

I suspect this might be affected/fixed with the latest PR that Pawel merged (can't look it up at the moment). Could you confirm that you repro with current master?

Boris
-- 
Sent from a mobile. Please excuse my brevity.

**Comment by d2chau** [comment]
With current master, the "No jid for ssrc" still appears for everyone in the meeting but only when user's disable their camera. This can also be seen on meet.jit.si

**Comment by hamidyaseen** [comment]
I am also observing the same issue by using the mute video (camera icon) option in toolbar at one conference participant....

**Comment by Zalmoxisus** [comment]
Yes, it always happens when mute/unmute video, and we get an infinite cycle, which can cause CPU spikes.

Steps to reproduce:
1. Open https://meet.jit.si/
2. Open in other window the same url (participant 2).
3. Click "stop camera" icon for the participant 2. Start camera and stop again.
As a result we get infinite messages in the console of Particiapant 1.

**Comment by hristoterezov** [comment]
For me the messages are printed only for 2-3 seconds.

**Comment by Zalmoxisus** [comment]
@hristoterezov, yes, first time the messages are printed only for 2-3 seconds, and the second time there are infinite messages on the console of Particiapant 1.

**Comment by LeoIannacone** [comment]
I can confime this

**Comment by bgrozev** [comment]
I don't see the messages any more.
