### ISSUE TITLE
Speaker mode only when startAudioOnly passed in config

### ISSUE THREAD

**Issue by carotkut94** [jitsi/jitsi-meet#3498]
I have added bundle config as below
 ` Bundle config = new Bundle();
        config.putBoolean("startAudioOnly", true);
        Bundle urlObject = new Bundle();
        urlObject.putBundle("config", config);
        urlObject.putString("url", "https://meet.jit.si/demo");
        view.loadURLObject(urlObject);
        setContentView(view);`

call starts as audio only, but audio gets routed to speaker, instead of earphone, and i press on select the sound device, i only get the option of "Speaker".
and if i start the jitsi-meet android app(downloaded from play store) and start the voice only call, it works as expected.
What am i missing?

**Comment by saghul** [comment]
If you try setting this URL: `https://meet.jit.si/demo#config.startAudioOnly=true` does it work as expected?

**Comment by carotkut94** [comment]
No, same behavior,  audio gets routed to speaker instead of earphone , and earphone does not show up in change audio route,

**Comment by saghul** [comment]
Can you paste (not here, use a gist please) the logs obtained with `adb logcat` ? Thanks!

**Comment by carotkut94** [comment]
here is the link for the adb logcat https://pastebin.com/Y5MecbrH

**Comment by saghul** [comment]
What permissions did you set in your manifest? I see an exception when calling `setSpeakerphoneOn` on your log.

**Comment by carotkut94** [comment]
setSpeakerphoneOn  is by default on, and when i run the app, at first it asks me to access the mic and camera, i have not defined any permission in the manifest.

**Comment by saghul** [comment]
Hum. Do you see a difference the second time you try this? That is, after the permission was granted.

**Comment by carotkut94** [comment]
No,there is no difference.
at first run it asks for permission, and after allowing them app gets connected to the server
and once the permissions are granted, this process remains the same, just one difference that it does not ask for permission again

**Comment by carotkut94** [comment]
@saghul 
Any idea on it? 
and I have another question about jitis-meet app on android studio, is it the same app, which is on github available at https://github.com/jitsi/jitsi-meet/tree/master/android/app , if yes then is it written in react-native? is so then where i can find the code related to that toggle button, which changes the conference mode to video - audio and vice versa.

**Comment by carotkut94** [comment]
I am not asking about the button on, overflow menu,
![inkedscreenshot_20181005-121213_li](https://user-images.githubusercontent.com/17780580/46520093-53202580-c898-11e8-9270-bd4c2ee8c0ba.jpg)
I am talking about the toggle button on the toolbar, as in the above image

**Comment by saghul** [comment]
Ah that. That's not a toolbar :-) Here it is: https://github.com/jitsi/jitsi-meet/blob/master/react/features/welcome/components/WelcomePage.native.js#L106

**Comment by carotkut94** [comment]
Thanks  @saghul  , let me look into the implementation of <VideoSwitch/>

**Comment by Frindecent** [comment]
Got this issue here too

**Comment by RheineAdithia** [comment]
got this issue too, and after a few test, the bug only persist in android verson above Marshmallow.. Marshmallow version got the speaker redirected after initialization.

any update on this bug

**Comment by saghul** [comment]
I'll give this a test later today @RheineAdithia. Can you reproduce this with the latest release of Jitsi Meet (from the Play store).

**Comment by saghul** [comment]
There might have been a bug we fixed then. I can't recall TBH. Yeah, please try the latest code in master and report back! Cheers!

**Comment by RheineAdithia** [comment]
We have tried to use the latest code (jitsi version 1.9) mr. Saul, but there is a failed to resolve some of the package used

Failed to resolve: com.facebook.react:react-native:0.56.0
Open File
Show in Project Structure dialog


Failed to resolve: com.facebook.react:react-native-fetch-blob:0.10.8-jitsi-1
Open File
Show in Project Structure dialog


Failed to resolve: com.facebook.react:react-native-linear-gradient:2.4.0-jitsi-1
Open File
Show in Project Structure dialog


Failed to resolve: com.facebook.react:react-native-sound:0.10.9-jitsi-1
Open File
Show in Project Structure dialog


Failed to resolve: com.facebook.react:react-native-calendar-events:1.6.0-jitsi-1
Open File
Show in Project Structure dialog

Is many people seeing this problem?

---------------------------------------------

Warmest Regards

Rheine Adithia Kurniawan
Vocalist - Tour Leader - Programmer
WhatsApp : +6281802083670
LINE : rheineadithia
IG : Rheine_adithia
Email : rheine_adithia@hotmail.com
---------------------------------------------

________________________________

**Comment by RheineAdithia** [comment]
It seems that our developer has always taken the latest source using the maven repository. So it is already updated to the latest (the 1.16 version) and the bug is still persisting.

Is there any method that im missing here mr Saul?

---------------------------------------------

Warmest Regards

Rheine Adithia Kurniawan
Vocalist - Tour Leader - Programmer
WhatsApp : +6281802083670
LINE : rheineadithia
IG : Rheine_adithia
Email : rheine_adithia@hotmail.com
---------------------------------------------

________________________________

**Comment by saghul** [comment]
1.16 is too old. I'm going to work on releasing 1.20 hopefully soon.

**Comment by carotkut94** [comment]
@saghul  when can we expect the new artifacts? is there an ETA for this?

**Comment by RheineAdithia** [comment]
So we need to take the 1.19 version?? Which version is the latest one mr shaul? And can you give me the link to where the repository is?

We use the one that is documented in the jitsi GitHub page, by using this :
Use pre-build SDK artifacts/binaries

and it gave us that version.

---------------------------------------------

Warmest Regards

Rheine Adithia Kurniawan
Vocalist - Tour Leader - Programmer
WhatsApp : +6281802083670
LINE : rheineadithia
IG : Rheine_adithia
Email : rheine_adithia@hotmail.com
---------------------------------------------

________________________________

**Comment by RheineAdithia** [comment]
@saghul is this the right maven repo url : https://github.com/jitsi/jitsi-maven-repository/tree/master/releases ? because this is where we pulled the code and build our own artifact , and it shows that the version is 1.9 in the code?

**Comment by saghul** [comment]
Yes, that's the right maven repo URL. But as I said there is one dependency missing. This repo contains the source so you can try and build it yourself while we fix and upload 1.20 to the maven repo.

**Comment by adimulyo29** [comment]
any updates on the latest release @saghul @RheineAdithia @carotkut94

**Comment by saghul** [comment]
No updates as of yet, sorry.
