### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by stanukih** [jitsi/jitsi-meet#3955]
If you send only a space to the message, the formatting moves out.

**Comment by saghul** [comment]
@virtuacoplenny care to take a look when you've got time?

**Comment by virtuacoplenny** [comment]
Should be fixed now with https://github.com/jitsi/jitsi-meet/pull/3972.

**Comment by stanukih** [comment]
How often is the site https://meet.jit.si/******** version updated? While there the problem remained.

**Comment by saghul** [comment]
every few weeks.

**Comment by saghul** [comment]
#3972 landed, closing. Thanks @virtuacoplenny for the fix and @stanukih for reporting!

**Comment by stanukih** [comment]
While the problem persists. It is not convenient for me to use the hand tool since it is not visible who wants to say. For this we use chat. A message with a space means I want to reply. If several people send a blank message, the formatting in the chat shifts.

**Comment by stanukih** [comment]
![8](https://user-images.githubusercontent.com/11682091/54188614-e7d72100-44d1-11e9-93ba-69f690cbc575.jpg)

**Comment by saghul** [comment]
> While the problem persists.

It hasn't been deployed to meet.jit.si yet. You can test it in https://beta.meet.jit.si/test123



> It is not convenient for me to use the hand tool since it is not visible who wants to say. For this we use chat. A message with a space means I want to reply. If several people send a blank message, the formatting in the chat shifts.

I really don't understand what you mean here. What has the "raise hand" feature have to do with sending a space in chat?

**Comment by stanukih** [comment]
![8](https://user-images.githubusercontent.com/11682091/54190453-ae081980-44d5-11e9-8fd3-74a36af7e2f8.jpg)

**Comment by stanukih** [comment]
Raise/Lower your hand.
I can not see who wants to answer. If you send an empty message in the chat, you immediately see who wants to reply.

**Comment by saghul** [comment]
> Raise/Lower your hand.
> I can not see who wants to answer.

It's right there on every thumbnail. Or do you mean you cannot see it from the chat?



> If you send an empty message in the chat, you immediately see who wants to reply.

Well, that's a convention you used which will no longer work.

**Comment by stanukih** [comment]
OK. Maybe then it is worth adding a signature to the sketches, for example, from the bottom right of the user's nickname? Just seeing the hand is not clear who it is. Directing each time and read the nickname is not very convenient.
