### ISSUE TITLE
Jitsi Meet Stable download hangs

### ISSUE THREAD

**Issue by unicornmafia** [jitsi/jitsi-meet#4241]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Jitsi download key command times out

## Current behavior
```
~ » wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | sudo apt-key add -
gpg: no valid OpenPGP data found.
```
also hangs when opening:
```
https://download.jitsi.org/stable/
```

## Expected Behavior
should download / open

## Possible Solution
---

## Steps to reproduce
---

# Environment details
Ubuntu 18.04.2 LTS

**Comment by damencho** [comment]
We are aware of the problem and we are working on fixing it, will let you know as soon it is resolved.

**Comment by damencho** [comment]
All issues had been fixed and download.jitsi.org is back.

**Comment by carlosibanezramirez** [comment]
The error still remains in Debian. The error is:
E: El repositorio «https://download.jitsi.org stable/ Release» no tiene un fichero de Publicación.

**Comment by carlosibanezramirez** [comment]
Err:5 https://download.jitsi.org stable/ Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 130.79.200.22 443]
