### ISSUE TITLE
Crash on iOS 13 on call end

### ISSUE THREAD

**Issue by nasircsms** [jitsi/jitsi-meet#4717]
## Description
---
Upon terminating call on iOS 13.1.1 I am facing crash. Below is the full stack trace from lldb

`
[JitsiMeetSDK] [VideoCaptureController] Capture stopped
*** Assertion failure in -[FBSSerialQueue assertOnQueue], /BuildRoot/Library/Caches/com.apple.xbs/Sources/FrontBoardServices/FrontBoard-619.2/FrontBoardServices/FBSSerialQueue.m:98
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'threading violation: expected the main thread'
*** First throw call stack:
(0x1a202498c 0x1a1d4d0a4 0x1a1f26d1c 0x1a235c8f4 0x1a7106b74 0x1a70bc0bc 0x1a70bc324 0x1a70bc22c 0x1a5bd043c 0x1a5cb8958 0x1a5cb9648 0x10ade9158 0x10c875828 0x10c876c04 0x10c87db74 0x10c87e710 0x10c889ae4 0x1a1d41fa4 0x1a1d44ae0)
libc++abi.dylib: terminating with uncaught exception of type NSException+

* thread .20, queue = 'org.webrtc.RTCDispatcherCaptureSession', stop reason = signal SIGABRT
  * frame .0: 0x00000001a1e1cebc libsystem_kernel.dylib`__pthread_kill + 8
    frame .1: 0x00000001a1d38790 libsystem_pthread.dylib`pthread_kill$VARIANT$mp + 112
    frame .2: 0x00000001a1c8c824 libsystem_c.dylib`abort + 100
    frame .3: 0x00000001a1de57d4 libc++abi.dylib`abort_message + 128
    frame .4: 0x00000001a1de59c4 libc++abi.dylib`demangling_terminate_handler() + 296
    frame .5: 0x00000001a1d4d358 libobjc.A.dylib`_objc_terminate() + 124
    frame .6: 0x00000001a1df2304 libc++abi.dylib`std::__terminate(void (*)()) + 16
    frame .7: 0x00000001a1df229c libc++abi.dylib`std::terminate() + 44
    frame .8: 0x00000001a1d4d2dc libobjc.A.dylib`objc_terminate + 12
    frame .9: 0x000000010c876c18 libdispatch.dylib`_dispatch_client_callout + 36
    frame .10: 0x000000010c87db74 libdispatch.dylib`_dispatch_lane_serial_drain + 744
    frame .11: 0x000000010c87e710 libdispatch.dylib`_dispatch_lane_invoke + 448
    frame .12: 0x000000010c889ae4 libdispatch.dylib`_dispatch_workloop_worker_thread + 1324
    frame .13: 0x00000001a1d41fa4 libsystem_pthread.dylib`_pthread_wqthread + 276

  thread .1, queue = 'com.apple.main-thread'
    frame .0: 0x00000001a1d431a0 libsystem_pthread.dylib`_pthread_qos_class_to_thread_qos + 16
    frame .1: 0x00000001a1d43bcc libsystem_pthread.dylib`pthread_qos_max_parallelism + 36
    frame .2: 0x00000001acbf9418 vImage`vImageConvert_ARGBFFFFtoPlanarF + 236
    frame .3: 0x00000001acd1a4c4 vImage`AnyToAnyBlockInternal + 1600
    frame .4: 0x00000001acd140c0 vImage`vImageConvert_AnyToAny + 2976
    frame .5: 0x00000001a296ab70 ImageIO`iio_vImageConvert_AnyToAny(vImageConverter*, vImage_Buffer const*, vImage_Buffer const*, void*, unsigned int) + 220
    frame .6: 0x00000001a2966b24 ImageIO`IIOColorConverter::colorConvert(vImage_Buffer*, vImage_Buffer*) + 28
    frame .7: 0x00000001a289232c ImageIO`IIOIOSurfaceWrapper::copy_and_colormatch_CIF10_to_P3_vImage(unsigned char*, unsigned int, unsigned char*, unsigned int) + 820
    frame .8: 0x00000001a289092c ImageIO`IIOIOSurfaceWrapper::CopyImageBlockSetWithOptions(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 3564
    frame .9: 0x00000001a8f5b314 CoreGraphics`imageProvider_retain_data + 88
    frame .10: 0x00000001a8d5c938 CoreGraphics`CGDataProviderRetainData + 84
    frame .11: 0x00000001a8ec5c14 CoreGraphics`provider_for_destination_retain_data + 24
    frame .12: 0x00000001a8d5c938 CoreGraphics`CGDataProviderRetainData + 84
    frame .13: 0x00000001a8f4ad7c CoreGraphics`CGAccessSessionCreate + 104
    frame .14: 0x00000001a8e389a0 CoreGraphics`img_data_lock + 2476
    frame .15: 0x00000001a8e367ec CoreGraphics`CGSImageDataLock + 1120
    frame .16: 0x00000001a8c67a10 CoreGraphics`ripc_AcquireRIPImageData + 712
    frame .17: 0x00000001a8e51754 CoreGraphics`ripc_DrawImage + 1112
    frame .18: 0x00000001a8e3d460 CoreGraphics`CGContextDrawImageWithOptions + 1212
    frame .19: 0x00000001a5c919a0 UIKitCore`-[UIImage drawInRect:blendMode:alpha:] + 1472
    frame .20: 0x00000001a649cb4c UIKitCore`-[UIView _drawViewHierarchyInRect:] + 324
    frame .21: 0x00000001a60a44c4 UIKitCore`___UIDrawViewRectAfterCommit_block_invoke_2 + 40
    frame .22: 0x00000001a60a3fdc UIKitCore`_UIDrawViewRectAfterCommit + 744
    frame .23: 0x00000001031a5f24 MyApp`-[GMSOffscreenEntitiesHostView newFrame] + 152
    frame .24: 0x00000001031a5874 MyApp`__36-[GMSOffscreenEntitiesHostView init]_block_invoke + 36
    frame .25: 0x000000010337dcdc MyApp`gmscore::renderer::ios::BlockBasedBehavior::Commit(gmscore::renderer::EntityRenderer*) + 28
    frame .26: 0x0000000103370d2c MyApp`gmscore::renderer::EntityRenderer::Draw(bool) + 376
    frame .27: 0x00000001034176b4 MyApp`-[GMSPhoenixRenderer drawForced:] + 68
    frame .28: 0x00000001033f9ea8 MyApp`-[GMSEntityRendererView draw] + 392
    frame .29: 0x00000001033f7350 MyApp`-[GMSDisplayLink displayLinkFired:] + 320
    frame .30: 0x000000010ca595f8 GPUToolsCore`-[DYDisplayLinkInterposer forwardDisplayLinkCallback:] + 168
    frame .31: 0x00000001a886a514 QuartzCore`CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 632
    frame .32: 0x00000001a2f5deb0 IOKit`IODispatchCalloutFromCFMessage + 488
    frame .33: 0x00000001a1f796d4 CoreFoundation`__CFMachPortPerform + 172
    frame .34: 0x00000001a1fa2e5c CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
    frame .35: 0x00000001a1fa2588 CoreFoundation`__CFRunLoopDoSource1 + 444
    frame .36: 0x00000001a1f9d45c CoreFoundation`__CFRunLoopRun + 2168
    frame .37: 0x00000001a1f9c8bc CoreFoundation`CFRunLoopRunSpecific + 464
    frame .38: 0x00000001abe08328 GraphicsServices`GSEventRunModal + 104
    frame .39: 0x00000001a60326d4 UIKitCore`UIApplicationMain + 1936
    frame .40: 0x0000000102fbed24 MyApp`main at AppDelegate.swift:15:7
    frame .41: 0x00000001a1e27460 libdyld.dylib`start + 4
  thread .4, name = 'gputools.smt_poll.0x280910900'
    frame .0: 0x00000001a1e1d238 libsystem_kernel.dylib`__semwait_signal + 8
    frame .1: 0x00000001a1c89644 libsystem_c.dylib`nanosleep + 212
    frame .2: 0x00000001a1c8951c libsystem_c.dylib`usleep + 64
    frame .3: 0x000000010ca4e298 GPUToolsCore`smt_poll_thread_entry(void*) + 136
    frame .4: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .5, name = 'gputools.smt_poll.0x280910ce0'
    frame .0: 0x00000001a1e1d238 libsystem_kernel.dylib`__semwait_signal + 8
    frame .1: 0x00000001a1c89644 libsystem_c.dylib`nanosleep + 212
    frame .2: 0x00000001a1c8951c libsystem_c.dylib`usleep + 64
    frame .3: 0x0000000105713da4 libMTLCapture.dylib`___lldb_unnamed_symbol1787$$libMTLCapture.dylib + 100
    frame .4: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .7, queue = 'WebRTCModule.queue'
    frame .0: 0x00000001a1dfb630 libsystem_kernel.dylib`semaphore_wait_trap + 8
    frame .1: 0x000000010c877290 libdispatch.dylib`_dispatch_sema4_wait + 24
    frame .2: 0x000000010c8778d4 libdispatch.dylib`_dispatch_semaphore_wait_slow + 140
    frame .3: 0x000000010c0cfe70 JitsiMeet`-[VideoCaptureController stopCapture] + 128
    frame .4: 0x000000010c0d2524 JitsiMeet`-[WebRTCModule(RTCMediaStream) mediaStreamRelease:] + 368
    frame .5: 0x00000001a202ad90 CoreFoundation`__invoking___ + 144
    frame .6: 0x00000001a1efabd0 CoreFoundation`-[NSInvocation invoke] + 300
    frame .7: 0x00000001a1efb7a8 CoreFoundation`-[NSInvocation invokeWithTarget:] + 76
    frame .8: 0x000000010c027ff8 JitsiMeet`-[RCTModuleMethod invokeWithBridge:module:arguments:] + 460
    frame .9: 0x000000010c02a108 JitsiMeet`facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&) + 244
    frame .10: 0x000000010c029e6c JitsiMeet`___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 88
    frame .11: 0x000000010c875828 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame .12: 0x000000010c876c04 libdispatch.dylib`_dispatch_client_callout + 16
    frame .13: 0x000000010c87db74 libdispatch.dylib`_dispatch_lane_serial_drain + 744
    frame .14: 0x000000010c87e710 libdispatch.dylib`_dispatch_lane_invoke + 448
    frame .15: 0x000000010c889ae4 libdispatch.dylib`_dispatch_workloop_worker_thread + 1324
    frame .16: 0x00000001a1d41fa4 libsystem_pthread.dylib`_pthread_wqthread + 276
  thread .9, name = 'com.apple.uikit.eventfetch-thread'
    frame .0: 0x00000001a1dfb5f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame .1: 0x00000001a1dfaa60 libsystem_kernel.dylib`mach_msg + 72
    frame .2: 0x00000001a1fa2068 CoreFoundation`__CFRunLoopServiceMachPort + 216
    frame .3: 0x00000001a1f9d188 CoreFoundation`__CFRunLoopRun + 1444
    frame .4: 0x00000001a1f9c8bc CoreFoundation`CFRunLoopRunSpecific + 464
    frame .5: 0x00000001a22dc994 Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 228
    frame .6: 0x00000001a22dc874 Foundation`-[NSRunLoop(NSRunLoop) runUntilDate:] + 88
    frame .7: 0x00000001a60ca49c UIKitCore`-[UIEventFetcher threadMain] + 152
    frame .8: 0x00000001a240d0b0 Foundation`__NSThread__start__ + 848
    frame .9: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .10, queue = 'AudioMode.queue'
    frame .0: 0x00000001a1dfb5f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame .1: 0x00000001a1dfaa60 libsystem_kernel.dylib`mach_msg + 72
    frame .2: 0x00000001ad010018 AudioToolbox`ASClient_AudioSessionGetPropertyMessage + 180
    frame .3: 0x00000001acf8f7c4 AudioToolbox`AudioSessionCopyProperty_Priv + 544
    frame .4: 0x00000001aea27ddc AVFAudio`int GetProperty<unsigned int>(unsigned int, unsigned int, unsigned int*) + 60
    frame .5: 0x00000001aea27ca8 AVFAudio`void GetProperty_DefaultToZero<unsigned int>(unsigned int, unsigned int, unsigned int&) + 48
    frame .6: 0x00000001aea1fd3c AVFAudio`-[AVAudioSession category] + 68
    frame .7: 0x000000010adc4d84 WebRTC`::-[RTCAudioSession category](self=<unavailable>, _cmd=<unavailable>) at RTCAudioSession.mm:234:23 [opt]
    frame .8: 0x000000010adc2f5c WebRTC`::-[RTCAudioSession(self=0x0000000283b52760, _cmd=<unavailable>, configuration=<unavailable>, active=NO, shouldSetActive=NO, outError=0x000000016d40e568) setConfiguration:active:shouldSetActive:error:](RTCAudioSessionConfiguration *, BOOL, BOOL, NSError **) at RTCAudioSession+Configuration.mm:54:12 [opt]
    frame .9: 0x000000010adc2eb0 WebRTC`::-[RTCAudioSession(self=<unavailable>, _cmd=<unavailable>, configuration=<unavailable>, outError=<unavailable>) setConfiguration:error:](RTCAudioSessionConfiguration *, NSError **) at RTCAudioSession+Configuration.mm:20:10 [opt]
    frame .10: 0x000000010bc4bf50 JitsiMeet`-[AudioMode setConfig:error:] + 108
    frame .11: 0x000000010bc4c038 JitsiMeet`-[AudioMode setMode:resolve:reject:] + 164
    frame .12: 0x00000001a202ad90 CoreFoundation`__invoking___ + 144
    frame .13: 0x00000001a1efabd0 CoreFoundation`-[NSInvocation invoke] + 300
    frame .14: 0x00000001a1efb7a8 CoreFoundation`-[NSInvocation invokeWithTarget:] + 76
    frame .15: 0x000000010c027ff8 JitsiMeet`-[RCTModuleMethod invokeWithBridge:module:arguments:] + 460
    frame .16: 0x000000010c02a108 JitsiMeet`facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&) + 244
    frame .17: 0x000000010c029e6c JitsiMeet`___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 88
    frame .18: 0x000000010c875828 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame .19: 0x000000010c876c04 libdispatch.dylib`_dispatch_client_callout + 16
    frame .20: 0x000000010c87db74 libdispatch.dylib`_dispatch_lane_serial_drain + 744
    frame .21: 0x000000010c87e710 libdispatch.dylib`_dispatch_lane_invoke + 448
    frame .22: 0x000000010c889ae4 libdispatch.dylib`_dispatch_workloop_worker_thread + 1324
    frame .23: 0x00000001a1d41fa4 libsystem_pthread.dylib`_pthread_wqthread + 276
  thread .11, name = 'Realm notification listener'
    frame .0: 0x00000001a1e1e99c libsystem_kernel.dylib`kevent + 8
    frame .1: 0x0000000106ce3aa0 Realm`realm::_impl::ExternalCommitHelper::listen(this=0x0000000280770f90) at external_commit_helper.cpp:216:15
    frame .2: 0x0000000106ce87cc Realm`realm::_impl::ExternalCommitHelper::ExternalCommitHelper(this=0x0000000280b0b418)::$_0::operator()() const at external_commit_helper.cpp:173:13
    frame .3: 0x0000000106ce8768 Realm`decltype(__f=0x0000000280b0b418)::$_0>(fp)()) std::__1::__invoke<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>(realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0&&) at type_traits:4361:1
    frame .4: 0x0000000106ce86c8 Realm`void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>(__t=size=2, (null)=__tuple_indices<> @ 0x000000016d49af58)::$_0>&, std::__1::__tuple_indices<>) at thread:342:5
    frame .5: 0x0000000106ce7dac Realm`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >(__vp=0x0000000280b0b410) at thread:352:5
    frame .6: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .12, name = 'AVAudioSession Notify Thread'
    frame .0: 0x00000001a1dfb5f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame .1: 0x00000001a1dfaa60 libsystem_kernel.dylib`mach_msg + 72
    frame .2: 0x00000001a1fa2068 CoreFoundation`__CFRunLoopServiceMachPort + 216
    frame .3: 0x00000001a1f9d188 CoreFoundation`__CFRunLoopRun + 1444
    frame .4: 0x00000001a1f9c8bc CoreFoundation`CFRunLoopRunSpecific + 464
    frame .5: 0x00000001ae9fde68 AVFAudio`GenericRunLoopThread::Entry(void*) + 156
    frame .6: 0x00000001aea4edf0 AVFAudio`CAPThread::Entry(CAPThread*) + 204
    frame .7: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .13, name = 'com.apple.NSURLConnectionLoader'
    frame .0: 0x00000001a1dfb5f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame .1: 0x00000001a1dfaa60 libsystem_kernel.dylib`mach_msg + 72
    frame .2: 0x00000001a1fa2068 CoreFoundation`__CFRunLoopServiceMachPort + 216
    frame .3: 0x00000001a1f9d188 CoreFoundation`__CFRunLoopRun + 1444
    frame .4: 0x00000001a1f9c8bc CoreFoundation`CFRunLoopRunSpecific + 464
    frame .5: 0x00000001a5217e68 CFNetwork`___lldb_unnamed_symbol3$$CFNetwork + 192
    frame .6: 0x00000001a240d0b0 Foundation`__NSThread__start__ + 848
    frame .7: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .14
    frame .0: 0x00000001a1d44ad8 libsystem_pthread.dylib`start_wqthread
  thread .19, name = 'com.google.Maps.LabelingBehavior'
    frame .0: 0x00000001a1dfb5f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame .1: 0x00000001a1dfaa60 libsystem_kernel.dylib`mach_msg + 72
    frame .2: 0x00000001a1fa2068 CoreFoundation`__CFRunLoopServiceMachPort + 216
    frame .3: 0x00000001a1f9d188 CoreFoundation`__CFRunLoopRun + 1444
    frame .4: 0x00000001a1f9c8bc CoreFoundation`CFRunLoopRunSpecific + 464
    frame .5: 0x00000001a22dc994 Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 228
    frame .6: 0x00000001034b3a54 MyApp`-[GMSx_GTMSimpleWorkerThread main] + 184
    frame .7: 0x00000001a240d0b0 Foundation`__NSThread__start__ + 848
    frame .8: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
* thread .20, queue = 'org.webrtc.RTCDispatcherCaptureSession', stop reason = signal SIGABRT
  * frame .0: 0x00000001a1e1cebc libsystem_kernel.dylib`__pthread_kill + 8
    frame .1: 0x00000001a1d38790 libsystem_pthread.dylib`pthread_kill$VARIANT$mp + 112
    frame .2: 0x00000001a1c8c824 libsystem_c.dylib`abort + 100
    frame .3: 0x00000001a1de57d4 libc++abi.dylib`abort_message + 128
    frame .4: 0x00000001a1de59c4 libc++abi.dylib`demangling_terminate_handler() + 296
    frame .5: 0x00000001a1d4d358 libobjc.A.dylib`_objc_terminate() + 124
    frame .6: 0x00000001a1df2304 libc++abi.dylib`std::__terminate(void (*)()) + 16
    frame .7: 0x00000001a1df229c libc++abi.dylib`std::terminate() + 44
    frame .8: 0x00000001a1d4d2dc libobjc.A.dylib`objc_terminate + 12
    frame .9: 0x000000010c876c18 libdispatch.dylib`_dispatch_client_callout + 36
    frame .10: 0x000000010c87db74 libdispatch.dylib`_dispatch_lane_serial_drain + 744
    frame .11: 0x000000010c87e710 libdispatch.dylib`_dispatch_lane_invoke + 448
    frame .12: 0x000000010c889ae4 libdispatch.dylib`_dispatch_workloop_worker_thread + 1324
    frame .13: 0x00000001a1d41fa4 libsystem_pthread.dylib`_pthread_wqthread + 276
  thread .21, name = 'com.google.Maps.LabelingBehavior'
    frame .0: 0x00000001a1dfb5f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame .1: 0x00000001a1dfaa60 libsystem_kernel.dylib`mach_msg + 72
    frame .2: 0x00000001a1fa2068 CoreFoundation`__CFRunLoopServiceMachPort + 216
    frame .3: 0x00000001a1f9d188 CoreFoundation`__CFRunLoopRun + 1444
    frame .4: 0x00000001a1f9c8bc CoreFoundation`CFRunLoopRunSpecific + 464
    frame .5: 0x00000001a22dc994 Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 228
    frame .6: 0x00000001034b3a54 MyApp`-[GMSx_GTMSimpleWorkerThread main] + 184
    frame .7: 0x00000001a240d0b0 Foundation`__NSThread__start__ + 848
    frame .8: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .22, name = 'com.apple.CFStream.LegacyThread'
    frame .0: 0x00000001a1dfb5f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame .1: 0x00000001a1dfaa60 libsystem_kernel.dylib`mach_msg + 72
    frame .2: 0x00000001a1fa2068 CoreFoundation`__CFRunLoopServiceMachPort + 216
    frame .3: 0x00000001a1f9d188 CoreFoundation`__CFRunLoopRun + 1444
    frame .4: 0x00000001a1f9c8bc CoreFoundation`CFRunLoopRunSpecific + 464
    frame .5: 0x00000001a1fbad60 CoreFoundation`_legacyStreamRunLoop_workThread + 260
    frame .6: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .23, name = 'com.apple.CFSocket.private'
    frame .0: 0x00000001a1e1d148 libsystem_kernel.dylib`__select + 8
    frame .1: 0x00000001a1fafb3c CoreFoundation`__CFSocketManager + 636
    frame .2: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .24
    frame .0: 0x00000001a1d44ad8 libsystem_pthread.dylib`start_wqthread
  thread .25, name = 'com.facebook.react.JavaScript'
    frame .0: 0x00000001a1dfb5f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame .1: 0x00000001a1dfaa60 libsystem_kernel.dylib`mach_msg + 72
    frame .2: 0x00000001a1fa2068 CoreFoundation`__CFRunLoopServiceMachPort + 216
    frame .3: 0x00000001a1f9d188 CoreFoundation`__CFRunLoopRun + 1444
    frame .4: 0x00000001a1f9c8bc CoreFoundation`CFRunLoopRunSpecific + 464
    frame .5: 0x000000010c007d30 JitsiMeet`+[RCTCxxBridge runRunLoop] + 264
    frame .6: 0x00000001a240d0b0 Foundation`__NSThread__start__ + 848
    frame .7: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .26, name = 'JavaScriptCore bmalloc scavenger'
    frame .0: 0x00000001a1e1cc8c libsystem_kernel.dylib`__psynch_cvwait + 8
    frame .1: 0x00000001a1d3a204 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$mp + 684
    frame .2: 0x00000001a1e6e7a8 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
    frame .3: 0x00000001b0bfa3fc JavaScriptCore`void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 108
    frame .4: 0x00000001b0bfddcc JavaScriptCore`bmalloc::Scavenger::threadRunLoop() + 200
    frame .5: 0x00000001b0bfdab4 JavaScriptCore`bmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*) + 12
    frame .6: 0x00000001b0bfedc0 JavaScriptCore`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::Scavenger*), bmalloc::Scavenger*> >(void*) + 40
    frame .7: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .28, name = 'network_thread 0x0x124428590'
    frame .0: 0x00000001a1e1d148 libsystem_kernel.dylib`__select + 8
    frame .1: 0x000000010ae090c4 WebRTC`rtc::PhysicalSocketServer::WaitSelect(this=0x0000000283211c70, cmsWait=<unavailable>, process_io=true) at physical_socket_server.cc:1442:13 [opt]
    frame .2: 0x000000010adfbc44 WebRTC`rtc::MessageQueue::Get(this=0x0000000124428590, pmsg=0x000000016da9ef40, cmsWait=<unavailable>, process_io=<unavailable>) at message_queue.cc:329:17 [opt]
    frame .3: 0x000000010ae0f820 WebRTC`rtc::Thread::ProcessMessages(this=0x0000000124428590, cmsLoop=-1) at thread.cc:535:10 [opt]
    frame .4: 0x000000010ae0f6cc WebRTC`rtc::Thread::PreRun(pv=0x0000000280b4c7b0) at thread.cc:349:19 [opt]
    frame .5: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .29, name = 'worker_thread 0x0x12442b230'
    frame .0: 0x00000001a1e1cc8c libsystem_kernel.dylib`__psynch_cvwait + 8
    frame .1: 0x00000001a1d3a204 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$mp + 684
    frame .2: 0x000000010ad2d904 WebRTC`rtc::Event::Wait(this=<unavailable>, timeout_ts=const absl::optional<timespec> @ 0x000000016db2ad98)::$_0::operator()(absl::optional<timespec>) const at event.cc:165:17 [opt]
    frame .3: 0x000000010ad2d7d0 WebRTC`rtc::Event::Wait(this=0x0000000283b52a40, give_up_after_ms=<unavailable>, warn_after_ms=<unavailable>) at event.cc:0 [opt]
    frame .4: 0x000000010ae01a70 WebRTC`rtc::NullSocketServer::Wait(this=<unavailable>, cms=<unavailable>, process_io=<unavailable>) at null_socket_server.cc:23:10 [opt]
    frame .5: 0x000000010adfbc44 WebRTC`rtc::MessageQueue::Get(this=0x000000012442b230, pmsg=0x000000016db2af40, cmsWait=<unavailable>, process_io=<unavailable>) at message_queue.cc:329:17 [opt]
    frame .6: 0x000000010ae0f820 WebRTC`rtc::Thread::ProcessMessages(this=0x000000012442b230, cmsLoop=-1) at thread.cc:535:10 [opt]
    frame .7: 0x000000010ae0f6cc WebRTC`rtc::Thread::PreRun(pv=0x0000000280b4f5f0) at thread.cc:349:19 [opt]
    frame .8: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .30, name = 'signaling_thread 0x0x11046af70'
    frame .0: 0x00000001a1e1cc8c libsystem_kernel.dylib`__psynch_cvwait + 8
    frame .1: 0x00000001a1d3a204 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$mp + 684
    frame .2: 0x000000010ad2d904 WebRTC`rtc::Event::Wait(this=<unavailable>, timeout_ts=const absl::optional<timespec> @ 0x000000016dbb6d98)::$_0::operator()(absl::optional<timespec>) const at event.cc:165:17 [opt]
    frame .3: 0x000000010ad2d7d0 WebRTC`rtc::Event::Wait(this=0x0000000283b52650, give_up_after_ms=<unavailable>, warn_after_ms=<unavailable>) at event.cc:0 [opt]
    frame .4: 0x000000010ae01a70 WebRTC`rtc::NullSocketServer::Wait(this=<unavailable>, cms=<unavailable>, process_io=<unavailable>) at null_socket_server.cc:23:10 [opt]
    frame .5: 0x000000010adfbc44 WebRTC`rtc::MessageQueue::Get(this=0x000000011046af70, pmsg=0x000000016dbb6f40, cmsWait=<unavailable>, process_io=<unavailable>) at message_queue.cc:329:17 [opt]
    frame .6: 0x000000010ae0f820 WebRTC`rtc::Thread::ProcessMessages(this=0x000000011046af70, cmsLoop=-1) at thread.cc:535:10 [opt]
    frame .7: 0x000000010ae0f6cc WebRTC`rtc::Thread::PreRun(pv=0x0000000280b4f610) at thread.cc:349:19 [opt]
    frame .8: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .32, name = 'com.apple.coreaudio.AQClient'
    frame .0: 0x00000001a1dfb5f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame .1: 0x00000001a1dfaa60 libsystem_kernel.dylib`mach_msg + 72
    frame .2: 0x00000001a1fa2068 CoreFoundation`__CFRunLoopServiceMachPort + 216
    frame .3: 0x00000001a1f9d188 CoreFoundation`__CFRunLoopRun + 1444
    frame .4: 0x00000001a1f9c8bc CoreFoundation`CFRunLoopRunSpecific + 464
    frame .5: 0x00000001acfce380 AudioToolbox`GenericRunLoopThread::Entry(void*) + 156
    frame .6: 0x00000001ad08e4f8 libAudioToolboxUtility.dylib`CAPThread::Entry(CAPThread*) + 88
    frame .7: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .34, name = 'JSC Heap Collector Thread'
    frame .0: 0x00000001a1e1cc8c libsystem_kernel.dylib`__psynch_cvwait + 8
    frame .1: 0x00000001a1d3a204 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$mp + 684
    frame .2: 0x00000001b0bbeb6c JavaScriptCore`WTF::ThreadCondition::timedWait(WTF::Mutex&, WTF::WallTime) + 144
    frame .3: 0x00000001b0ba4a18 JavaScriptCore`WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2040
    frame .4: 0x00000001b0b7d2d4 JavaScriptCore`bool WTF::Condition::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 184
    frame .5: 0x00000001b0b7d65c JavaScriptCore`WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 216
    frame .6: 0x00000001b0bbc7a4 JavaScriptCore`WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 256
    frame .7: 0x00000001b0bbe314 JavaScriptCore`WTF::wtfThreadEntryPoint(void*) + 12
    frame .8: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .35, name = 'Heap Helper Thread'
    frame .0: 0x00000001a1e1cc8c libsystem_kernel.dylib`__psynch_cvwait + 8
    frame .1: 0x00000001a1d3a204 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$mp + 684
    frame .2: 0x00000001b0bbeb6c JavaScriptCore`WTF::ThreadCondition::timedWait(WTF::Mutex&, WTF::WallTime) + 144
    frame .3: 0x00000001b0ba4a18 JavaScriptCore`WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2040
    frame .4: 0x00000001b0b7d2d4 JavaScriptCore`bool WTF::Condition::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 184
    frame .5: 0x00000001b0b7d65c JavaScriptCore`WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 216
    frame .6: 0x00000001b0bbc7a4 JavaScriptCore`WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 256
    frame .7: 0x00000001b0bbe314 JavaScriptCore`WTF::wtfThreadEntryPoint(void*) + 12
    frame .8: 0x00000001a1d411ec libsystem_pthread.dylib`_pthread_start + 124
  thread .36
    frame .0: 0x00000001a1d44ad8 libsystem_pthread.dylib`start_wqthread
  thread .37
    frame .0: 0x00000001a1e1da74 libsystem_kernel.dylib`__workq_kernreturn + 8
  thread .38
    frame .0: 0x00000001a1d44ad8 libsystem_pthread.dylib`start_wqthread
  thread .39, queue = 'com.facebook.react.RNSoundQueue'
    frame .0: 0x00000001a1dfb5f4 libsystem_kernel.dylib`mach_msg_trap + 8
    frame .1: 0x00000001a1dfaa60 libsystem_kernel.dylib`mach_msg + 72
    frame .2: 0x00000001acfcefd8 AudioToolbox`AudioQueueStop + 532
    frame .3: 0x00000001ae9f0250 AVFAudio`AVAudioPlayerCpp::disposeQueue(bool) + 176
    frame .4: 0x00000001ae9f06e4 AVFAudio`AVAudioPlayerCpp::DoAction(unsigned int, unsigned long, void const*) + 696
    frame .5: 0x00000001ae9b8e64 AVFAudio`-[AVAudioPlayer stop] + 36
    frame .6: 0x000000010bfecaf8 JitsiMeet`-[RNSound release:] + 104
    frame .7: 0x00000001a202ad90 CoreFoundation`__invoking___ + 144
    frame .8: 0x00000001a1efabd0 CoreFoundation`-[NSInvocation invoke] + 300
    frame .9: 0x00000001a1efb7a8 CoreFoundation`-[NSInvocation invokeWithTarget:] + 76
    frame .10: 0x000000010c027ff8 JitsiMeet`-[RCTModuleMethod invokeWithBridge:module:arguments:] + 460
    frame .11: 0x000000010c02a108 JitsiMeet`facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&) + 244
    frame .12: 0x000000010c029e6c JitsiMeet`___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 88
    frame .13: 0x000000010c875828 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame .14: 0x000000010c876c04 libdispatch.dylib`_dispatch_client_callout + 16
    frame .15: 0x000000010c87db74 libdispatch.dylib`_dispatch_lane_serial_drain + 744
    frame .16: 0x000000010c87e710 libdispatch.dylib`_dispatch_lane_invoke + 448
    frame .17: 0x000000010c889ae4 libdispatch.dylib`_dispatch_workloop_worker_thread + 1324
    frame .18: 0x00000001a1d41fa4 libsystem_pthread.dylib`_pthread_wqthread + 276
  thread .40
    frame .0: 0x00000001a1d44ad8 libsystem_pthread.dylib`start_wqthread
  thread .41
    frame .0: 0x00000001a1d44ad8 libsystem_pthread.dylib`start_wqthread
  thread .42
    frame .0: 0x00000001a1d44ad8 libsystem_pthread.dylib`start_wqthread
`

# Environment details
---
JitsiMeet SDK 2.3.0
iOS 13.1.1

**Comment by saghul** [comment]
Hum, I haven't seen this one. Are you using H.264 by any chance?

**Comment by nasircsms** [comment]
> Hum, I haven't seen this one. Are you using H.264 by any chance?

Where can I confirm this setting ? Though I haven't changed anything for that.. whatever comes by default.

**Comment by saghul** [comment]
Then you are not. We just released a 2.3.1 SDK which fixes a few crashes on iOS, can you please give it a try?

**Comment by nasircsms** [comment]
> Then you are not. We just released a 2.3.1 SDK which fixes a few crashes on iOS, can you please give it a try?

sure, I'll get back to you..
Thanks

**Comment by nasircsms** [comment]
I compiled framework with the latest source from 'master' branch and the issue is still there. It still crashes once I hangup the call, with the same trace I mentioned above.

**Comment by nasircsms** [comment]
> How are you hanging up the call? Can you reproduce the crash with our sample applications here? https://github.com/jitsi/jitsi-meet-sdk-samples

Hangup is from JitsiView 'hangup' button from interface. 
I'll try the sample.

**Comment by nasircsms** [comment]
Samples use precompiled framework which I can't be used with Xcode 11 :worried: That's why I was compiling framework myself with Xcode 11 build tools. What other options I can try ?

**Comment by saghul** [comment]
What do you need from Xcode 11, just being able to run on an iOS 13 device? If so you can run Xcode 10 with this trick: https://gist.github.com/steipete/d9b44d8e9f341e81414e86d7ff8fb62d

**Comment by kharpodiya** [comment]
Same issue with me, when I build the SDK for score 11.

**Comment by saghul** [comment]
This should be fixed in master (just committed it). Can you please give it a test?

**Comment by kharpodiya** [comment]
> This should be fixed in master (just committed it). Can you please give i

> This should be fixed in master (just committed it). Can you please give it a test?

Sure, thanks..

**Comment by kharpodiya** [comment]
Now some times a black screen comes with the Error: "You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store."

**Comment by saghul** [comment]
The black screen is expected. When the call ends and there is no welcome page enabled that’s what you’ll get when the call ends.

As for the JS error, can you send the full backtrace?

The error is printed in the console, right?

**Comment by kharpodiya** [comment]
> The black screen is expected. When the call ends and there is no welcome page enabled that’s what you’ll get when the call ends.
> 
> As for the JS error, can you send the full backtrace?
> 
> The error is printed in the console, right?

i'm not sure may be it's  a react native error  something like this.
![Screenshot 2019-10-19 at 5 16 00 PM](https://user-images.githubusercontent.com/56601023/67144463-23ba3c00-f294-11e9-9894-8685da923e22.png)

**Comment by kharpodiya** [comment]
> The black screen is expected. When the call ends and there is no welcome page enabled that’s what you’ll get when the call ends.
> 
> As for the JS error, can you send the full backtrace?
> 
> The error is printed in the console, right?

The error not printed in the console. Some times when I cut the call a black view appears with these options " Dismiss, reload js ,... etc." And the error is on that black view in the red box

**Comment by saghul** [comment]
Oh, I see. Damn. Still I think there should be something useful in the Xcode console, can you please check?

Also, how easy is it to reproduce this for you? Where you in a call when it happened or alone? (I ask because I never ran into it while testing the fix for the native crash)

**Comment by kharpodiya** [comment]
> Oh, I see. Damn. Still I think there should be something useful in the Xcode console, can you please check?
> 
> Also, how easy is it to reproduce this for you? Where you in a call when it happened or alone? (I ask because I never ran into it while testing the fix for the native crash)

Sure , if I found the exact scenario then I will share.

**Comment by saghul** [comment]
Thank you!

**Comment by saghul** [comment]
iOS SDK 2.4.0 is out, with a fix for this.

**Comment by dhanashree27** [comment]
I am also facing same issue.

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'threading violation: expected the main thread'

for audio call it works fine but for video call getting above crash as soon as I start the call.

[JitsiMeetSDK] [VideoCaptureController] Capture will start

 *** Assertion failure in -[FBSSerialQueue assertOnQueue], /Library/Caches/com.apple.xbs/Sources/FrontBoardServices/FrontBoard-626.8/FrontBoardServices/FBSSerialQueue.m:98
