### ISSUE TITLE
iOS - changing Default_Server_URL breaks DOMINANT SPEAKER functionality.

### ISSUE THREAD

**Issue by bhavesh18** [jitsi/jitsi-meet#4961]
When I change Default_Server_URL it breaks the DOMINANT SPEAKER functionality however the same code works fine on android.

**Comment by saghul** [comment]
This is highly unlikely. Please paste the code changes you are making and the logs.

**Comment by bhavesh18** [comment]
![1](https://user-images.githubusercontent.com/22396203/71412220-bc917d00-2672-11ea-815f-c026d16a6dbe.png)
![2](https://user-images.githubusercontent.com/22396203/71412221-bc917d00-2672-11ea-843d-45410fe1075d.png)

**Comment by bhavesh18** [comment]
![Screenshot 2019-12-23 at 5 18 58 PM](https://user-images.githubusercontent.com/22396203/71412283-08dcbd00-2673-11ea-9aa4-a185c7f15820.png)

Logs (android)

**Comment by khateeb0** [comment]
working fine for android but dominant speaker changed listener is not working for ios.

**Comment by khateeb0** [comment]
@saghul  Any updates???

**Comment by saghul** [comment]
I have a suspicion this is related to datachannels breaking on iOS. Any chance you could try applying this patch and rebuilding the SDK? https://github.com/react-native-webrtc/react-native-webrtc/pull/726

**Comment by saghul** [comment]
This was fixed with the aforementioned PR.

**Comment by davenlin19** [comment]
I still have this problem. The dominant speaker detection works find on android but I can not see the blue icon on ios.
It is strange:
- If I use the server meet.jit.si, it works on ios and android
- If I use my own server, only works on android (I used https://github.com/skrafft/react-native-jitsi-meet). But if I try to use my own server with the ios jitsi meet app, it works.

Could you please give me a lead @saghul ? Thank you!

**Comment by saghul** [comment]
We don't maintain that package. It's usually several versions behind, so it's possible it doesn't include the necessary fix.
