### ISSUE TITLE
Make Jitsi widget responsive and UI looks well with tiny size

### ISSUE THREAD

**Issue by MurzNN** [jitsi/jitsi-meet#5416]
**Is your feature request related to a problem you are facing?**
In Riot.im messenger when users switch to other room, Jitsi widget are resized to tiny size in left panel, here is screenshot:
![image](https://user-images.githubusercontent.com/336662/77728877-82879c80-700e-11ea-8528-ab43f7cf5ad2.png)

In this mode there usability of widget is very poor.

**Describe the solution you'd like**
Will be good to make element sizes and padding smaller, for fit all Jitsi interface elements in small frame.

**Comment by dandv** [comment]
To start, how can the Jitsi iframe be made responsive, assuming control over the [iframe API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe)?

**Comment by MurzNN** [comment]
Oh no, bump!

**Comment by MurzNN** [comment]
Bump!

**Comment by HansJK** [comment]
> To start, how can the Jitsi iframe be made responsive, assuming control over the [iframe API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe)?

Well video calling have worked fine on phones for years, you can take inspiration from that.

**Comment by saghul** [comment]
We have already implemented a responsive UI and continue to make improvements in this area. See the Mattermost integration as an example.

**Comment by MurzNN** [comment]
Glad to hear than you implemented some improvements responsive UI! But current UI still have some problems with tiny widget size. For example here is screenshot of current Jitsi version with 180x200px widget and it looks not so well: 
![image](https://user-images.githubusercontent.com/336662/111161677-76dd0f00-85ac-11eb-9de7-55359480f66a.png)

Or for make it looks better, we need to pass some arguments to widget? Can you please share here the screenshot of tiny-sized Jitsi in Mattermost integration to lookup? Thanks!

**Comment by saghul** [comment]
Yes, individual issues would be better. But make sure you test latest unstable / master first, we have redesigned the toolbar and it no longer looks like in the screenshot.

**Comment by amreshparida** [comment]
Use the below css

 <style>
     #meet {
	padding-bottom: 10.25%; 
}
#meet iframe {
	position: absolute;
	top: 0;
	left: 0;
	width: 100% !important;
	height: 100% !important;
}
 </style>

<div id="meet"></div> /* div where jitsi iframe will be loaded */
