### ISSUE TITLE
Failed to create EGL context

### ISSUE THREAD

**Issue by pandyin** [jitsi/jitsi-meet#6121]
I was on Android Jitsi meet v 20.2.1 there were about 40 people on the call everyone had theirs camera turned on (web, ios and Android) everything went smoothly until my 4g went down and I got kicked out of the call then after I got my 4g back I tried to reconnect to the call and the app crashed

```
2020-04-17 12:32:34.381 18196-18196/? E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.RuntimeException: java.lang.RuntimeException: Failed to create EGL context: 0x3003
        at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:278)
        at org.webrtc.EglBase14Impl.<init>(EglBase14Impl.java:76)
        at org.webrtc.EglBase$-CC.createEgl14(EglBase.java:160)
        at org.webrtc.EglBase$-CC.create(EglBase.java:103)
        at org.webrtc.EglRenderer.lambda$init$0(EglRenderer.java:233)
        at org.webrtc.-$$Lambda$EglRenderer$A5MPsBufyTiKpmjvPS46Dr9iaHs.run(Unknown Source:6)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
        at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at org.webrtc.EglRenderer$HandlerWithExceptionCallback.dispatchMessage(EglRenderer.java:97)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:184)
        at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:196)
        at org.webrtc.EglRenderer.init(EglRenderer.java:224)
        at org.webrtc.EglRenderer.init(EglRenderer.java:251)
        at org.webrtc.SurfaceEglRenderer.init(SurfaceEglRenderer.java:61)
        at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:87)
        at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:71)
        at com.oney.WebRTCModule.j.f(WebRTCView.java:605)
        at com.oney.WebRTCModule.j.onAttachedToWindow(WebRTCView.java:260)
        at android.view.View.dispatchAttachedToWindow(View.java:20105)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3430)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5193)
        at android.view.ViewGroup.addView(ViewGroup.java:4979)
        at com.facebook.react.views.view.f.addView(ReactViewGroup.java:453)
        at android.view.ViewGroup.addView(ViewGroup.java:4919)
        at com.facebook.react.views.view.ReactViewManager.addView(ReactViewManager.java:355)
        at com.facebook.react.views.view.ReactViewManager.addView(ReactViewManager.java:37)
        at com.facebook.react.uimanager.j.a(NativeViewHierarchyManager.java:512)
        at com.facebook.react.uimanager.aq$j.a(UIViewOperationQueue.java:205)
        at com.facebook.react.uimanager.aq$1.run(UIViewOperationQueue.java:779)
        at com.facebook.react.uimanager.aq.i(UIViewOperationQueue.java:888)
        at com.facebook.react.uimanager.aq.h(UIViewOperationQueue.java:42)
        at com.facebook.react.uimanager.aq$g.a(UIViewOperationQueue.java:948)
        at com.facebook.react.uimanager.c.b(GuardedFrameCallback.java:28)
        at com.facebook.react.modules.core.e$b.b(ReactChoreographer.java:174)
        at com.facebook.react.modules.core.a$a$1.doFrame(ChoreographerCompat.java:84)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:722)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.RuntimeException: Failed to create EGL context: 0x3003
        at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:278)
        at org.webrtc.EglBase14Impl.<init>(EglBase14Impl.java:76)
        at org.webrtc.EglBase$-CC.createEgl14(EglBase.java:160)
        at org.webrtc.EglBase$-CC.create(EglBase.java:103)
        at org.webrtc.EglRenderer.lambda$init$0(EglRenderer.java:233)
        at org.webrtc.-$$Lambda$EglRenderer$A5MPsBufyTiKpmjvPS46Dr9iaHs.run(Unknown Source:6)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
    	at org.webrtc.ThreadUtils$4.call(ThreadUt
```

**Comment by ijoshivaibhav** [comment]
I have implemented latest sdk and on some devices like Xiomi,Vivo, with Android 6,8,10 app crashes.
Caused by java.lang.RuntimeException: Failed to create EGL context: 0x3003
       at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:278)
       at org.webrtc.EglBase14Impl.<init>(EglBase14Impl.java:76)
       at org.webrtc.EglBase$-CC.createEgl14(EglBase.java:160)
       at org.webrtc.EglBase$-CC.create(EglBase.java:103)
       at org.webrtc.EglRenderer.lambda$init$0$EglRenderer(EglRenderer.java:233)
       at org.webrtc.-$$Lambda$EglRenderer$A5MPsBufyTiKpmjvPS46Dr9iaHs.run(:6)
       at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
       at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
       at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at org.webrtc.EglRenderer$HandlerWithExceptionCallback.dispatchMessage(EglRenderer.java:97)
       at android.os.Looper.loop(Looper.java:201)
       at android.os.HandlerThread.run(HandlerThread.java:65)

any update on this?

**Comment by saghul** [comment]
We've seen this too. There seems to be some limit on the number of EGL contexts you can create until you run out. Unfortunately figuring the number out is virtually impossible. If anyone has an idea on how to tackle this it would be much appreciated.

**Comment by LuxsThor** [comment]
issue still persist on some devices. has there been any news?

java.lang.RuntimeException: Unable to find any matching EGL config
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2921)
	at android.app.ActivityThread.-wrap4(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1446)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.RuntimeException: Unable to find any matching EGL config
	at org.webrtc.EglBase14Impl.getEglConfig(SourceFile:7)
	at org.webrtc.EglBase14Impl.<init>(SourceFile:4)
	at Era.b(EglBase.java:2)
	at Era.a(EglBase.java:2)
	at Era.b(EglBase.java:1)
	at ch.threema.app.voip.services.J.<init>(SourceFile:3)
	at ch.threema.app.voip.services.V.c(SourceFile:12)
	at ch.threema.app.voip.services.VoipCallService.onCreate(SourceFile:10)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)

**Comment by 1Ajay** [comment]
2020-12-14 20:38:49.479 30821-30821/com.nouveaulabs.dolphinvc E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.RuntimeException: java.lang.RuntimeException: Failed to create EGL context: 0x3003
        at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:278)
        at org.webrtc.EglBase14Impl.<init>(EglBase14Impl.java:76)
        at org.webrtc.EglBase$-CC.createEgl14(EglBase.java:160)
        at org.webrtc.EglBase$-CC.create(EglBase.java:103)
        at org.webrtc.EglRenderer.lambda$init$0$EglRenderer(EglRenderer.java:233)
        at org.webrtc.-$$Lambda$EglRenderer$miQc1-F9Qqw0EkFhtMh5sNQ-7uU.run(Unknown Source:6)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
        at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at org.webrtc.EglRenderer$HandlerWithExceptionCallback.dispatchMessage(EglRenderer.java:97)
        at android.os.Looper.loop(Looper.java:228)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:184)
        at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:196)
        at org.webrtc.EglRenderer.init(EglRenderer.java:224)
        at org.webrtc.EglRenderer.init(EglRenderer.java:251)
        at org.webrtc.SurfaceEglRenderer.init(SurfaceEglRenderer.java:61)
        at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:87)
        at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:71)
        at com.oney.WebRTCModule.WebRTCView.tryAddRendererToVideoTrack(WebRTCView.java:605)
        at com.oney.WebRTCModule.WebRTCView.onAttachedToWindow(WebRTCView.java:260)
        at android.view.View.dispatchAttachedToWindow(View.java:19798)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3442)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5245)
        at android.view.ViewGroup.addView(ViewGroup.java:5023)
        at com.facebook.react.views.view.ReactViewGroup.addView(ReactViewGroup.java:465)
        at android.view.ViewGroup.addView(ViewGroup.java:4963)
        at com.facebook.react.views.view.ReactClippingViewManager.addView(ReactClippingViewManager.java:38)
        at com.facebook.react.views.view.ReactClippingViewManager.addView(ReactClippingViewManager.java:19)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:517)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:206)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:792)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:903)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:43)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:963)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1083)
        at android.view.Choreographer.doCallbacks(Choreographer.java:908)
        at android.view.Choreographer.doFrame(Choreographer.java:831)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1070)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:228)
        at android.app.ActivityThread.main(ActivityThread.java:7782)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
     Caused by: java.lang.RuntimeException: Failed to create EGL context: 0x3003
    	at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.j

Any Solutions?
