### ISSUE TITLE
Audio not picked up on iPad for users who rejoin a conference

### ISSUE THREAD

**Issue by Rusta** [jitsi/jitsi-meet#6426]
## Description
The audio of other users who rejoin a conference is not picked up by safari on iPad

## Current behavior
When a user returns to a conference their audio track is not picked up by existing iPad users on the conference (but their video track can be seen)

## Expected Behavior
When a user returns to a conference both their audio and video tracks are picked up by existing iPad users on the conference

## Possible Solution
Not sure. Refreshing the browser/session (i.e. leaving and re-entering the room) for the iPad user "fixes" the issue for them (in that they can then hear and see everyone on the call when they return) but if there are other iPad users on the call it would start a chain effect as the audio of the iPad user who just returned would now no longer be heard by other iPad users on the call

## Steps to reproduce
1. Start a new conference on https://meet.jit.si
2. Join conference with user 1 on iPad
3. Join conference with user 2 on any other device
4. User 2 leaves the conference (goes to another web page OR refreshes their browser)
5. User 2 returns to the same conference
6. User 1 (on iPad) will be able to see the video of the returning user 2 but not hear their audio

# Environment details
 iPad Pro (iOS 13.4.1) using safari and the public https://meet.jit.si website

**Comment by hariprakashnagar** [comment]
I am facing the same problem.

**Comment by saghul** [comment]
@jallamsetty1 when did we deploy the latest changes for Safari on iOS?

**Comment by jallamsetty1** [comment]
Yes, this should have been fixed on https://meet.jit.si now. The fix was deployed about 7-10 days back.

**Comment by hariprakashnagar** [comment]
I have tested on https://meet.jit.si issue but still facing the same issue.  iPad mic is not working. The camera is working. And, on the iPad, I can view and hear.

**Comment by hariprakashnagar** [comment]
> Yes, this should have been fixed on https://meet.jit.si now. The fix was deployed about 7-10 days back.

I have tested on https://meet.jit.si issue but still facing the same issue in the iPad safari. iPad mic is not working. The camera is working. And, on the iPad, I can view and hear.

**Comment by jallamsetty1** [comment]
> > Yes, this should have been fixed on https://meet.jit.si now. The fix was deployed about 7-10 days back.
> 
> I have tested on https://meet.jit.si issue but still facing the same issue in the iPad safari. iPad mic is not working. The camera is working. And, on the iPad, I can view and hear.

Do you see any errors in the logs ? Also what version of iOS are you running on the iPad ?

**Comment by hariprakashnagar** [comment]
Our iPad is Version 13.4.1.

**Comment by jallamsetty1** [comment]
> Our iPad is Version 13.4.1.

Will you be able to provide the console logs ?

**Comment by hariprakashnagar** [comment]
[iCareMeeting_iPad_Debugger_Log.txt](https://github.com/jitsi/jitsi-meet/files/4647989/iCareMeeting_iPad_Debugger_Log.txt)
[iCareMeeting_iPad_Debugger_Error.txt](https://github.com/jitsi/jitsi-meet/files/4647990/iCareMeeting_iPad_Debugger_Error.txt)
[iCareMeeting_iPad_Debugger_Warning.txt](https://github.com/jitsi/jitsi-meet/files/4647991/iCareMeeting_iPad_Debugger_Warning.txt)

Please find the attached logs

**Comment by hariprakashnagar** [comment]
[iPad_Debugger_Log.txt](https://github.com/jitsi/jitsi-meet/files/4647997/iPad_Debugger_Log.txt)
[iPad_Debugger_Error.txt](https://github.com/jitsi/jitsi-meet/files/4647999/iPad_Debugger_Error.txt)
[iPad_Debugger_Warning.txt](https://github.com/jitsi/jitsi-meet/files/4648000/iPad_Debugger_Warning.txt)

Please find the log files

**Comment by jallamsetty1** [comment]
> [iPad_Debugger_Log.txt](https://github.com/jitsi/jitsi-meet/files/4647997/iPad_Debugger_Log.txt)
> [iPad_Debugger_Error.txt](https://github.com/jitsi/jitsi-meet/files/4647999/iPad_Debugger_Error.txt)
> [iPad_Debugger_Warning.txt](https://github.com/jitsi/jitsi-meet/files/4648000/iPad_Debugger_Warning.txt)
> 
> Please find the log files

The logs are for your deployment and seem to report an error that we already fixed on meet.jit.si.

**Comment by hariprakashnagar** [comment]
> > [iPad_Debugger_Log.txt](https://github.com/jitsi/jitsi-meet/files/4647997/iPad_Debugger_Log.txt)
> > [iPad_Debugger_Error.txt](https://github.com/jitsi/jitsi-meet/files/4647999/iPad_Debugger_Error.txt)
> > [iPad_Debugger_Warning.txt](https://github.com/jitsi/jitsi-meet/files/4648000/iPad_Debugger_Warning.txt)
> > Please find the log files
> 
> The logs are for your deployment and seem to report an error that we already fixed on meet.jit.si.

We have tested on both our development server and meet.jit.si.

**Comment by hariprakashnagar** [comment]
@jallamsetty1 when we expect the update on iPad audio issue.

**Comment by jallamsetty1** [comment]
> @jallamsetty1 when we expect the update on iPad audio issue.

We have fixed the audio issue and the fix is available in the nightly builds.

**Comment by hariprakashnagar** [comment]
> > @jallamsetty1 when we expect the update on iPad audio issue.
> 
> We have fixed the audio issue and the fix is available in the nightly builds.

Where we test the fix.

**Comment by saghul** [comment]
You can test it on alpha.jitsi.net

**Comment by jallamsetty1** [comment]
alpha is broken for Safari because of the callstats issue, can you please try it on https.beta.meet.jit.si ?

**Comment by hariprakashnagar** [comment]
> alpha is broken for Safari because of the callstats issue, can you please try it on https://beta.meet.jit.si ?

Thank you. It's working on the iPad.  When jitsi team planing to release this fix.

**Comment by jallamsetty1** [comment]
> > alpha is broken for Safari because of the callstats issue, can you please try it on https://beta.meet.jit.si ?
> 
> Thank you. It's working on the iPad. When jitsi team planing to release this fix.

I am not sure yet when the next release will be, I can update here when that happens.

**Comment by jallamsetty1** [comment]
@hariprakashnagar, this fix got deployed on https://meet.jit.si today. Please note that it hasn't been pushed to stable deb packages yet, still available only in the nightly builds.
