### ISSUE TITLE
iOS Client does not leave Meeting when closing App

### ISSUE THREAD

**Issue by fritzfr** [jitsi/jitsi-meet#6665]
## Description
When in a meeting using the iOS app, and then closing the iOS app completely (by swiping up on the iPhone into "app switch mode" and then swiping up the app to close it, the client stays in the meeting.

## Current behavior
See above.

## Expected Behavior
The client should disconnect from the meeting upon closing of the app.

## Possible Solution
I realize, that the App is react native based, and it seems rather difficult to detect closing of the app within javascript through react native. This might have to be implemented natively.

## Steps to reproduce
1. Join a meeting with the iOS app
2. Join the same meeting on Desktop/Browser to see the the iOS client
3. Close the iOS App
4. The user remains in the Meeting

# Environment details
Current iOS App, 20.2.3.

**Comment by saghul** [comment]
To clarify, what you see in the browser is a frozen tile, right? A "ghost" as we call it, which vanishes in about 60 seconds, right?

**Comment by fritzfr** [comment]
@saghul Yes, true. From the connection stats I can see that the connection is lost. Why the 60 seconds? Could you point me to the setting, where these 60 seconds are set?

**Comment by saghul** [comment]
The 60 seconds allow for participants to return after a brief network fluke. I think we can do better in this case though. When you swipe it out, appWillTerminate will get called and we have ~5 seconds to do stuff. That should be enough to trigger leaving a meeting.

**Comment by fritzfr** [comment]
@saghul Maybe I'm missing something but I implemented it exactly like you, it doesn't seem to do much though. There is still a 5-15 second delay after app termination and the participant actually disappearing.

**Comment by kishanitechnotion** [comment]
I am also facing this exact issue. I guess applicationWillTerminate() is not being called because app is not always terminated when user swipes out app from switcher (in cases where app supports background execution).

**Comment by ngdlmk** [comment]
This issue still exist for android android app when you terminate the app leave method is working and leaving to conference but on ios when you terminte the still remain on conference. I got log applicationWillTerminate() method fired and this method contain leave() method but it is not working.

**Comment by amjadislam** [comment]
@saghul can you help me, please. Thanks
This issue still exists and the most interesting thing is if I download the app from the Apple AppStore it working fine. on killing app user disappears instantly but when I download the latest code and compile and kill app it shows ghost user for a minute and vanishes after 1 minute.
