### ISSUE TITLE
Xcode 11: Unable to open file (in target "JitsiMeet" in project "sdk")

### ISSUE THREAD

**Issue by KiranJasvanee** [jitsi/jitsi-meet#6866]
Jitsi-meet working cool using Cocoapods. but when I tried to download the project and installed react-native and project node_modules. now I'm trying to open this project but I'm constantly receiving the following error. 

Unable to open file (in target "JitsiMeet" in project "sdk")

![Screenshot 2020-05-26 at 12 56 08 PM](https://user-images.githubusercontent.com/6015870/82872174-49a56e80-9f50-11ea-8812-cac7f8896853.png)

Sometimes it also throws - 
~/React-Native/jitsi-meet-ios-sdk-2.8.1/ios/Pods/Target Support Files/Pods-jitsi-meet/Pods-jitsi-meet.debug.xcconfig: unable to open file (in target "jitsi-meet" in project "app")

**Comment by saghul** [comment]
What exact steps did you follow?

Did you open the xcodeproj or the xcworkspace file?

**Comment by KiranJasvanee** [comment]
@saghul Thanks for quick reply. I tried to open xcworkspace file

**Comment by saghul** [comment]
Ah wait. You need to `pod install` after `npm install`

**Comment by KiranJasvanee** [comment]
@saghul Its resolved now. thanks for helping. I'm closing this issue.

**Comment by Saurabh-WowLabz-Kataria** [comment]
@KiranJasvanee , hey I was facing the same issue, I did pod install and the error still persists. Anything else you did to solve that issue?

**Comment by saghul** [comment]
Xcode 11 is no longer supported, you need to use Xcode 12.

**Comment by Saurabh-WowLabz-Kataria** [comment]
I am using Xcode Version 12.3 (12C33).
