### ISSUE TITLE
Safari 13.1 on macOS Mojave 10.14.6 : Failed to access your camera (no video)

### ISSUE THREAD

**Issue by Ribero** [jitsi/jitsi-meet#6872]
### Description: No video when using jitsi-meet web using Safari on macOS. 
Jitsi does not ask for camera access (it does for audio mic).

Display error message : 

Failed to access your camera
Your camera does not support required video resolution.

tested on: 

- https://meet.jit.si/Safari_Camera_Issue
- iMac and MacBook Pro internal webcam
- macOS Mojave 10.14.6 (18G5033)
- Safari Version 13.1 (14609.1.20.111.8) and Version 13.1.1 (14609.2.9.1.3)

### Steps to reproduce:

1. launch Safari
2. go to https://meet.jit.si/Safari_Camera_Issue
3. try to activate video

### Expected behavior:

- Safari should ask user for permission to use the camera (if not already granted in site pref)
- Internal default web cam should switch on and display user video feedback.

### Actual behavior:

- Safari does not ask permission to access camera
- Camera does not switch on
- Camera does not display any picture
- Error message is thrown : "_Failed to access your camera. Your camera does not support required video resolution._"

### Server information:

- Jitsi Meet version: ???
- Operating System: online

### Client information:

- Browser / app version: Safari Version 13.1 (14609.1.20.111.8) and Version 13.1.1 (14609.2.9.1.3)
- Operating System: macOS 10.14.6 (18G4032)
- iMac (Retina 4K, 21.5-inch, 2017) internal 720p capable webcam 
- MacBook Pro (Retina, mid-2012) internal 720p capable webcam 

Also occurs with:

- macOS 10.13.6 (17G66), Safari 13.0.4 (13608.4.9.1.4) + iSight
- Mac Pro (early 2008), external Firewire iSight 480p capable webcam 

### Additional information:

Seems very similar to issue #2000 which is marked as closed/fixed so it could be a new one.
Probably related with Web kit issue: https://bugs.webkit.org/show_bug.cgi?id=210932

**Comment by saghul** [comment]
@jallamsetty1

**Comment by awlx** [comment]
It works on macOS Catalina 10.15.4 with Safari 13.1 without a problem :).

**Comment by jallamsetty1** [comment]
@Ribero, Can you please check if this is the same issue as https://bugs.webkit.org/show_bug.cgi?id=210932 ? This seems to happen on iMacs and older models of MBPs. 

Can you also please run this in the browser console to check what are the min and max values for height/width as reported by the getCapabilities() method.

```
(async () => {
  try {
    const filter = ({width, height}) => ({width, height});
    const stream = await navigator.mediaDevices.getUserMedia({video:{}});
    const [track] = stream.getVideoTracks();
    console.log(`Capabilities: ${JSON.stringify(filter(track.getCapabilities()), null, 2)}`);
    console.log(`Settings: ${JSON.stringify(filter(track.getSettings()), null, 2)}`);
  } catch(e) {
    console.log(e);
  }
})();
```

**Comment by Ribero** [comment]
Hi @jallamsetty1 !

I just updated safari today to Version 13.1.1 (14609.2.9.1.3) on macOS 10.14.6 (18G5033) (Security update from Apple today). I still have the problem with the camera not being correctly managed (same error message).

I tried your suggestion in Safari console and found that I get a request from Safari to allow camera access (which I do net get using jitsi), then this result:

<img width="705" alt="image" src="https://user-images.githubusercontent.com/2266264/83044971-39bb8680-a045-11ea-873c-672df9dce709.png">

I encounter the same issue on multiple Mac:

- iMac (Retina 4K, 21.5-inch, 2017), macOS 10.14.6 / Safari 13.1 and 13.1.1 -> not that old 😉 !
- MacBook Pro (Retina, mid-2012), macOS 10.14.6 / Safari 13.1 and 13.1.1
- Mac Pro (beginning 2008), macOS 10.13.6 (17G66), Safari 13.0.4 (13608.4.9.1.4) -> yes, very old 😄 !

**Comment by jallamsetty1** [comment]
> Hi @jallamsetty1 !
> 
> I just updated safari today to Version 13.1.1 (14609.2.9.1.3) on macOS 10.14.6 (18G5033) (Security update from Apple today). I still have the problem with the camera not being correctly managed (same error message).
> 
> I tried your suggestion in Safari console and found that I get a request from Safari to allow camera access (which I do not get when using jitsi), then this result:
> 
> <img alt="image" width="705" src="https://user-images.githubusercontent.com/2266264/83044971-39bb8680-a045-11ea-873c-672df9dce709.png">
> 
> I encounter the same issue on multiple Mac:
> 
> * iMac (Retina 4K, 21.5-inch, 2017), macOS 10.14.6 / Safari 13.1 and 13.1.1 -> not that old 😉 !
> * MacBook Pro (Retina, mid-2012), macOS 10.14.6 / Safari 13.1 and 13.1.1
> * Mac Pro (beginning 2008), macOS 10.13.6 (17G66), Safari 13.0.4 (13608.4.9.1.4) -> yes, very old 😄 !
> 
> I also tried other "jitsi like" solutions that worked with the camera on the very same Macs and Safari version without any specific extension.

Thanks for checking, clearly the camera on your machines supports resolutions upto 720p but Safari 13 doesn't seem to be returning a stream when those constraints are passed when requesting for a video stream. You get the request in this case because we are passing no constraints. This is a safari webkit bug for sure. Can you please let us know what other "jitsi like" solutions that you have tried and seem to be working on these machines ?

**Comment by Ribero** [comment]
The latest I tried is Big Blue Button (https://sourceforge.net/projects/bigbluebutton/)
Their live demo server is not available anymore but you can try a free instantiation made by a local Internet Provider here : https://ensemble-bbb.scaleway.com (sorry it's in french but a short user guide in english is available [here](https://www.scaleway.com/en/docs/scaleway-videoconferencing-powered-by-bigbluebutton/)).

**Comment by jallamsetty1** [comment]
> The latest I tried is Big Blue Button (https://sourceforge.net/projects/bigbluebutton/)
> Their live demo server is not available anymore but you can try a free instantiation made by a local Internet Provider here : https://ensemble-bbb.scaleway.com (sorry it's in french but a short user guide in english is available [here](https://www.scaleway.com/en/docs/scaleway-videoconferencing-powered-by-bigbluebutton/)).

Thank you, will check it out if possible.
> 
> I also tried this successfully : https://webrtc.github.io/samples/src/content/devices/input-output/ it's not a real application but it works for detecting the camera
Yes, the sample doesn't pass any constraints so the camera will be detected.

Can you please try this and let me know if you get the permission request from the browser and if so what is the output you get on the browser console, thanks !

```
(async () => {
  try {
    const filter = ({width, height}) => ({width, height});
    const stream = await navigator.mediaDevices.getUserMedia({video: { height: { ideal: 720 }}});
    const [track] = stream.getVideoTracks();
    console.log(`Capabilities: ${JSON.stringify(filter(track.getCapabilities()), null, 2)}`);
    console.log(`Settings: ${JSON.stringify(filter(track.getSettings()), null, 2)}`);
  } catch(e) {
    console.log(e);
  }
})();

```

**Comment by 532910** [comment]
One of my peers gets the same error:
```
Failed to access your camera
Your camera does not support required video resolution.
```

Safari 13.1 (15609.1.20.111.8), macOS Catalina 10.15.4, iMac (Retina 5K, 27-inch, 2017) (integrated webcam)

![image](https://user-images.githubusercontent.com/14617699/83271911-28a08000-a1d3-11ea-844b-59f75d9ba7d3.png)

**Comment by Ribero** [comment]
> > The latest I tried is Big Blue Button (https://sourceforge.net/projects/bigbluebutton/)
> > Their live demo server is not available anymore but you can try a free instantiation made by a local Internet Provider here : https://ensemble-bbb.scaleway.com (sorry it's in french but a short user guide in english is available [here](https://www.scaleway.com/en/docs/scaleway-videoconferencing-powered-by-bigbluebutton/)).
> 
> Thank you, will check it out if possible.
> 
> > I also tried this successfully : https://webrtc.github.io/samples/src/content/devices/input-output/ it's not a real application but it works for detecting the camera
> > Yes, the sample doesn't pass any constraints so the camera will be detected.
> 
> Can you please try this and let me know if you get the permission request from the browser and if so what is the output you get on the browser console, thanks !
> 
> ```
> (async () => {
>   try {
>     const filter = ({width, height}) => ({width, height});
>     const stream = await navigator.mediaDevices.getUserMedia({video: { height: { ideal: 720 }}});
>     const [track] = stream.getVideoTracks();
>     console.log(`Capabilities: ${JSON.stringify(filter(track.getCapabilities()), null, 2)}`);
>     console.log(`Settings: ${JSON.stringify(filter(track.getSettings()), null, 2)}`);
>   } catch(e) {
>     console.log(e);
>   }
> })();
> ```

iMac:
<img width="672" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/2266264/83280639-41129980-a1d7-11ea-8f55-98d7076caf46.png">

MacBookPro:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/2266264/83280144-84b8d380-a1d6-11ea-84ac-0d8ec488b218.png">

**Comment by Ribero** [comment]
I have done a complementary test today on the latest version of Safari running on Catalina (MacBook Air of a friend) and it has no issue.

It seems that the common point of all macOS computers / Safari that are falling to use the camera is probably macOS Mojave in conjunction with Safari 13.x.

**Comment by jallamsetty1** [comment]
> I have done a complementary test today on the latest version of Safari running on Catalina (MacBook Air of a friend) and it has no issue.
> 
> It seems that the common point of all macOS computers / Safari that are falling to use the camera is probably macOS Mojave in conjunction with Safari 13.x.

Yes that appears to be the case and this is the safari bug for this issue -  https://bugs.webkit.org/show_bug.cgi?id=210932. Can you please update the bug and mention that you see the issue as well and list your configuration there ? I will try a workaround by not passing the min/max values in the constraints and see if that works. Thank you for all your help !

**Comment by Ribero** [comment]
> Yes that appears to be the case and this is the safari bug for this issue - https://bugs.webkit.org/show_bug.cgi?id=210932. Can you please update the bug and mention that you see the issue as well and list your configuration there ? I will try a workaround by not passing the min/max values in the constraints and see if that works. Thank you for all your help !

done : https://bugs.webkit.org/show_bug.cgi?id=210932#c25

**Comment by adeel-raza** [comment]
I have tried it on Chorme and Safari both and it still does not work and shows the same error. “failed to access the camera”
MacOS Sierra version: 10.12.6
Safari version: 12.11

This is the error in the console.
```
Logger.js:154 2020-06-12T10:12:39.798Z [features/base/tracks] Failed to create local tracks 
["video"] 
s {gum: {…}, name: "gum.not_found", message: "Requested device(s) was/were not found: video", stack: "Error↵    at new s (https://web-cdn.jitsi.net/meet…833/libs/lib-jitsi-meet.min.js?v=4127.780:1:92370"}
gum: {error: DOMException: Requested device not found, constraints: {…}, devices: Array(1)}
message: "Requested device(s) was/were not found: video"
name: "gum.not_found"
stack: "Error↵    at new s (https://web-cdn.jitsi.net/meetjitsi_4180.833/libs/lib-jitsi-meet.min.js?v=4127.780:1:113699)↵    at https://web-cdn.jitsi.net/meetjitsi_4180.833/libs/lib-jitsi-meet.min.js?v=4127.780:1:92370"
_proto_: Error
```

**Comment by jallamsetty1** [comment]
> I have tried it on Chorme and Safari both and it still does not work and shows the same error. “failed to access the camera”
> MacOS Sierra version: 10.12.6
> Safari version: 12.11
> 
> This is the error in the console.
> 
> ```
> Logger.js:154 2020-06-12T10:12:39.798Z [features/base/tracks] Failed to create local tracks 
> ["video"] 
> s {gum: {…}, name: "gum.not_found", message: "Requested device(s) was/were not found: video", stack: "Error↵    at new s (https://web-cdn.jitsi.net/meet…833/libs/lib-jitsi-meet.min.js?v=4127.780:1:92370"}
> gum: {error: DOMException: Requested device not found, constraints: {…}, devices: Array(1)}
> message: "Requested device(s) was/were not found: video"
> name: "gum.not_found"
> stack: "Error↵    at new s (https://web-cdn.jitsi.net/meetjitsi_4180.833/libs/lib-jitsi-meet.min.js?v=4127.780:1:113699)↵    at https://web-cdn.jitsi.net/meetjitsi_4180.833/libs/lib-jitsi-meet.min.js?v=4127.780:1:92370"
> _proto_: Error
> ```

Can you please check if you have correct permissions for the browsers under System Preference -> Security & Privacy -> Privacy ? Please ensure that the both the browsers have permissions for camera, microphone and screen recording.

**Comment by jallamsetty1** [comment]
> > Yes that appears to be the case and this is the safari bug for this issue - https://bugs.webkit.org/show_bug.cgi?id=210932. Can you please update the bug and mention that you see the issue as well and list your configuration there ? I will try a workaround by not passing the min/max values in the constraints and see if that works. Thank you for all your help !
> 
> done : https://bugs.webkit.org/show_bug.cgi?id=210932#c25

@Ribero, Can you please try https://jaya.jitsi.net to see if you can get the camera on your macOS computers. Hopefully this should work until we can get the apple folks to fix the bug in webkit.

**Comment by Ribero** [comment]
I tired and it works with Macbook Pro and iMac and also an iPhone (using safari). All devices are requesting access to camera and mic.

On both Mac I found that the "settings"-> "preview" does not work:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/2266264/84818279-8d9f0700-b016-11ea-8e4c-61c4d2c81bcd.png">

On the iPhone the preview from the setting panel works as expected.

I cannot test the old MacPro/iSight now.

**Comment by jallamsetty1** [comment]
> @jallamsetty1 I tired and it works with Macbook Pro and iMac and also an iPhone (using safari). All devices are requesting access to camera and mic.
> 
> On both Mac I found that the "settings"-> "preview" does not work (but the camera/mic works fine everywhere else and more importantly, works perfectly during a video conference) :
> 
> <img alt="image" width="600" src="https://user-images.githubusercontent.com/2266264/84818279-8d9f0700-b016-11ea-8e4c-61c4d2c81bcd.png">
> 
> On the iPhone the preview from the settings panel works as expected (with a working preview and no message stating camera access not granted).
> 
> I cannot test the old MacPro/iSight now. **[Update] : works also on this setup. (with the same issue than other macs in settings/preview)**
> 
> So it seems we have a working solution here ! Thanks !
> 
> Do you plan to push it to https://meet.jit.si/ ?

Thanks @Ribero for verifying, I will have an update soon after analyzing what impact this change would have on the other features.

**Comment by jallamsetty1** [comment]
Looks like they have a fix that's going to be available in the next STP.

**Comment by Ribero** [comment]
@jallamsetty1 Does it mean we have to wait for a new Safari release from Apple (which could take months, especially for Mojave which is no more a priority for Apple) ?

**Comment by dox** [comment]
Happy to report that webcam/audio is working perfectly in Safari 14.0 (Big Sur) on Jitsi-meet 1.0.4127

**Comment by jallamsetty1** [comment]
> Happy to report that webcam/audio is working perfectly in Safari 14.0 (Big Sur) on Jitsi-meet 1.0.4127

Thank you for testing Jitsi-meet on Big Sur. Can you please share your macbook model ? Is it one of the older laptops by any chance ? The issue described here happens mostly on older models.

**Comment by dox** [comment]
> > Happy to report that webcam/audio is working perfectly in Safari 14.0 (Big Sur) on Jitsi-meet 1.0.4127
> 
> Thank you for testing Jitsi-meet on Big Sur. Can you please share your macbook model ? Is it one of the older laptops by any chance ? The issue described here happens mostly on older models.

Hey - so I tested this on an iMac (Retina 4K, 21.5-inch, Late 2015) and a MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports).

Both had the same issue before (no webcam, audio fine though).  Big Sur/Safari 14 upgrade and it's working totally as expected. 👍

**Comment by jallamsetty1** [comment]
> > > Happy to report that webcam/audio is working perfectly in Safari 14.0 (Big Sur) on Jitsi-meet 1.0.4127
> > 
> > 
> > Thank you for testing Jitsi-meet on Big Sur. Can you please share your macbook model ? Is it one of the older laptops by any chance ? The issue described here happens mostly on older models.
> 
> Hey - so I tested this on an iMac (Retina 4K, 21.5-inch, Late 2015) and a MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports).
> 
> Both had the same issue before (no webcam, audio fine though). Big Sur/Safari 14 upgrade and it's working totally as expected. 👍

That is great news! Thank you for giving us the update.

**Comment by jallamsetty1** [comment]
> @jallamsetty1 Does it mean we have to wait for a new Safari release from Apple (which could take months, especially for Mojave which is no more a priority for Apple) ?

Have you tried the Safari Technology preview ?

**Comment by Ribero** [comment]
> Have you tried the Safari Technology preview ?

Unfortunately no, I did not found the official version of Safari Technology Preview for Mojave. The only one version available seems to be for Catalina and Big Sur. I have to look a bit more to see if it still exists.

The other aspect is that I cannot impose my interlocutors running macOS Mojave and Safari (probably 40% of them) to install a specific browser.

**Comment by jallamsetty1** [comment]
> > Have you tried the Safari Technology preview ?
> 
> Unfortunately no, I did not found the official version of Safari Technology Preview for Mojave. The only one version available seems to be for Catalina and Big Sur (https://developer.apple.com/safari/download/). I have to look a bit more to see if it still exists.
> 
> The other aspect is that I cannot impose my interlocutors running macOS Mojave and Safari (probably 40% of them) to install a specific browser.

Sorry you are in this situation, I will discuss with the team to see what we can do about it even though Apple has a fix for it.

**Comment by Ribero** [comment]
Thanks @jallamsetty1 !

To argument: 

Please note that it is not specific to my context: every person using macOS Sierra, High Sierra or Mojave in combination with Safari is facing the issue. 

There are still many Profesionnal users (and probably non pro users too) that did not switched to Catalina yet for obvious compatibility reasons (legacy apps, drivers, hardware compatibility, internal support...), and Safari is still the most efficient browser (memory, cpu, battery, ios-macos sync/integration...) for many users. 

We can all hope that Apple will fix Webkit soon but there is absolutely no guarantee and knowing that there is a possible fix already available in Jitsi but not deployed is a bit frustrating. 
It's very rare that all people we are communicating with (most use apple hardware) meet the requirements to use Jitsi. In some context we can ask them to use their iPhone/iPad instead but when it is not possible we often have switch to another product. I don't feel very confident now setting up a video conf on jitsi knowing that I may have issue with a significant part of participants. 

Side comment: using the jisti meet desktop application (https://github.com/jitsi/jitsi-meet-electron) is probably the best solution to avoid all these hassle but it requires an installation and the application is not even mentioned on Jitsi home page. How end users are supposed to find it (searching on github ?)

**Comment by jallamsetty1** [comment]
> Thanks @jallamsetty1 !
> 
> To argument:
> 
> Please note that it is not specific to my context: every person using macOS Sierra, High Sierra or Mojave in combination with Safari is facing the issue.
> 
> There are still many Profesionnal users (and probably non pro users too) that did not switched to Catalina yet for obvious compatibility reasons (legacy apps, drivers, hardware compatibility, internal support...), and Safari is still the most efficient browser (memory, cpu, battery, ios-macos sync/integration...) for many users.
> 
> We can all hope that Apple will fix Webkit soon but there is absolutely no guarantee and knowing that there is a possible fix already available in Jitsi but not deployed is a bit frustrating.
> It's very rare that all people we are communicating with (most use apple hardware) meet the requirements to use Jitsi. In some context we can ask them to use their iPhone/iPad instead but when it is not possible we often have switch to another product. I don't feel very confident now setting up a video conf on jitsi knowing that I may have issue with a significant part of participants.
> 
> Side comment: using the jisti meet desktop application (https://github.com/jitsi/jitsi-meet-electron) is probably the best solution to avoid all these hassle while there is a solution for Safari but it requires an installation (which is never that simple with non tech users or non admin users) and the application is not even mentioned on Jitsi home page (https://jitsi.org/#download). How end users are supposed to find it (searching on github ?)

Thanks for explaining your situation. We will go ahead with the change, will try to get it in the upcoming meet.jit.si release. Thank you for your patience.

**Comment by jallamsetty1** [comment]
The fix for this issue is available in the nightly builds and will be available in the next release of meet.jit.si

**Comment by jallamsetty1** [comment]
Looks like we updated https://meet.jit.si yesterday with the fix, @Ribero can you please give it a try and let me know if this fixes the issue for you, thanks !

**Comment by Ribero** [comment]
@jallamsetty1 Congratulation and thank you so much. It works on the 3 mac I tried (MacBook Pro, iMac, Mac Pro).
Settings (preview panel) is also working.
