### ISSUE TITLE
Iframe API Change Camera disrupts audio on iOS Safari browser

### ISSUE THREAD

**Issue by augustinejenin** [jitsi/jitsi-meet#7129]
@jallamsetty1 

we integrated Iframe API in our website. But when client try to change the camera. its not possible.Front camera preview is blank and when click on that it shows an error Unable to access camera and camera not changed it still showing the first camera.
I tried in the settings menu. there is an option to change the camera. when try to change it shows preview not available.

### Expected behavior:

It should show the both camera previews and when click on that camera should work.

### Actual behavior:

When user click on the video button dropdown it not showing the preview of the front camera. when try to change the camera it shows the error "Unable to access camera".

### Server information:

- Jitsi Meet version:
root@video:~# dpkg -l | grep jitsi
ii  jitsi-meet                             2.0.4627-1                                      all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody                     1.0.4127-1                                      all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver                  1.0.4127-1                                      all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                         1.0.4127-1                                      all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config                  1.0.4127-1                                      all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2                     2.1-202-g5f9377b9-1                             all          WebRTC compatible Selective Forwarding Unit (SFU)
- Operating System:Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-45-generic x86_64)

### Additional information:

Its working in Redmi(android  ) chrome. Both previews are showing camera able to shift.
Its not working in iphone(safari) - preview not showing.selecting camera shows the error Unable to access camera
Its not working in lenovo (android 5.0.2) and Samsung  (android 8.1.0 ) - when click on video dropdown backcamera screen is showing a black screen and when click on that nothing happens. just shows error "Unable to access camera". Tried in the settings menu to change camera. but there shows preview not available.
**Our priority is to work this in Iphone safari browser**
![mn](https://user-images.githubusercontent.com/26268454/85387941-1bbd4500-b563-11ea-8a02-ff4161c460ad.png)

Please fix this issue as soon as possible

**Comment by augustinejenin** [comment]
@jallamsetty1 @saghul  Can you please reply.This issue need to be fixed soon.

**Comment by jallamsetty1** [comment]
> @jallamsetty1 @saghul Can you please reply.This issue need to be fixed soon.

These are mobile browser limitations. If we are capturing video from a given camera and then try to get to second stream for the preview, browser seems to turn off both the streams but device selection should work even when preview doesn't work. Try not to double select the camera, like if it's already in use, do not try to select that again, selecting the camera thats not in use seems to work fine. That is what I have seen in my testing on iPhone and Samsung phones. We haven't really optimized the UX for mobile and this is something on our roadmap but not sure when we will get to it.

**Comment by augustinejenin** [comment]
@jallamsetty1 @saghul 
Can you please provide an ios application for us. if you provide your email address i will send you our server url. We are web developers . we don't know to develop ios applications. we are loosing our  project because  of this error "Unable access camera".
Customers raising complaints about this.

Can you please respond soon?

**Comment by augustinejenin** [comment]
@jallamsetty1 @saghul  can you please replay when you can fix this issue. because clients raises complaints. we will loose our project because of this issue. Can you please let us know when you can fix this issues. we need this working in ios safari browser. 
So we can inform the clients to wait.

Please I am waiting for your updates.

**Comment by jallamsetty1** [comment]
Unfortunately this is a limitation on the mobile devices, iOS and Android phones don't allow opening more than one camera at a time. You should be able to change the device from the device selection menu where we can preview one camera at a time. I will disable the camera settings pop-up menu since it doesn't work. If you have your own deployment, I can let you know how to disable it until we are able to make that change on our side.

**Comment by augustinejenin** [comment]
@jallamsetty1  yes we have our own development. PLease let us know how to do it.  So disable means users will be able to access front cam only they will be not able shift camera now. right?

**Comment by jallamsetty1** [comment]
> @jallamsetty1 yes we have our own development. PLease let us know how to do it. So disable means users will be able to access front cam only they will be not able shift camera now. right?

I have merged a patch to disable settings from the camera and mic buttons. You should be able to get this change from the unstable repo. You should now use the device settings menu to preview and select a device.
![Image from iOS](https://user-images.githubusercontent.com/54324652/86133100-d8f4f300-bab5-11ea-97b9-58c5309a1339.jpg)

This setting is under the 3 dots menu as shown above.

**Comment by augustinejenin** [comment]
HI @jallamsetty1 please let us know the code we can disable this options. we get updations from stable repo. we need this updates only now.

**Comment by augustinejenin** [comment]
hi @jallamsetty1 when the iframe loads in ios browser. camera and microphone permissions will ask but it will show as disabled. user has to click again to enable. this issue only exist in ios browser no issues in android. any fix for this issue?

**Comment by jallamsetty1** [comment]
> HI @jallamsetty1 please let us know the code we can disable this options. we get updations from stable repo. we need this updates only now.

Here is the patch - https://github.com/jitsi/jitsi-meet/commit/0e1ecd3256cb7d60563fac1c81f45a1437a52fe4

**Comment by augustinejenin** [comment]
> hi @jallamsetty1 when the iframe loads in ios browser. camera and microphone permissions will ask but it will show as disabled. user has to click again to enable. this issue only exist in ios browser no issues in android. any fix for this issue?

@jallamsetty1 can you please replay to this issues? This issue only happens when it takes in iphone safari browser.

**Comment by augustinejenin** [comment]
> > HI @jallamsetty1 please let us know the code we can disable this options. we get updations from stable repo. we need this updates only now.
> 
> Here is the patch - [0e1ecd3](https://github.com/jitsi/jitsi-meet/commit/0e1ecd3256cb7d60563fac1c81f45a1437a52fe4)

@jallamsetty1  we didn't see these files ( react/features/toolbox/components/web/AudioSettingsButton.js , react/features/toolbox/components/web/VideoSettingsButton.js) in our deployment.

**Comment by saghul** [comment]
You need to rebuild the frontend. Or use our nightly builds.

**Comment by augustinejenin** [comment]
> hi @jallamsetty1 when the iframe loads in ios browser. camera and microphone permissions will ask but it will show as disabled. user has to click again to enable. this issue only exist in ios browser no issues in android. any fix for this issue?

@jallamsetty1  Can you please reply to this issue?

**Comment by jallamsetty1** [comment]
> > hi @jallamsetty1 when the iframe loads in ios browser. camera and microphone permissions will ask but it will show as disabled. user has to click again to enable. this issue only exist in ios browser no issues in android. any fix for this issue?
> 
> @jallamsetty1 Can you please reply to this issue?

This has been fixed on meet.jit.si, we deployed a fix last week and it is also available in the latest nightly builds.

**Comment by jallamsetty1** [comment]
@augustinejenin, can you please close this issue if both the issues that you reported are fixed for you ?

**Comment by augustinejenin** [comment]
> > > hi @jallamsetty1 when the iframe loads in ios browser. camera and microphone permissions will ask but it will show as disabled. user has to click again to enable. this issue only exist in ios browser no issues in android. any fix for this issue?
> > 
> > 
> > @jallamsetty1 Can you please reply to this issue?
> 
> This has been fixed on meet.jit.si, we deployed a fix last week and it is also available in the latest nightly builds.

@jallamsetty1  we got this update from your nightly builds. when you will update this to your stable release?

Camera shifting is still not working. we tried to change it from the settings but it still shows preview not available. Do you know when this will be fixed?

Please reply  to my two questions then i can close the issues.

**Comment by augustinejenin** [comment]
> @augustinejenin, can you please close this issue if both the issues that you reported are fixed for you ?

Camera shifting is still not working. we tried to change it from the settings but it still shows preview not available. Do you know when this will be fixed?

So i can close this issue

**Comment by jallamsetty1** [comment]
> > @augustinejenin, can you please close this issue if both the issues that you reported are fixed for you ?
> 
> Camera shifting is still not working. we tried to change it from the settings but it still shows preview not available. Do you know when this will be fixed?
> 
> So i can close this issue

Will you be able share the link to your website so that I can see what's happening ?

**Comment by augustinejenin** [comment]
@jallamsetty1  this is the website  we integrated iframe API  -- https://grupo.testme.es/videopage/

When we try to change the camera it shows preview not available in android and some iphones it gets unable to access camera.

Please look into the attachments:

![Skype_Picture](https://user-images.githubusercontent.com/26268454/87505067-96224600-c685-11ea-971e-ecf85024a29e.jpeg)
![fc1da2f4-e5b6-4bf7-a627-ea1976064b97](https://user-images.githubusercontent.com/26268454/87505088-a76b5280-c685-11ea-9da9-a244afd239bc.jpg)
![fe05f2ac-6b5e-4fd0-a34e-82154062b314](https://user-images.githubusercontent.com/26268454/87505094-a9351600-c685-11ea-94e3-dc3c1b2fdef6.jpg)

**Comment by augustinejenin** [comment]
> @jallamsetty1 this is the website we integrated iframe API -- https://grupo.testme.es/videopage/
> 
> When we try to change the camera it shows preview not available in android and some iphones it gets unable to access camera.
> 
> Please look into the attachments:
> **Iphone**:
> ![Skype_Picture](https://user-images.githubusercontent.com/26268454/87505067-96224600-c685-11ea-971e-ecf85024a29e.jpeg)
> 
> **Android Phone:**
> ![fc1da2f4-e5b6-4bf7-a627-ea1976064b97](https://user-images.githubusercontent.com/26268454/87505088-a76b5280-c685-11ea-9da9-a244afd239bc.jpg)
> ![fe05f2ac-6b5e-4fd0-a34e-82154062b314](https://user-images.githubusercontent.com/26268454/87505094-a9351600-c685-11ea-94e3-dc3c1b2fdef6.jpg)

@jallamsetty1 could you check this?

**Comment by jallamsetty1** [comment]
I tested it on an iPhone 8 plus and didn't see any issues. I was able to get the preview and switch cameras as well. I did see the unable to access camera error but that seem to affect the above behavior, will try to take a look why we are getting the error.
I am trying to resurrect an old android phone to test this. Are you saying that the preview and switching don't happen on android phones at all ? Does this happen on all android phones or only on certain models ?

**Comment by augustinejenin** [comment]
@jallamsetty1  we tested in these both android phones showing the same issues. When switching the camera preview not available.
Lenovo 6010 , android 5.0.2
Samsung  SM-G610F,  android 8.1.0

I will explain scenario as detail:

Front cam will be working as default when  we access the url  and we go to settings and change camera it will show preview not availble. when click on ok it will show message failed to access your camera.if i refresh the page then it will default will show the backcamera.

Its working Redmi Note 8 , android.

Another issue reported that phone is getting hang when shifting the camera.

**Comment by augustinejenin** [comment]
@jallamsetty1  can you tell me when this will be working in all device. it should be working in all iphones because most of the clients are using iphones,

**Comment by jallamsetty1** [comment]
> @jallamsetty1 can you tell me when this will be working in all device. it should be working in all iphones because most of the clients are using iphones,

It is working fine on the iPhone and Android devices that I tested, both of them recent models and running latest versions of the OS. If the preview and switching isn't working fine on the older models, I am inclined to blame it on the mobile browser. Are you able to able to update and check ?

**Comment by augustinejenin** [comment]
@jallamsetty1  we tested in iphone. still the preview is not available when change the camera and phone is getting hang. issue exist in the android latest version also(android 9 lenovo).

preview screen shows black screen but camera shift is working. Now these two issues are reporting.
1. preview not available when shifting the camera.
2. phone is getting hang.

**Comment by jallamsetty1** [comment]
@augustinejenin, 
Can you pls let me know what is the model and iOS version of the iPhone that you are seeing these 2 issues on ? If that is a device specific issue, we will not be able to fix the part where the device hangs, you will have to open a bug report in webkit.

@saghul helped me test few other Android devices like Galaxy S9, Pixel 3, Xiaomi Poco F1, Xiaomi MiPad 2 and they all seem to be working fine with preview and switching cameras. I think the key here is to have the latest versions of the OS on these devices. Having said that, we can make a few changes to make the experience better on mobile UI  but that will take time.

**Comment by augustinejenin** [comment]
@jallamsetty1 
iOS version is 13.6 latest one
iPhone XR is model

**Comment by augustinejenin** [comment]
@jallamsetty1  Can we use your unstable release for our customers. 
When your all unstable releases will be available in production?

You had time to check in the iphone model i mentioned above?

**Comment by jallamsetty1** [comment]
> @jallamsetty1 Can we use your unstable release for our customers.
> When your all unstable releases will be available in production?
> 
> You had time to check in the iphone model i mentioned above?

We have plans to push the latest to stable repo sometime this week. You can also use unstable releases for your customer if you prefer not to wait for the stable releases.
I don't have access to an iPhone XR, will check if someone else in the team does.

**Comment by jallamsetty1** [comment]
@augustinejenin, one of the team members tried it on an iphone max and was not able to reproduce the issue. Will you be able to provide us with the logs from iPhone XR where you are reproducing the issue ?

**Comment by augustinejenin** [comment]
> @augustinejenin, one of the team members tried it on an iphone max and was not able to reproduce the issue. Will you be able to provide us with the logs from iPhone XR where you are reproducing the issue ?

@jallamsetty1  one client informed that its not working in this model 6S y iPhoneX, version iOS 13.5.1.
Can you please let me where you checking this? i hope you tested in this https://grupo.testme.es/videopage/ . Currently doing some updation in this server.

If you checking in your unstable repo pls let us know the repo.

Can you please check in  6S y iPhoneX, version iOS 13.5.1.? clients waiting for the Update.

**Comment by jallamsetty1** [comment]
> > @augustinejenin, one of the team members tried it on an iphone max and was not able to reproduce the issue. Will you be able to provide us with the logs from iPhone XR where you are reproducing the issue ?
> 
> @jallamsetty1 one client informed that its not working in this model 6S y iPhoneX, version iOS 13.5.1.
> Can you please let me where you checking this? i hope you tested in this https://grupo.testme.es/videopage/ . Currently doing some updation in this server.
> 
> If you checking in your unstable repo pls let us know the repo.
> 
> Can you please check in 6S y iPhoneX, version iOS 13.5.1.? clients waiting for the Update.

Hi @augustinejenin, as much as we would like to help, we don't have the resources to debug this issue on each and every device. It would be really helpful if you could narrow it down for us.
Do you know if this issue is specific to iFrame ? 
Does the issue reproduce when you try directly on the browser w/o iFrame on your deployment ? 
You can also try against https://meet.jit.si to rule out config issues from your deployment that could cause this.
We would also need the logs from the device where it reproduces with steps for reproduction.

Thanks!

**Comment by utkarshmarwaha** [comment]
@jallamsetty1 @saghul 
I am facing a similar issue on iPhone X. Whenever I go to settings and come back to video screen, The video and audio stops working. Other person on call cannot see my video or listen to my audio and I can't even listen to other person's audio. Plus There comes a message showing **"Unable to access camera"** which I can't even dismiss from the screen. If I try to restart the video from ongoing call screen by turning it off and then on again then the video resumes but similar thing doesn't work for audio

"Unable to access camera" even appears on settings screen sometimes after a few seconds on the settings screen even when I can see my camera in the video preview box. Its positioning is such that It doesn't even allow to press ok/cancel to go back to previous screen and it can't even be dismissed

I even tried it with https://meet.jit.si but the issue persists there as well.

![WhatsApp Image 2020-08-04 at 4 11 55 PM](https://user-images.githubusercontent.com/63839120/89285352-d023ae00-d66d-11ea-8e8e-9e8a6e3927b3.jpeg)

![WhatsApp Image 2020-08-04 at 4 33 45 PM](https://user-images.githubusercontent.com/63839120/89286746-5f31c580-d670-11ea-8418-58a843519cae.jpeg)

**Comment by augustinejenin** [comment]
@jallamsetty1  i was waiting for the customer reply. This is now they says.
 Cameras now work on iPhone and iPad
- When the host switches to the rear camera, the microphone is canceled and it is no longer heard.
- In the session with the computer it does not work, directly it cannot connect, it stays in the loop all the time trying to connect

if this issue is fixed. client is ok. Please check this issue.

**Comment by jallamsetty1** [comment]
> @jallamsetty1 @saghul
> I am facing a similar issue on iPhone X. Whenever I go to settings and come back to video screen, The video and audio stops working. Other person on call cannot see my video or listen to my audio and I can't even listen to other person's audio. Plus There comes a message showing **"Unable to access camera"** which I can't even dismiss from the screen. If I try to restart the video from ongoing call screen by turning it off and then on again then the video resumes but similar thing doesn't work for audio
> 
> "Unable to access camera" even appears on settings screen sometimes after a few seconds on the settings screen even when I can see my camera in the video preview box. Its positioning is such that It doesn't even allow to press ok/cancel to go back to previous screen and it can't even be dismissed
> 
> I even tried it with https://meet.jit.si but the issue persists there as well.
> 
> ![WhatsApp Image 2020-08-04 at 4 11 55 PM](https://user-images.githubusercontent.com/63839120/89285352-d023ae00-d66d-11ea-8e8e-9e8a6e3927b3.jpeg)
> 
> ![WhatsApp Image 2020-08-04 at 4 33 45 PM](https://user-images.githubusercontent.com/63839120/89287609-f0556c00-d671-11ea-9278-5df23c88b4f9.jpeg)

We are aware of this issue, it happens when we try to grab a second stream from a camera while the stream capture is already in progress. We can mitigate this on mobile web by providing a toggle cam/mic button instead of the select cam/mic button. This will need a little bit of re-work on the mobile web UI and unfortunately we won't be able to get to it soon.

**Comment by jallamsetty1** [comment]
> @jallamsetty1 i was waiting for the customer reply. This is now they says.
> Cameras now work on iPhone and iPad
> 
> * When the host switches to the rear camera, the microphone is canceled and it is no longer heard.
This seems to be the same issue that the other user reported above, opening mic twice seems to be messing up the original stream. The only alternative would be to provide a toggle button.
> * In the session with the computer it does not work, directly it cannot connect, it stays in the loop all the time trying to connect
Can you please explain what you mean this ? Which client keeps reloading ? Is it the mobile client or the desktop browser client ?
> 
> if this issue is fixed. client is ok. Please check this issue.

**Comment by augustinejenin** [comment]
> > @jallamsetty1 i was waiting for the customer reply. This is now they says.
> > Cameras now work on iPhone and iPad
> > 
> > * When the host switches to the rear camera, the microphone is canceled and it is no longer heard.
> 
> This seems to be the same issue that the other user reported above, opening mic twice seems to be messing up the original stream. The only alternative would be to provide a toggle button.
> 
> > * In the session with the computer it does not work, directly it cannot connect, it stays in the loop all the time trying to connect
> 
> Can you please explain what you mean this ? Which client keeps reloading ? Is it the mobile client or the desktop browser client ?
> 
> > if this issue is fixed. client is ok. Please check this issue.

@jallamsetty1 i didnt understand this "The only alternative would be to provide a toggle button."

What Update we need to do for this?

This is the code we are using 
<script src='https://mydomain/external_api.js'></script> <script type="text/javascript"> jQuery(document).ready(function() { var domain = 'mydomain'; var options = { roomName: 'chatroom', width: '100%', height: 700, configOverwrite: { disableDeepLinking: true }, parentNode: document.querySelector('#meet'), }; var api = new JitsiMeetExternalAPI(domain, options); }); </script>

**Comment by augustinejenin** [comment]
> > > @jallamsetty1 i was waiting for the customer reply. This is now they says.
> > > Cameras now work on iPhone and iPad
> > > 
> > > * When the host switches to the rear camera, the microphone is canceled and it is no longer heard.
> > 
> > 
> > This seems to be the same issue that the other user reported above, opening mic twice seems to be messing up the original stream. The only alternative would be to provide a toggle button.
> > > * In the session with the computer it does not work, directly it cannot connect, it stays in the loop all the time trying to connect
> > 
> > 
> > Can you please explain what you mean this ? Which client keeps reloading ? Is it the mobile client or the desktop browser client ?
> > > if this issue is fixed. client is ok. Please check this issue.
> 
> @jallamsetty1 i didnt understand this "The only alternative would be to provide a toggle button."
> 
> What Update we need to do for this?
> 
> This is the code we are using
> 
> <script src='https://mydomain/external_api.js'></script> <script type="text/javascript"> jQuery(document).ready(function() { var domain = 'mydomain'; var options = { roomName: 'chatroom', width: '100%', height: 700, configOverwrite: { disableDeepLinking: true }, parentNode: document.querySelector('#meet'), }; var api = new JitsiMeetExternalAPI(domain, options); }); </script>

@jallamsetty1 can you please reply how to make this microphone works?

**Comment by augustinejenin** [comment]
> > @jallamsetty1 i was waiting for the customer reply. This is now they says.
> > Cameras now work on iPhone and iPad
> > 
> > * When the host switches to the rear camera, the microphone is canceled and it is no longer heard.
> 
> This seems to be the same issue that the other user reported above, opening mic twice seems to be messing up the original stream. The only alternative would be to provide a toggle button.
> 
> > * In the session with the computer it does not work, directly it cannot connect, it stays in the loop all the time trying to connect
> 
> Can you please explain what you mean this ? Which client keeps reloading ? Is it the mobile client or the desktop browser client ?
> 
> > if this issue is fixed. client is ok. Please check this issue.

hi @jallamsetty1 do you have any update for the mic is not working. Clients asking when this will fixed. Mic is not working when they shift the camera.

**Comment by augustinejenin** [comment]
@jallamsetty1 Do You have any update for this ? clients still asking about this. Can You let me know when this will be fixed?

**Comment by jallamsetty1** [comment]
> @jallamsetty1 Do You have any update for this ? clients still asking about this. Can You let me know when this will be fixed?

Unfortunately, we don't have a quick fix for it since it is a mobile browser issue. We will have to implement a workaround by changing the way we switch between devices which would need a bit of rework on the UI. At this point, I don't have an estimate on when this will be prioritized.

**Comment by augustinejenin** [comment]
@jallamsetty1 Thank you for the update. But clients still asking about this. if you fix this issue please let me know.
Thank You

**Comment by augustinejenin** [comment]
> > @jallamsetty1 Do You have any update for this ? clients still asking about this. Can You let me know when this will be fixed?
> 
> Unfortunately, we don't have a quick fix for it since it is a mobile browser issue. We will have to implement a workaround by changing the way we switch between devices which would need a bit of rework on the UI. At this point, I don't have an estimate on when this will be prioritized.

@jallamsetty1 any updates the issue?

**Comment by augustinejenin** [comment]
> > @jallamsetty1 Do You have any update for this ? clients still asking about this. Can You let me know when this will be fixed?
> 
> Unfortunately, we don't have a quick fix for it since it is a mobile browser issue. We will have to implement a workaround by changing the way we switch between devices which would need a bit of rework on the UI. At this point, I don't have an estimate on when this will be prioritized.

hi @jallamsetty1  Can you give me an update on this Because clients still asking about this . Can you please let me know a date this issue will be fixed. then we can inform them.

**Comment by jallamsetty1** [comment]
Unfortunately, I won't be able to provide you a date yet, I will be out for a week starting tomorrow. I will have to discuss with my manager if I can move this task to top of the list when I get back.

**Comment by augustinejenin** [comment]
@jallamsetty1  Can you give me an update on this when you come back?

**Comment by jallamsetty1** [comment]
> @jallamsetty1 Can you give me an update on this when you come back?

Unfortunately this a mobile Safari [bug](https://bugs.webkit.org/show_bug.cgi?id=179363) that is producing the same issue on all other video conferencing solutions as well. We will wait for an update from the Apple folks before taking on UI redesign task just to mitigate this one.

**Comment by augustinejenin** [comment]
@jallamsetty1 thank you for the update. when ever you get the update please let me know. we are waiting for this fix.

**Comment by augustinejenin** [comment]
@jallamsetty1 any updates?

**Comment by amirkhattak** [comment]
hi there i am facing issue on mobile andriod i am using external api iframe its show this image [https://chat.pakistanichatzone.com/ss.png/](url)

**Comment by amirkhattak** [comment]
its showing that i cant use on mobile i need to download app

**Comment by augustinejenin** [comment]
> its showing that i cant use on mobile i need to download app

use this configOverwrite: { disableDeepLinking: true }

**Comment by augustinejenin** [comment]
@jallamsetty1 any update on this? clients asking about this.

**Comment by augustinejenin** [comment]
> > @jallamsetty1 Can you give me an update on this when you come back?
> 
> Unfortunately this a mobile Safari [bug](https://bugs.webkit.org/show_bug.cgi?id=179363) that is producing the same issue on all other video conferencing solutions as well. We will wait for an update from the Apple folks before taking on UI redesign task just to mitigate this one.

@jallamsetty1 any update on this clients asking about this.

**Comment by augustinejenin** [comment]
> > @jallamsetty1 Can you give me an update on this when you come back?
> 
> Unfortunately this a mobile Safari [bug](https://bugs.webkit.org/show_bug.cgi?id=179363) that is producing the same issue on all other video conferencing solutions as well. We will wait for an update from the Apple folks before taking on UI redesign task just to mitigate this one.

@jallamsetty1 any updates in this.

**Comment by jallamsetty1** [comment]
I am sorry @augustinejenin, unfortunately, I don't have an update on this yet.

**Comment by amirkhattak** [comment]
is there any way to use random rooms name automatically in iframe  in external based api?

**Comment by augustinejenin** [comment]
> I am sorry @augustinejenin, unfortunately, I don't have an update on this yet.

@jallamsetty1 clients still asking about this. do you have any updates about this. We need to send an updates to them.Any updates when this may be fixed?

**Comment by Dewsworld** [comment]
I am at the end of losing a contract because of this bug. Please add support for (at least) popular browser with iframe API

**Comment by saghul** [comment]
Look, trying to harass developers like this won't get you very far. 

This is a bug in Safari: https://github.com/jitsi/jitsi-meet/issues/7129#issuecomment-690749760

**Comment by Dewsworld** [comment]
> Look, trying to harass developers like this won't get you very far.
> 
> This is a bug in Safari: [#7129 (comment)](https://github.com/jitsi/jitsi-meet/issues/7129#issuecomment-690749760)

No offense intended.

**Comment by jallamsetty1** [comment]
> > Look, trying to harass developers like this won't get you very far.
> > This is a bug in Safari: [#7129 (comment)](https://github.com/jitsi/jitsi-meet/issues/7129#issuecomment-690749760)
> 
> No offense intended.
> 
> Plus, it's not working in chrome, firefox web browser also.

Are you saying that audio drops out on Chrome/FF on Android as well when you try to select camera ?

**Comment by Dewsworld** [comment]
> Are you saying that audio drops out on Chrome/FF on Android as well when you try to select a camera?

The audio works well on chrome browser. But the camera starts and within a blink, it goes dark and then comes the issue, unable to access the camera.

Note to all viewers who read the thread: I'm a huge fan of Jitsi. That's why I care about its betterment.

**Comment by jallamsetty1** [comment]
@augustinejenin, I have been able to talk to product team and we will be prioritizing this work in the coming 2-3 weeks unless something else comes up. 
@Dewsworld, the issue you are describing is different from what we are running into on mobile Safari.
Please open a new github issue and leave as much information there as possible with versions, devices and browser logs.

**Comment by augustinejenin** [comment]
> @augustinejenin, I have been able to talk to product team and we will be prioritizing this work in the coming 2-3 weeks unless something else comes up.
> @Dewsworld, the issue you are describing is different from what we are running into on mobile Safari.
> Please open a new github issue and leave as much information there as possible with versions, devices and browser logs.

@jallamsetty1 thank you for your update.

**Comment by augustinejenin** [comment]
> @augustinejenin, I have been able to talk to product team and we will be prioritizing this work in the coming 2-3 weeks unless something else comes up.
> @Dewsworld, the issue you are describing is different from what we are running into on mobile Safari.
> Please open a new github issue and leave as much information there as possible with versions, devices and browser logs.

hi @jallamsetty1 is that started ? Can you please let us know an update ?

**Comment by augustinejenin** [comment]
> > @augustinejenin, I have been able to talk to product team and we will be prioritizing this work in the coming 2-3 weeks unless something else comes up.
> > @Dewsworld, the issue you are describing is different from what we are running into on mobile Safari.
> > Please open a new github issue and leave as much information there as possible with versions, devices and browser logs.
> 
> hi @jallamsetty1 is that started ? Can you please let us know an update ?

@jallamsetty1 any updates?

**Comment by jallamsetty1** [comment]
@augustinejenin Sorry for the delay in responding. Unfortunately, the work needed for this change could not be scheduled because of other higher priority tasks. Leaving this issue open and marking it as low priority. We will be happy to accept PRs from the community that addresses this issue.

**Comment by jallamsetty1** [comment]
@augustinejenin, this issue has been fixed thanks to @muscat1! There is a new toggle camera button under the 3-dots menu now. This should be available in the next release of meet.jit.si.
