### ISSUE TITLE
Ability to pass dropbox access token to config so it doesn't require signing in

### ISSUE THREAD

**Issue by ovvn** [jitsi/jitsi-meet#7684]
**Is your feature request related to a problem you are facing?**
Trying to pass dropbox access token along with `appKey` and `redirectURI` to the config https://github.com/jitsi/jitsi-meet/blob/master/config.js#L190

**Describe the solution you'd like**
Being able to pass the dropbox token so it doesn't ask to sign in when starting recording

**Describe alternatives you've considered**
No alternatives

**Comment by damencho** [comment]
Is this possible using the dropbox API?

**Comment by ovvn** [comment]
@damencho it's actually possible via `jitsiApi.executeCommand 'startRecording', { dropboxToken }` that's why I thought if pass the token to `configOverwrite`along with `appKey` and `redirectURI` then it shouldn't require signing in when I click on 'Start recording' in the menu.

**Comment by damencho** [comment]
Hum, why would you need to pass appkey and redirectURL? 
In order to obtain the `dropboxToken` you should already be using it then obtain the token and pass it to the iframeAPI.
Allowing any url to be overridden is a security issue and should be avoided.

**Comment by ovvn** [comment]
> Hum, why would you need to pass appkey and redirectURL?
Just following the integration guide at https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web-integrations#creating-the-dropbox-app-for-dropbox-recording-integration
> In order to obtain the `dropboxToken` you should already be using it then obtain the token and pass it to the iframeAPI.
> Allowing any url to be overridden is a security issue and should be avoided.
yes I agree, but found it confusing that even after specifying 
```
    dropbox: {
        appKey: '__dropbox_app_key__',
        redirectURI: 'https://yourdeployment.com/static/oauth.html'
    }
```
It still required signing in when clicking on 'Start Recording'

**Comment by damencho** [comment]
Hum, I see. This means we do not handle correctly the passed `dropboxToken ` to the iframeAPI and that should be fixed.

**Comment by hardik-modi** [comment]
Still facing the issue with custom installation, I have enabled the dropbox like mentioned in **https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web-integrations#creating-the-dropbox-app-for-dropbox-recording-integration.**

I also added the dropbox access token like this **jitsiApi.executeCommand 'startRecording', { dropboxToken }** in IFrame API but no luck.


I tried by disabling this  dropbox: {
        appKey: '__dropbox_app_key__',
        redirectURI: 'https://yourdeployment.com/static/oauth.html'
    }
as I am adding token **jitsiApi.executeCommand 'startRecording', { dropboxToken }** in IFrame API but still no luck.

**Comment by csanchez-kachimushi** [comment]
Hi @ovvn 

Hello @ovvn 
![disabled default dropbox](https://user-images.githubusercontent.com/120679156/215144196-ad008f36-6cea-4407-8040-b14b3dcd92b7.PNG)
 regarding this issue, did you manage to find the solution?
I have a similar issue, I already enabled and linked the DropBox to jitsi and it does not request a login, but I need the option to be enabled at login,
my configuration is as follows:

configOverwrite: { fileRecordingsEnabled: true,
dropbox: {
          appKey: 'xxxxxx'
        },
      },
interfaceConfigOverwrite: {}
