### ISSUE TITLE
"Video Share" feature flag not respected on Android

### ISSUE THREAD

**Issue by mfts** [jitsi/jitsi-meet#7764]
### Description:
I have set the feature flag `video-share.enabled` to `false`. It works well on iOS. 

However, testing it, the video sharing button is still shown for Android phones. In particular, Galaxy S9 (Android 10)

https://github.com/jitsi/jitsi-meet/blob/7f5751b9185b406a55e22b0df204620f56eae1b0/react/features/base/flags/constants.js

### Steps to reproduce:

In `MainActivity.java` I have changed the following function:

```
private void setJitsiMeetConferenceDefaultOptions() {
        // Set default options
        JitsiMeetConferenceOptions defaultOptions
            = new JitsiMeetConferenceOptions.Builder()
            .setWelcomePageEnabled(true)
            .setServerURL(buildURL(defaultURL))
            .setFeatureFlag("call-integration.enabled", false)
            .setFeatureFlag("resolution", 360)
            .setFeatureFlag("server-url-change.enabled", !configurationByRestrictions)
            .setFeatureFlag("calendar.enabled", false)
            .setFeatureFlag("live-streaming.enabled", false)
            .setFeatureFlag("recording.enabled", false)
            .setFeatureFlag("video-share.enabled", false)           ## <---- video share feature flag
            .setFeatureFlag("invite.enabled", false)
            .setFeatureFlag("close-captions.enabled", false)
            .build();
        JitsiMeet.setDefaultConferenceOptions(defaultOptions);
    }
```

However, when built, signed and installed on an Android device, the video sharing feature is still available

### Expected behavior:

If I disable the `video-share` feature flag, it should not appear in the Android application anymore.

### Actual behavior:

Even if I disabled the `video-share` feature flag, the button to share a video still appears in the Android application.

### Server information:

- Jitsi Meet version: stable-4857
- Operating System: debian10

### Client information:

- Browser / app version: android-20.4.1
- Operating System: Android 10

### Additional information:

![Screenshot_20200923](https://user-images.githubusercontent.com/4049052/94015474-96da0580-fdb5-11ea-9548-1570de5ea46a.jpg)

**Comment by saghul** [comment]
What SDK version are you using?

**Comment by mfts** [comment]
- Jisti-Meet Android SDK 2.10.0
- Android SDK minimum version 23
- Android SDK target version 29

**Comment by saghul** [comment]
Hum, there might be a bug in there!

**Comment by Marinaarimany** [comment]
Hello, 
I also have this problem with the other parameters such as the meeting password which is displayed when I passed meeting-password.enabled to false, I also have this problem with call-integration .enabled. 
I am on android 10 too.
When will the correction be made?
Thank you so much 👍

**Comment by saghul** [comment]
What SDK version are you using @Marinaarimany ?

**Comment by Marinaarimany** [comment]
@saghul 
I am developing with react-native. I don't know if you can help me: /
I am using the react-native-jitsi-meet version 2.1.1 library
Thank you

**Comment by saghul** [comment]
That version is incredibly old. Please update to the latest SDK version (2.10.0) at the time of this writing.

**Comment by Marinaarimany** [comment]
@saghul  Thank you :)

**Comment by saghul** [comment]
@mfts I just tested this myself and cannot reproduce it. Are you sure you are on the latest version? You said you modified MainActivity.java, but that's not part of the SDK, so I'm a bit unsure about what you are using really.

**Comment by Marinaarimany** [comment]
@saghul  Can you send me the link of the sdk please because the library I am using is outdated I think. And I would like to have no more worries with Jitsi ^^
https://www.npmjs.com/package/react-native-jitsi-meet

Thank you

**Comment by saghul** [comment]
We don't maintain that package, sorry. Our SDK is released to our maven repo or cocoapods respectively. See here: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-mobile

**Comment by doomtrooper** [comment]
@saghul I am also facing this issue mentioned by @mfts , Any help would be appreciated.

**Comment by mfts** [comment]
@doomtrooper the issue was solved in the latest Android release v20.5

**Comment by moskaland** [comment]
@mfts still facing issue on my end:
    jitsi-meet-sdk:3.1.0"
    minSdkVersion 24
    targetSdkVersion 30
    compileSdkVersion 30

**Comment by hanifmhd** [comment]
hi @saghul i'm still facing this issue even i already set `false` the "video-share.enabled"
i'm using jitsi-meet-sdk:3.6.0
