### ISSUE TITLE
Keyboard shortcuts do not take into account modifier keys

### ISSUE THREAD

**Issue by alajovic** [jitsi/jitsi-meet#7933]
### Description:

Keyboard shortcuts in Jitsi work regardless of whether a modifier key (Ctrl, Alt, ...) is pressed at the same time or not. For example, muting works with just the M key, but also with Ctrl+M, Alt+M, or Ctrl+Alt+M. Same for V, Ctrl+V, Alt+V, Ctrl+Alt+V, Win+V, and so on. I found out about this because on my system, Ctrl+Alt+M is set as a shortcut that opens up a browser window. As you can imagine, it gets pressed quite often. For some reason, the key press event also gets delivered to the current window, so while I'm in a Jitsi talk, pressing this key combination not only opens up another browser window, but also mutes my microphone. This is very annoying, since I usually only realize what has happened a while later, when I try to speak and ostensibly get ignored by other participants.

In my opinion, Jitsi should only react to keyboard events that don't have any active modifier keys.

### Steps to reproduce:

1. Start a Jitsi meeting.
2. Press Ctrl+M, Alt+M, or Ctrl+Alt+M

### Expected behavior:

Jitsi does not react to the key M when a modifier key is also pressed at the same time.

### Actual behavior:

The microphone gets muted, even though the shortcut for muting is supposed to be just "M", and not Ctrl+M, Alt+M, or Ctrl+Alt+M.

### Server information:

Issue is reproducible with the current version on meet.jit.si (as of 2020-10-20).

### Client information:

- Browser / app version: Reproducible with Firefox 81 and Chromium 86.
- Operating System: Gentoo Linux

**Comment by archenemies** [comment]
I was just using Jitsi in Firefox 84.0 and noticed the key bindings only work when I press them with "meta", otherwise it activates the default Firefox binding for the key (e.g. opening the find-in-page bar to search for the letter "m" when I press "m").

I haven't been able to check if this is due to my own configuration, there is nothing I can remember that would cause "meta" to be required. Another Firefox user was not able to reproduce on an older version of Firefox.

But I prefer to activate the keybindings with "meta" in general, since it helps disambiguate browser keybindings from web page keybindings. So my perspective is a bit different, certainly it would be nice for me if modifiers could be configured and not just disabled entirely.

I found this issue when searching to see if anyone else had the same problem. Thanks.

**Comment by i-need-to-tell-you-something** [comment]
> I was just using Jitsi in Firefox 84.0 and noticed the key bindings only work when I press them with "meta", otherwise it activates the default Firefox binding for the key (e.g. opening the find-in-page bar to search for the letter "m" when I press "m").
> 
> I haven't been able to check if this is due to my own configuration, there is nothing I can remember that would cause "meta" to be required. Another Firefox user was not able to reproduce on an older version of Firefox.
> 
> But I prefer to activate the keybindings with "meta" in general, since it helps disambiguate browser keybindings from web page keybindings. So my perspective is a bit different, certainly it would be nice for me if modifiers could be configured and not just disabled entirely.
> 
> I found this issue when searching to see if anyone else had the same problem. Thanks.

For me personally, Meta+letters would be terrible since I already have those bound. I think that might be the case for many other users as the Meta modifier is normally avoided by applications and reserved for the OS. What could address your preference would be effectively a separate feature request - to have the hotkey configurable.

Also, I think the bug you are experiencing - hotkeys not working unless meta is held - could hypothetically be tested by booting a clean live-USB of your OS and using meet.jit.si in the browser there. You should probably make a separate issue for it if it persists in that case.

**Comment by i-need-to-tell-you-something** [comment]
It is very annoying with my use case where I use a lot of hotkeys with modifiers, so I am constantly involuntarily turning off my video, and raising my hand, and modifying other settings in Jitsi Meet. Some participants have gotten used to ignoring that, but in other cases, it is very inconvenient.

### Client information:

* Browser / app version: Firefox 86.0.1 (64-bit) + meet.jit.si (2021-03-25).
* Operating System: Kubuntu 18.04

**Comment by i-need-to-tell-you-something** [comment]
Apparently, there was a partial fix [here](https://github.com/jitsi/jitsi-meet/pull/6907) (only blocks Meta key modified inputs). But it has not been merged, probably because noone seems to have found time to test it. So based on that Alt and Ctrl might be blocked as easily, but testing is needed.

**Comment by alajovic** [comment]
@archenemies, the behavior you are describing, namely that when you press a key without a modifier, Firefox initiates the in-page search, is probably due to a Firefox setting. You can check under _General_ -> _Browsing_ -> _Search for text when you start typing_. I had this option turned on for a long time, but eventually realized that it interacted badly with _so_ many web pages that it was getting in my way much more than it helped me, so I turned it off. Pressing Ctrl+F when I want to search isn't that much of a hassle after all.

**Comment by ulab** [comment]
This can quickly become a privacy issue when you try to paste something with `ctrl-v` into the chat, but have not focused the input field. The camera should not get enabled then.

**Comment by alajovic** [comment]
I recently noticed that the behavior seems to have changed since the last update to this discussion, and the issue seems to be gone, at least for me. That is, modifier keys now correctly prevent Jitsi hotkey actions from triggering. I kindly ask other participants from the discussion to check if that's the case for them as well, and if it is, we can close the issue.

**Comment by ulab** [comment]
For OSX `cmd-v` and `alt-v` are not switching the camera anymore. `ctrl-v` still does though.

**Comment by alajovic** [comment]
Hmm, right. I actually only checked my own use case, which was `Ctrl+Alt+key`. Now that you mention it, `Ctrl+key` and `Meta+key` do indeed still seem to trigger the hotkey action also here (GNU/Linux – Kubuntu 20.04).

**Comment by i-need-to-tell-you-something** [comment]
This issue is still present on meet.jit.si.

**Comment by mbrodala** [comment]
Maybe fixed with https://github.com/jitsi/jitsi-meet/pull/13520?

**Comment by saghul** [comment]
Yep, we forgot to close this one.

**Comment by ls-1N** [comment]
Should #13520 be live on meet.jit.si? Because I am still getting the issue there.

**Comment by saghul** [comment]
It's not live yet.

**Comment by ls-1N** [comment]
How might I find out when it is live?

**Comment by ls-1N** [comment]
Ah, then I'm still experiencing unwanted actions when releasing some key combinations that happen to include the key that without modifiers should actually trigger an action in Jitsi Meet.

Observed:
Releasing (but not starting the press of) the hotkey combination Windows+Shift+w acts as if I had pressed w (Toggle tile view). Same issue with e.g. Windows+Shift+s.

Expected:
Pressing w while one or more modifier keys are held will not trigger the "Toggle tile view" action.

**Comment by saghul** [comment]
> Releasing (but not starting the press of)

How do you release without starting the press?

**Comment by ls-1N** [comment]
I start it while another window is in focus and end it when the browser with Jitsi Meet open is focused. To also be a bit less ambiguous:
The "Toggle tile view" function gets triggered when pressing Windows+Shift+s while Jitsi Meet has focus:
- pressing and then releasing - true
- pressing (not releasing) - false
- (not pressing) releasing - true

**Comment by michaelkuhn** [comment]
I just found this thread while debugging a weird problem I was having with Jitsi today: I have Super+M mapped to muting my microphone, but this also triggers Jitsi's mute shortcut. This can lead to double-muting (microphone + Jitsi) and can also easily get out of sync, depending on which window I have focused when using the shortcut.

Is this to be expected? I was quite surprised by it. #13520 seems to specifically exclude Ctrl, but not Super. I'm using Chrome on GNOME/Wayland.
