### ISSUE TITLE
"disableThirdPartyRequests: true" does not disable connecting callstats.io

### ISSUE THREAD

**Issue by rg-artcom** [jitsi/jitsi-meet#8113]
### Description:

The Ubuntu server installation with deb packages is configured with a my.server-config.js which includes
config  = {
  [..]
  disableThirdPartyRequests: true,
  [..]
}
But using the jtisi meet with a browser connects to api.callstat.io 

### Steps to reproduce:

1. Install jitsi meet on ubuntu 20.04 with the package system and configure it with the option "disableThirdPartyRequests: true"
2. Open your browser and activate the developer tools / network analysis
3. Open a link to your new jitsi meet server installation
4. You will see the browser tries to connect to api.callstats.io

### Expected behavior:

No other servers are connected while using jitsi meet, only the server of the installation.

### Actual behavior:

api.callstats.io is connected by the browser

### Server information:

- Jitsi Meet version: 2.0.5142-1
- Operating System: Ubuntu 20.04 64bit

### Client information:

- Browser / app version: Firefox 82.0.3
- Operating System: Linux Mint 19.3

**Comment by saghul** [comment]
Thanks for the report!

**Comment by saghul** [comment]
This got fixed in https://github.com/jitsi/lib-jitsi-meet/commit/4980889b24716c383311aadd760d958f6ff58277 but hasn't made it to a stable release yet. Can you check the unstable / nightly ones?

**Comment by rg-artcom** [comment]
Sorry, can't test it. Still have problems to get the 'stable' running 'stable' ("Unfortunately, something went wrong" problem). But I will test it, if it's in the  next stable release.
