### ISSUE TITLE
jitsi-meet-prosody: Unable to load module 'roster_command': /usr/lib/prosody/modules/mod_roster_command.lua: No such file or directory

### ISSUE THREAD

**Issue by paulmenzel** [jitsi/jitsi-meet#8388]
Probably introduced by merge/pull request https://github.com/jitsi/jitsi-meet/pull/8381.

Upgrading the package *jitsi-meet-prosody* to version 1.0.4638-1 fails:

```
$ sudo apt full-upgrade
[…]
Get:7 https://download.jitsi.org unstable/ jitsi-meet-prosody 1.0.4638-1 [43.2 kB]
[…]
Setting up jitsi-meet-prosody (1.0.4638-1) ...
Component "focus.jitsi.molgen.mpg.de" "client_proxy"
modulemanager       error	Unable to load module 'roster_command': /usr/lib/prosody/modules/mod_roster_command.lua: No such file or directory
Failed to load module 'roster_command': /usr/lib/prosody/modules/mod_roster_command.lua: No such file or directory
dpkg: error processing package jitsi-meet-prosody (--configure):
 installed jitsi-meet-prosody package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of jitsi-meet-turnserver:
 jitsi-meet-turnserver depends on jitsi-meet-prosody; however:
  Package jitsi-meet-prosody is not configured yet.
[…]
$ dpkg -l jitsi-meet-prosody
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name               Version      Architecture Description
+++-==================-============-============-====================================
iF  jitsi-meet-prosody 1.0.4638-1   all          Prosody configuration for Jitsi Meet
$ dpkg -S /usr/share/jitsi-meet/prosody-plugins/mod_roster_command.lua
jitsi-meet-prosody: /usr/share/jitsi-meet/prosody-plugins/mod_roster_command.lua
```

**Comment by paulmenzel** [comment]
So the module is in `/usr/share/jitsi-meet`, and not `/usr/lib`.

    $ dpkg -S mod_roster_command
    jitsi-meet-prosody: /usr/share/jitsi-meet/prosody-plugins/mod_roster_command.lua
    jitsi-meet-prosody: /usr/share/jitsi-meet/prosody-plugins/mod_roster_command.patch

**Comment by paulmenzel** [comment]
`sudo strace -ff dpkg --configure -a` shows the lines below:

```
[pid 14108] execve("/usr/local/sbin/lua5.2", ["lua5.2", "/usr/bin/prosodyctl", "mod_roster_command", "subscribe", "focus.jitsi.molgen.mpg.de", "focus@auth.jitsi.molgen.mpg.de"], 0x7fff1dce86c8 /* 29 vars */) = -1 ENOENT (No such file or directory)
[pid 14108] execve("/usr/local/bin/lua5.2", ["lua5.2", "/usr/bin/prosodyctl", "mod_roster_command", "subscribe", "focus.jitsi.molgen.mpg.de", "focus@auth.jitsi.molgen.mpg.de"], 0x7fff1dce86c8 /* 29 vars */) = -1 ENOENT (No such file or directory)
[pid 14108] execve("/usr/sbin/lua5.2", ["lua5.2", "/usr/bin/prosodyctl", "mod_roster_command", "subscribe", "focus.jitsi.molgen.mpg.de", "focus@auth.jitsi.molgen.mpg.de"], 0x7fff1dce86c8 /* 29 vars */) = -1 ENOENT (No such file or directory)
[pid 14108] execve("/usr/bin/lua5.2", ["lua5.2", "/usr/bin/prosodyctl", "mod_roster_command", "subscribe", "focus.jitsi.molgen.mpg.de", "focus@auth.jitsi.molgen.mpg.de"], 0x7fff1dce86c8 /* 29 vars */) = 0
```

**Comment by paulmenzel** [comment]
```
$ dpkg -l prosody
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  prosody        0.11.2-1     amd64        Lightweight Jabber/XMPP server
```

**Comment by paulmenzel** [comment]
The configuration file was changed by the postinst script:

    -Component "focus.jitsi.molgen.mpg.de"
    +Component "focus.jitsi.molgen.mpg.de" "client_proxy"
    +    target_address = "focus@auth.jitsi.molgen.mpg.de"

**Comment by paulmenzel** [comment]
*jitsi-meet-token* is not installed, so the plugin path is not included:

    $ sudo head -2 /etc/prosody/conf.avail/jitsi.molgen.mpg.de.cfg.lua
    -- Plugins path gets uncommented during jitsi-meet-tokens package install - that's where token plugin is located
    --plugin_paths = { "/usr/share/jitsi-meet/prosody-plugins/" }

**Comment by paulmenzel** [comment]
Even after `sudo apt install jitsi-meet-tokens` – What is that for and what is the application ID? – the second line was still commented, so I manually edited the Lua configuration file.

**Comment by damencho** [comment]
The plugins path is enabled by default: https://github.com/jitsi/jitsi-meet/blob/e30b2e14a5ecd709789ddc8fde3205f4779046e1/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L1

**Comment by damencho** [comment]
prosody-plugins are now bundled inside jitsi-meet-prosody package:
https://github.com/jitsi/jitsi-meet/blob/e30b2e14a5ecd709789ddc8fde3205f4779046e1/debian/jitsi-meet-prosody.install#L2

**Comment by damencho** [comment]
If you uncomment plugin_paths does it work?

**Comment by paulmenzel** [comment]
Thank you for the quick response.

https://github.com/jitsi/jitsi-meet/commit/e11d4d3101e5228bf956a69a9e8da73d0aee7949 indeed changed the example configuration file. Should an update hook be added to also update existing configuration files?

I removed *jitsi-meet-tokens* again.

Yes, with the active `plugin_paths` the package update succeeded.

**Comment by bgrozev** [comment]
@paulmenzel Thanks for digging into it and finding the cause. Should be fixed with #8390

**Comment by cedws** [comment]
Sorry to be annoying but when will this fix be released? The packages for Ubuntu are still failing on the postinst step.

**Comment by raphael10-collab** [comment]
In Ubuntu 18.04.4 I'm getting issues as well with Jitsi-meet-prosody : https://github.com/jitsi/jitsi-meet/issues/9129

**Comment by damencho** [comment]
The fix mentioned by Boris is already in latest stable.

**Comment by morlac** [comment]
I got this error too on Ubuntu 18.04.5 LTS with jitsi testing in apt sources.list:

```
modulemanager       error	Unable to load module 'roster_command': /usr/lib/prosody/modules/mod_roster_command.lua: No such file or directory
Failed to load module 'roster_command': /usr/lib/prosody/modules/mod_roster_command.lua: No such file or directory
```

plugin_paths = { "/usr/share/jitsi-meet/prosody-plugins/" } is enabled

**Comment by morlac** [comment]
I found a solution that worked for me:
somewhere in the update-process the file `/etc/prosody/prosody.cfg.lua` changed and at the end of the file
the line `Include "conf.d/*.cfg.lua"`was missing.
Once I re-added this line the upgrade finished.

**Comment by frukto** [comment]
I think if you install `jicofo` with the default hostname (`localhost`), then the default config from `prosody` (`/etc/prosody/conf.avail/localhost.cfg.lua`) blocks the creation of `/etc/prosody/conf.avail/${JICOFO_HOSTNAME}.cfg.lua` and the fix from #8390 does not apply. So make sure to configure your `jicofo` installation appropriately.

**Comment by sliderxtm** [comment]
Same on fresh install on Ubuntu 20.04.3 LTS:

`modulemanager       error       Unable to load module 'roster_command': /usr/lib/prosody/modules/mod_roster_command.lua: No such file or directory                                                                                            
Failed to load module 'roster_command': /usr/lib/prosody/modules/mod_roster_command.lua: No such file or directory     
`
`# cat /etc/prosody/prosody.cfg.lua | grep plugin
plugin_paths = { "/usr/local/lib/prosody/modules" }
-- It looks for mod_modulename.lua in the plugins folder, so make sure that exists too.
`

however:
`# ls -la /usr/share/jitsi-meet/prosody-plugins/ | grep roster
-rw-r--r--  1 root root  5823 янв 25 19:38 mod_roster_command.lua
-rw-r--r--  1 root root  2486 янв 25 19:38 mod_roster_command.patch`

**Comment by sliderxtm** [comment]
if first install **jitsi-meet-prosody** and after it  **jitsi-meet** , then no error

**Comment by saghul** [comment]
What prosody version do you have installed?

**Comment by tetourne** [comment]
I have version 0.11.13-1 of prosody.

**Comment by saghul** [comment]
You need to install Prosody 0.12 before installing Jitsi Meet.

**Comment by msplival** [comment]
I run into this issue upgrading my jitsy server from bionic to focal. 
The solution was, as mentioned https://github.com/jitsi/jitsi-meet/issues/8388#issuecomment-848827493.

After that 'apt-get -f install' fixed all the broken packages. 
So... this should not be 'stale'.

**Comment by npriv-ic1** [comment]
For me, it was an apparently broken jicofo config file, under `/etc/jitsi/jicofo` that still existed despite running `sudo apt purge jitsi*`. Removing it manually made it work again.

**Comment by saghul** [comment]
> I run into this issue upgrading my jitsy server from bionic to focal.

We can't really automate that because we no longer support such old Ubuntu versions. See the supported Debian / Ubuntu versions here: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart
