### ISSUE TITLE
Android app does not work with more than 2 participants

### ISSUE THREAD

**Issue by albinou** [jitsi/jitsi-meet#8713]
### Description:

Video and audio stops working when a third participants joins a conference hosted by meet.jit.si. The Android app is not disconnected, and the chat still works fine.

### Steps to reproduce:

1. Start a conference on mit.jit.si with the Android app
2. Another participants joins the conference (from another Internet access)
3. Sound and video works perfectly between the 2 participants
4. A third participant joins the conference (from still another Internet access)

### Expected behavior:

- Sound and video should be sent/received by each participants
- Or the Android app should at least tell me what's wrong

### Actual behavior:

- The Android app does not receive any sound & video from other participants.
- The 2 other participants do not receive the sound & video from the Android app.

### Server information:

- mit.jit.si server

### Client information:

- App version: 20.6.2 downloaded from the Play store
- Operating System: Android
- Samsung Galaxy Tab

### Additional information:

Surprisingly:
1. the Android app works fine with other servers like framatalk.org
2. the meet.jit.si conference works when using a chrome browser on a computer behind the same internet access
3. the Android app works with meet.jit.si if using another internet access (LTE with WiFi tethering)

I don't understand how it could be related to the ISP. If ever useful, I let you know this has been tested with a French ISP (Free).

Is there any way to enable some logs in the Android app so I can provide them?
Thanks in advance!

**Comment by ahabiba** [comment]
I have the same issue, I tried using the sample application on simulator, it works ok on simulator but not on Samsung android phone! have you got it solved?

**Comment by saghul** [comment]
I just tested it and have no issues. Can you try to update to 21.X ?

**Comment by ahabiba** [comment]
I'm assuming that I use latest version of the SDK by the below line :
`implementation ('org.jitsi.react:jitsi-meet-sdk:+') { transitive = true }`

**Comment by saghul** [comment]
You should be, that's 3.5.0, which we released late last week.

**Comment by saghul** [comment]
Without logs there is not much we can do to help though.

**Comment by ahabiba** [comment]
I tried version 3.5.0 , and the problem still there 
` implementation ('org.jitsi.react:jitsi-meet-sdk:3.5.0') { transitive = true }`

Here is attached logcat

[LogCat.txt](https://github.com/jitsi/jitsi-meet/files/6412148/LogCat.txt)

**Comment by saghul** [comment]
So you are not testing against meet.jit.si then. Your comment was misleading since the initial report mentioned explicitly our public deployment.

The first simple test to run is: does your app work with meet.jit.si ?

**Comment by ahabiba** [comment]
Thanks for your reply, and sorry for confusion.

testing against "meet.jit.si" everything works fine, however testing against self hosted I get the mentioned issue.

**Comment by albinou** [comment]
Hi, sorry for the delay in answering.

I did not solved my issue (well, I solved it by using a VPN on the various tablets/phone used behind this ISP connection, but it adds a lot of latency).
I will try to provide you some logcat logs (it may take a few day, since I've only seen this issue when I go to see some family who has Free as ISP).

**Comment by ahabiba** [comment]
I see very wired behavior, when I connect to customer server, mobile send only private IP as ICE candidate!

```
021-05-03 16:13:48.287 15204-15264/? I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] sendIceCandidates [ { candidate: 'candidate:450490162 1 udp 2122260223 192.168.68.57 56290 typ host generation 0 ufrag eoKW network-id 3 network-cost 10',
        sdpMLineIndex: 0,
        sdpMid: 'audio' } ]
```

**Comment by albinou** [comment]
Hi!
So I've been able to run some tests with my nephew (the one who lives behind the ISP where the issue happens).

I had a deep look at ICE logs, but I did not understand much what happens (except that the framatalk.org server seems to only use IPv6 I guess?).

Here are the logs with the meet.jit.si server:

```
2021-05-07 18:02:14.044 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "ufrag" = "544T"
2021-05-07 18:02:14.045 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-id" = "4"
2021-05-07 18:02:14.045 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-cost" = "10"
2021-05-07 18:02:14.051 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "ufrag" = "544T"
2021-05-07 18:02:14.053 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-id" = "3"
2021-05-07 18:02:14.053 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-cost" = "10"
2021-05-07 18:02:14.059 4297-7810/? V/VibratorService: vibrate - package: org.jitsi.meet, token: android.os.Binder@133fb81, usage: 5, effect: Waveform{mTimings=[0, 250, 250, 250], mAmplitudes=[0, -1, 0, -1], mRepeat=-1, mMagnitude=-1, mMagnitudeType=TYPE_NOTIFICATION}, mag: 9999, TYPE_NOTIFICATION
2021-05-07 18:02:14.078 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] sendIceCandidates [ { candidate: 'candidate:2315330679 1 udp 2122262783 2a01:e0a:MASKED_IPV6 39091 typ host generation 0 ufrag 544T network-id 4 network-cost 10',
        sdpMLineIndex: 0,
        sdpMid: 'audio' },
      { candidate: 'candidate:622943561 1 udp 2122194687 192.168.0.41 41280 typ host generation 0 ufrag 544T network-id 3 network-cost 10',
        sdpMLineIndex: 0,
        sdpMid: 'audio' } ]
2021-05-07 18:02:14.078 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "ufrag" = "544T"
2021-05-07 18:02:14.087 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-id" = "4"
2021-05-07 18:02:14.088 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-cost" = "10"
2021-05-07 18:02:14.088 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "ufrag" = "544T"
2021-05-07 18:02:14.088 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-id" = "3"
2021-05-07 18:02:14.088 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-cost" = "10"
2021-05-07 18:02:14.356 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "ufrag" = "544T"
2021-05-07 18:02:14.357 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-id" = "3"
2021-05-07 18:02:14.357 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-cost" = "10"
2021-05-07 18:02:14.363 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] sendIceCandidate: last candidate.
2021-05-07 18:02:14.397 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] sendIceCandidates [ { candidate: 'candidate:87135148 1 udp 8265471 193.123.62.200 59137 typ relay raddr MASKED_PUBLIC_IPV4 rport 12336 generation 0 ufrag 544T network-id 3 network-cost 10',
        sdpMLineIndex: 0,
        sdpMid: 'audio' } ]
2021-05-07 18:02:14.398 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "ufrag" = "544T"
2021-05-07 18:02:14.399 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-id" = "3"
2021-05-07 18:02:14.400 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-cost" = "10"
2021-05-07 18:02:14.497 6370-6384/? I/org.jitsi.meet: Background concurrent copying GC freed 108685(4311KB) AllocSpace objects, 3(56KB) LOS objects, 49% free, 4428KB/8856KB, paused 200us total 106.865ms
2021-05-07 18:02:14.849 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/ChatRoom.js] Jicofo supports restart by terminate: true
2021-05-07 18:02:14.851 6370-6429/? I/JitsiMeetSDK: [modules/RTC/BridgeChannel.js] SenderVideoConstraints: {"idealHeight":360}
2021-05-07 18:02:14.851 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] JingleSessionPC[p2p=false,initiator=false,sid=9hi9vgqkqtv9i] setSenderVideoConstraint: 360
2021-05-07 18:02:14.852 6370-6429/? I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] Queued make video active, audio active task...
2021-05-07 18:02:14.852 6370-6429/? D/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] Make video active, audio active task done!
```

Full logs [here](https://github.com/jitsi/jitsi-meet/files/6460993/Jitsi.Android.3.participants.meet.jit.si.txt).


And here are the logs with the framatalk.org server:

```
2021-05-09 11:21:54.393 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "ufrag" = "1wU7"
2021-05-09 11:21:54.394 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-id" = "4"
2021-05-09 11:21:54.394 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-cost" = "10"
2021-05-09 11:21:54.399 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "ufrag" = "1wU7"
2021-05-09 11:21:54.400 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-id" = "3"
2021-05-09 11:21:54.400 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-cost" = "10"
2021-05-09 11:21:54.409 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] sendIceCandidate: last candidate.
2021-05-09 11:21:54.424 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] sendIceCandidates [ { candidate: 'candidate:2315330679 1 udp 2122262783 2a01:e0a:MASKED_IPV6 59827 typ host generation 0 ufrag 1wU7 network-id 4 network-cost 10',
        sdpMLineIndex: 0,
        sdpMid: 'audio' },
      { candidate: 'candidate:622943561 1 udp 2122194687 192.168.0.41 50387 typ host generation 0 ufrag 1wU7 network-id 3 network-cost 10',
        sdpMLineIndex: 0,
        sdpMid: 'audio' } ]
2021-05-09 11:21:54.425 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "ufrag" = "1wU7"
2021-05-09 11:21:54.427 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-id" = "4"
2021-05-09 11:21:54.427 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-cost" = "10"
2021-05-09 11:21:54.427 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "ufrag" = "1wU7"
2021-05-09 11:21:54.427 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-id" = "3"
2021-05-09 11:21:54.427 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/SDPUtil.js] not translating "network-cost" = "10"
2021-05-09 11:21:54.711 4255-13562/? V/VibratorService: vibrate - package: org.jitsi.meet, token: android.os.Binder@881081d, usage: 5, effect: Waveform{mTimings=[0, 250, 250, 250], mAmplitudes=[0, -1, 0, -1], mRepeat=-1, mMagnitude=-1, mMagnitudeType=TYPE_NOTIFICATION}, mag: 9999, TYPE_NOTIFICATION
2021-05-09 11:21:54.812 5083-5083/? D/Launcher.NotificationListener: onNotificationPosted : org.jitsi.meet number : 0 listener : null
2021-05-09 11:21:54.834 13315-13376/? I/JitsiMeetSDK: [modules/RTC/BridgeChannel.js] SenderVideoConstraints: {"idealHeight":360}
2021-05-09 11:21:54.835 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] JingleSessionPC[p2p=false,initiator=false,sid=47degguohdtmi] setSenderVideoConstraint: 360
2021-05-09 11:21:54.835 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] Queued make video active, audio active task...
2021-05-09 11:21:54.835 13315-13376/? D/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] Make video active, audio active task done!
2021-05-09 11:21:54.851 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] JingleSessionPC[p2p=false,initiator=false,sid=47degguohdtmi] setReceiverVideoConstraint - max frame height: 180
2021-05-09 11:21:54.861 13315-13376/? I/JitsiMeetSDK: [modules/RTC/BridgeChannel.js] Sending ReceiverVideoConstraint with maxFrameHeight=180px
2021-05-09 11:21:54.861 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] JingleSessionPC[p2p=false,initiator=false,sid=47degguohdtmi] setSenderVideoConstraint: 360
2021-05-09 11:21:54.865 13315-13376/? I/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] Queued make video active, audio active task...
2021-05-09 11:21:54.865 13315-13376/? D/JitsiMeetSDK: [modules/xmpp/JingleSessionPC.js] Make video active, audio active task done!
```

Full logs [here](https://github.com/jitsi/jitsi-meet/files/6460997/Jitsi.Android.3.participants.framatalk.org.txt).


Also, maybe it worths to mention that the ISP (Free, France) is using [Carrier-grade NAT](https://fr.wikipedia.org/wiki/Carrier-grade_NAT) with some customers. I am wondering if this could cause an issue?

Thanks for helping me, don't hesitate to ask for more logs if it is needed.
Cheers.

**Comment by akcachy** [comment]
Getting the issue in `jitsi-meet-android-sdk 3.7.0.`
Use case :-
1. When more than two users are joining in the call video frames are not coming although audio is coming and other changes are working as intended.
2. Checked with` jitsi - google playstore `with _meet.jit.si_ server getting the same issue.

**Comment by saghul** [comment]
@akcachy Are also in a similar networking environment?

**Comment by akcachy** [comment]
@saghul Yes on same networking environment with Nat and withouth NAT in both issue is same

**Comment by saghul** [comment]
NAT is not a problem. CGNAT is something different. Are you on an IPv6 only network with CGNAT?
