### ISSUE TITLE
iOS Screen Sharing does not work with self-hosted server

### ISSUE THREAD

**Issue by TwoLeggedCat** [jitsi/jitsi-meet#8970]
### Description:

Screen sharing works using meet.jit.si but not self-hosted servers.

### Steps to reproduce:

1. Setup a self-hosted server with the latest version of the Jitsi server from https://download.jitsi.org/stable/
2. Start screen sharing from iOS app
3. Observe lack of video stream

### Expected behavior:

Screen sharing works

### Actual behavior:

Screen sharing does not work; since the camera is automatically disabled, only the participants initials are displayed. The screen sharing icon is displayed on the participant's tile, however, aside from that, it is as though their camera were off and they were not screen sharing. Sometimes, instead of the initials being displayed, blackness is streamed instead.

### Server information:

- Jitsi Meet version:
> $apt show jitsi-meet
Package: jitsi-meet
Version: 2.0.5390-3

>$apt show jitsi-videobridge
Package: jitsi-videobridge
Version: 1126-1
- Operating System: Ubuntu 20.04.2

### Client information:

- Browser / app version: 21.0.0 (latest at time of writing)
- Operating System: iOS

### Additional information:

Screen sharing works as expected when using meet.jit.si as the server, and this has been reported by other users [here](https://github.com/jitsi/jitsi-meet/issues/5252#issuecomment-810094755). It was also stated there that no server-side update or change should be necessary, hence why this seems to be a bug.

**Comment by saghul** [comment]
Can you reproduce the problem with 2 and with 3 users in a conference?

**Comment by eveslage** [comment]
I can reproduce the issue with our self hosted Jitsi server.

**Comment by TwoLeggedCat** [comment]
> Can you reproduce the problem with 2 and with 3 users in a conference?

Yes; this occurs with 2 users and >2.

**Comment by pdarcos** [comment]
I can confirm the same thing is happening with me with a freshly compiled iOS app from master

**Comment by kleinesfilmroellchen** [comment]
Can reproduce with iOS 14.2 on 7th gen iPad, Jitsi 21.0.0 build 110. Two users were tested; receiving a screen share is not a problem. (Unfortunately, I don't have access to the server information)

**Comment by jallamsetty1** [comment]
> > Can you reproduce the problem with 2 and with 3 users in a conference?
> 
> Yes; this occurs with 2 users and >2.

Do you have p2p enabled in config.js ? The server side version ideally should not have any effect on the 1-1 call if p2p is enabled.

**Comment by TwoLeggedCat** [comment]
> > > Can you reproduce the problem with 2 and with 3 users in a conference?
> > 
> > 
> > Yes; this occurs with 2 users and >2.
> 
> Do you have p2p enabled in config.js ? The server side version ideally should not have any effect on the 1-1 call if p2p is enabled.

Yes, but, come to think of it, the clients may have had p2p mode disabled. Will check without it disabled later.

**Comment by TwoLeggedCat** [comment]
> > > > Can you reproduce the problem with 2 and with 3 users in a conference?
> > > 
> > > 
> > > Yes; this occurs with 2 users and >2.
> > 
> > 
> > Do you have p2p enabled in config.js ? The server side version ideally should not have any effect on the 1-1 call if p2p is enabled.
> 
> Yes, but, come to think of it, the clients may have had p2p mode disabled. Will check without it disabled later.

Same behavior with p2p mode enabled (or, rather, not disabled). Very strange; I would expect that to make a difference.

**Comment by eriktor1** [comment]
We have the same issue with our own 3 jitsi meet servers. We tried also various available Jitsi servers, and seems most of them have the same issue!
to be more precise, when sharing screen from Jitsi Android App, a remote user with iOs will not receive content (p2p). And if you have 3 or more participants , none of them will receive content (even Chrome on windows!).
But it works well on JIT.SI!

**Comment by TwoLeggedCat** [comment]
I am now using version 21.1.0 of the iOS client, and screen sharing works _with p2p mode_. With "Disable Peer-to-peer mode" on, it still does not work. @saghul are you aware of any non-default configuration values on meet.jit.si that could be causing it to work there? I can try them on my server. The only changes I can recall making to my configuration were those documented in [this guide](https://jitsi.github.io/handbook/docs/devops-guide/secure-domain) for setting up authentication. Worth noting to all interested that it does work with some self-hosted setups, as seen in #9012.

**Comment by saghul** [comment]
We haven't gotten to the bottom of this yet.

**Comment by eriktor1** [comment]
we could solve partially modifying the react-native-Webrtc as suggested in https://community.jitsi.org/t/screen-sharing-from-android-app-to-browser-on-self-hosted-instance-does-not-work/85734/14 (thanks @Alan_tulai !!!!!).
But why its working in JIT-SI without the fix? Also strange that so few are complaining about this issue. nobody is using the app or sdk with  their own server?  Also strange there has been no fix for it in the latest stable.

we were thinking that its possible that its the way the jisti autoinstallation configure the server (will try to understand if on self hosted its using SFU; while on JIT.SI not)

**Comment by saghul** [comment]
That's odd. That flag turns on the screen-share optimizations in WebRTC.

**Comment by eriktor1** [comment]
also believe that the title of this topic is too specific. Should be merged with various topics out there.

With the react-native-webrtc fix, we could actually  solve **3 key issues!**!!

- app/sdk not able to share content with iphone/safari
- app/sdk not able to share content with 3 o more participants (OF ANY KIND)-
- compatibiliy with iOs/Chrome (!!!): without it, chrome/iOS couldnt connect to meetings on self hosted servers!

how this fix is related (or not) with JIT.SI configuration or topology is really unclear to us at this time.

**Comment by AliKarpuzoglu** [comment]
did anyone manage to get it to work on self-hosted servers? Could there be a minimum server version?

**Comment by saghul** [comment]
There is nothing specific to the server. We just releases a new stable so please test with that people.

I think it's something related to screen sharing w/o simulcast and prioritizing in the bridge. A number of bugs have been fixed in the area recently.

**Comment by AliKarpuzoglu** [comment]
> There is nothing specific to the server. We just releases a new stable so please test with that people.
> 
> I think it's something related to screen sharing w/o simulcast and prioritizing in the bridge. A number of bugs have been fixed in the area recently.

Will try the new update later. Turning simulcast off fixes the screenshare issue, as you said

**Comment by AliKarpuzoglu** [comment]
So we tried the newest version, but it seems to still have issues, when Simulcast is turned on @saghul

**Comment by joelfischerr** [comment]
The latest build 21.2.0 (114) fixed all issues for me.

**Comment by subhash4android** [comment]
> > There is nothing specific to the server. We just releases a new stable so please test with that people.
> > I think it's something related to screen sharing w/o simulcast and prioritizing in the bridge. A number of bugs have been fixed in the area recently.
> 
> Will try the new update later. Turning simulcast off fixes the screenshare issue, as you said

Hi,
Is it fixed for ios scrrenshare?

**Comment by subhash4android** [comment]
Hi all,

Is ios screensharing working for more than 2 participants.
Currently only one to one ios screensharing is working on apps.

on self hosted server, we are unable to do screensharing for more than 2 participants.
Did anyone solved this issue.

Am i missing something in code.

Regards,
Subhash.

**Comment by TwoLeggedCat** [comment]
> We just releases a new stable so please test with that people.

Sorry it's been a while; the server we were hosting on was unavailable for a long time, but I can confirm that it now works with no changes to client or server aside from standard updates.

**Comment by saghul** [comment]
Thanks for confirming!

**Comment by thmna** [comment]
> Sorry it's been a while; the server we were hosting on was unavailable for a long time, but I can confirm that it now works with no changes to client or server aside from standard updates.

@TwoLeggedCat Did you resolve the issue of screensharing on iOS using self hosted server ?If so, please share how you have done it? Thankyou
