### ISSUE TITLE
Latest Unstable - Authentication issues - Moderator Status Lost on Refresh; Ending Recording Crashes Meeting

### ISSUE THREAD

**Issue by Freddie-m** [jitsi/jitsi-meet#9502]
### Description:

There seems to be a number of issues with the latest unstable:

1. Moderator access level is lost when screen is refreshed or when starting a new meeting after ending previous one. 
2. Ending a recording results in a bridge/meeting crash (goes into a reconnection)
3. Jibri recording has no media, only shows avatar

### Steps to reproduce:

1. Start a new meeting and activate recording.  
2. End the recording. Meeting crashes.
3. Start a new meeting on the same browser. Moderator options not available
4. Check profile to confirm still logged in as moderator. 
5. Log out, meeting ends. Then restart meeting, enter credentials, moderator controls now available 

### Expected behavior:

Moderator controls should be available once authenticated and should remain available even after a browser refresh or when a new meeting is created in the same browser immediately after.

### Actual behavior:

- Moderator controls are missing on refresh and meeting restart
- Jibri activation is successful but no media is recorded 
- Ending recording crashes meeting

### Server information:

- Jitsi Meet version: 2.0.6041-1
- Operating System: Ubuntu Server 20.04 LTS

### Client information:

- Browser / app version: Latest Chromium, Brave, Electron App
- Operating System: OSX 10.13.6

### Additional information:

It's quite possible that these issues are transient and only showing up because this is an unstable version, but I've reproduced them in the last 2 unstable versions and they appear to be persisting. Just want to be sure they're on the radar, if nothing else. 

I also wonder if these latest versions have greater resource demands. The fact that Jibri records no media and crashes when meeting stops makes me think this could be a JVB problem. There is nothing significant in JVB or Jibri logs. Ffmpeg log confirms no data is sent. Jicofo shows Jibri successfully joined Brewery otherwise, no significant issue, but it does show a packet listener exception viz:

> Jicofo 2021-07-06 21:39:41.853 SEVERE: [29] org.jivesoftware.smack.AbstractXMPPConnection$6.run: Exception in packet listener

Not sure if that's significant.

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you.

Have you tested the same with stable version?

Does 3way call work on your deployment?

**Comment by fremzy** [comment]
Hi @damencho, it's Freddie.

I figured it'd be better to create an issue here since this is the unstable version and I don't want to throw people off on the forum. Stable works fine, 3-way call and all. I made these observations in my test environment and thought to mention them because I know there's no authentication on meet.jit.si, so these could slide under the radar (IF they're actually issues - not just a problem with my deployment). I can create a thread in the forum if that's preferable?

**Comment by damencho** [comment]
> I made these observations in my test environment and thought to mention them because I know there's no authentication on meet.jit.si, so these could slide under the radar (_IF_ they're actually issues - not just a problem with my deployment). I can create a thread in the forum if that's preferable?

Nope. Don't worry, this is my automatic answer when I haven't seen this being discussed in the forum. 

We had prepared a stable release already, which is 2.0.6030-1 can you verify do you see the same there? 

Do you reproduce everytime the `Exception in packet listener`? Can you upload the logs of such an error?

**Comment by Freddie-m** [comment]
Yes, that exception is reproduced every time. Just tried again and sure enough, it's there. I have the log, but for some reason, I'm getting errors trying to attach it right now (getting a "Something went really wrong..." error from github). I'll try again in a little while.

I don't have any environment handy to deploy 2.0.6030-1 to test right now. I'll see if I can figure something out.

**Comment by Freddie-m** [comment]
Thanks @damencho. Changing trusted-domains from:

> trusted-domains: recorder.meet.myjitsi.com


to

> trusted-domains: [recorder.meet.myjitsi.com]

fixed it per your advise and reference - https://github.com/jitsi/jicofo/blob/1b8db233f0404876baf3df8f486dbeda2a700ef3/src/main/resources/reference.conf#L307 

Media is captured in recording now and meeting no longer crashes when recording is stopped.

**Comment by damencho** [comment]
Thanks for the update.

**Comment by damencho** [comment]
The authentication issue is still present as @Freddie-m reported offline to me.

**Comment by damencho** [comment]
We are all hands full right now and we are not actively using this feature, please if anyone can debug it at least find which commit broke it or something like that. Any help is welcome. 
I will try to squeeze it in the next month or so.

**Comment by Freddie-m** [comment]
Confirming authentication issue is also fixed. **All issues now marked fixed!** ✅
Thanks for squeezing this into your tight schedule, @damencho.
