### ISSUE TITLE
Echo Issue in ios to ios app

### ISSUE THREAD

**Issue by Hassanilyas143** [jitsi/jitsi-meet#9963]
When using the Jitsi-Meet app on the iPad there is a noticeable echo in the meeting.

**Comment by saghul** [comment]
What iPad model is that?

**Comment by Hassanilyas143** [comment]
iPad pro 11 2nd generation

**Comment by saghul** [comment]
There is an iPad mode without a working echo canceler, but that's not it IIRC.

We use the hardware AEC, so alas there is nothing else we can do here.

**Comment by Hassanilyas143** [comment]
The same issue exists in iPhone to iPhone

**Comment by saghul** [comment]
Can you describe how you are reproducing this? What audio device are you using? Are you in the same room?

**Comment by Hassanilyas143** [comment]
Using no audio device with iPhone. Just iPhone to iPhone. And both iPhones are not in the same room and are miles apart. And it's not exactly like an echo, it's the audio repeating itself multiple times.

**Comment by saghul** [comment]
What app version did you test? Are you able to gather logs with Console.app ?

**Comment by MeetSoniBV** [comment]
Our team is facing same, we are also using Jitsi SDK for Audio/Video calling functionality in our app where we stuck at a point, we are continuously facing echo problem while calling, we have checked all different version of Jitsi SDK but still facing same problem.

**Comment by shehryarxeven** [comment]
Facing same issue here when calling from iOS to iOS. Tried using the Jitsi sample app and echo was there as well.

**Comment by hasyapanchasara** [comment]
Hi @saghul I am too facing the same issue as mentioned by @MeetSoniBV

**Comment by kmoreau** [comment]
Hello, same issue here. Do you find some information about this ?

**Comment by Hassanilyas143** [comment]
@kmoreau nothing

**Comment by Hassanilyas143** [comment]
Any update?

**Comment by kmoreau** [comment]
nothing on my side :/

**Comment by Hassanilyas143** [comment]
Any update guys?

**Comment by saghul** [comment]
No updates yet, sorry. Can you reproduce it with the latest Jitsi Meet beta?

**Comment by saghul** [comment]
This has been fixed in the latest SDK and app. There was an issue where audio would be duplicated, creating an echo effect.

**Comment by Hassanilyas143** [comment]
I have the same issue faced again.

**Comment by Hassanilyas143** [comment]
@saghul please consider reopening this issue because this issue is not fixed.

**Comment by saghul** [comment]
What app / SDK version did you test?

**Comment by zhenghow93** [comment]
> This has been fixed in the latest SDK and app. There was an issue where audio would be duplicated, creating an echo effect.

Hi @saghul , could you reference the commit(s) that fixed that issue? One of our users seemed to face the echo issue as well (seems like an isolated issue), would be good if we can just cherrypick the commits for the fix to try it out. Currently using code from release 2.0.6726
